HACC_GPM: PyCosmoTools Class Reference
PyCosmoTools Class Reference
#include <pycosmotools.hpp>
Public Member Functions
PyCosmoTools ()
PyCosmoTools (int ng_, float rl_, int world_size_, int world_rank_, int *local_coords_, int *local_grid_size_)
~PyCosmoTools ()
void loadPython ()
void loadPyCosmoNotPython ()
void freePyCosmo ()
void freePython ()
void import (char *module)
void initialize ()
void powerSpectrumStep (float *power_spectrum, int nbins, int nfields, int step, float a, float z)
void analysisStep (float *particles, int nparticles, int nfields, int step, float a, float z)
void initialConditionsStep (float *power_spectrum, int nbins, int npowerfields, float *particles, int nparticles, int nparticlefields, int step, float a, float z)
void finalStep (float *power_spectrum, int nbins, int npowerfields, float *particles, int nparticles, int nparticlefields, int step, float a, float z)
Public Attributes
int ng
float rl
int world_size
int world_rank
int local_coords [3]
int local_grid_size [3]
int initialized
Detailed Description
Definition at line 1 of file pycosmotools.hpp.
Constructor & Destructor Documentation
PyCosmoTools() [1/2]
PyCosmoTools::PyCosmoTools ()
Definition at line 7 of file pycosmo.cpp.
{
    //initPyCosmo();
    initialized = 0;
}
References initialized.
PyCosmoTools() [2/2]
PyCosmoTools::PyCosmoTools (int ng_, float rl_, int world_size_, int world_rank_, int * local_coords_, int * local_grid_size_)
Definition at line 12 of file pycosmo.cpp.
{
    ng = ng_;
    rl = rl_;
    world_size = world_size_;
    world_rank = world_rank_;
    local_coords[0] = local_coords_[0];
    local_coords[1] = local_coords_[1];
    local_coords[2] = local_coords_[2];
    local_grid_size[0] = local_grid_size_[0];
    local_grid_size[1] = local_grid_size_[1];
    local_grid_size[2] = local_grid_size_[2];
    initialized = 0;
}
References initialized, local_coords, local_grid_size, ng, rl, world_rank, and world_size.
~PyCosmoTools()
PyCosmoTools::~PyCosmoTools ()
Definition at line 26 of file pycosmo.cpp.
{
    if (initialized == 1){
        finalizePyCosmo();
        return;
    }
    if (initialized == 2){
        finalizePyCosmoNotPython();
        return;
    }
}
References finalizePyCosmo(), finalizePyCosmoNotPython(), and initialized.
Member Function Documentation
analysisStep()
void PyCosmoTools::analysisStep (float * particles, int nparticles, int nfields, int step, float a, float z)
Definition at line 71 of file pycosmo.cpp.
{
    int dims[2] = {nparticles,nfields};
    doAnalysisStep(particles,dims,2,step,a,z);
}
References doAnalysisStep().
Referenced by main(), and HACCGPM::serial::PyAnalysis().
finalStep()
void PyCosmoTools::finalStep (float * power_spectrum, int nbins, int npowerfields, float * particles, int nparticles, int nparticlefields, int step, float a, float z)
Definition at line 82 of file pycosmo.cpp.
{
    int power_dims[2] = {nbins,npowerfields};
    int particle_dims[2] = {nparticles,nparticlefields};
    doFinalStep(power_spectrum,power_dims,2,particles,particle_dims,2,step,a,z);
}
References doFinalStep().
Referenced by main().
freePyCosmo()
void PyCosmoTools::freePyCosmo ()
Definition at line 37 of file pycosmo.cpp.
{
    finalizePyCosmoNotPython();
    initialized = 0;
}
References finalizePyCosmoNotPython(), and initialized.
freePython()
void PyCosmoTools::freePython ()
Definition at line 42 of file pycosmo.cpp.
{
    finalizePyCosmo();
    initialized = 0;
    return;
}
References finalizePyCosmo(), and initialized.
Referenced by serial().
import()
void PyCosmoTools::import (char * module)
Definition at line 58 of file pycosmo.cpp.
{
    importModule(module);
}
References importModule().
Referenced by main(), and serial().
initialConditionsStep()
void PyCosmoTools::initialConditionsStep (float * power_spectrum, int nbins, int npowerfields, float * particles, int nparticles, int nparticlefields, int step, float a, float z)
Definition at line 76 of file pycosmo.cpp.
{
    int power_dims[2] = {nbins,npowerfields};
    int particle_dims[2] = {nparticles,nparticlefields};
    doInitialConditionsStep(power_spectrum,power_dims,2,particles,particle_dims,2,step,a,z);
}
References doInitialConditionsStep().
Referenced by main().
initialize()
void PyCosmoTools::initialize ()
Definition at line 62 of file pycosmo.cpp.
{
    initAnalysisObjects(ng,rl,world_size,world_rank,local_coords,local_grid_size);
}
References initAnalysisObjects(), local_coords, local_grid_size, ng, rl, world_rank, and world_size.
Referenced by main(), and serial().
loadPyCosmoNotPython()
void PyCosmoTools::loadPyCosmoNotPython ()
Definition at line 53 of file pycosmo.cpp.
{
    initPyCosmoNoLoad();
    initialized = 2;
}
References initialized, and initPyCosmoNoLoad().
Referenced by serial().
loadPython()
void PyCosmoTools::loadPython ()
Definition at line 48 of file pycosmo.cpp.
{
    initPyCosmo();
    initialized = 1;
}
References initialized, and initPyCosmo().
Referenced by main().
powerSpectrumStep()
void PyCosmoTools::powerSpectrumStep (float * power_spectrum, int nbins, int nfields, int step, float a, float z)
Definition at line 66 of file pycosmo.cpp.
{
    int dims[2] = {nbins,nfields};
    doPowerSpectrumStep(power_spectrum,dims,2,step,a,z);
}
References doPowerSpectrumStep().
Referenced by main().
Member Data Documentation
initialized
int PyCosmoTools::initialized
Definition at line 11 of file pycosmotools.hpp.
Referenced by freePyCosmo(), freePython(), loadPyCosmoNotPython(), loadPython(), PyCosmoTools(), PyCosmoTools(), and ~PyCosmoTools().
local_coords
int PyCosmoTools::local_coords[3]
Definition at line 9 of file pycosmotools.hpp.
Referenced by initialize(), and PyCosmoTools().
local_grid_size
int PyCosmoTools::local_grid_size[3]
Definition at line 10 of file pycosmotools.hpp.
Referenced by initialize(), and PyCosmoTools().
ng
int PyCosmoTools::ng
Definition at line 5 of file pycosmotools.hpp.
Referenced by initialize(), and PyCosmoTools().
rl
float PyCosmoTools::rl
Definition at line 6 of file pycosmotools.hpp.
Referenced by initialize(), and PyCosmoTools().
world_rank
int PyCosmoTools::world_rank
Definition at line 8 of file pycosmotools.hpp.
Referenced by pycosmo.analysistools.PyCosmoAnalysis::__set_power_spectrum__(), initialize(), and PyCosmoTools().
world_size
int PyCosmoTools::world_size
Definition at line 7 of file pycosmotools.hpp.
Referenced by initialize(), and PyCosmoTools().
The documentation for this class was generated from the following files:
/home/hqureshi/HACC_GPM/pycosmotools/include/pycosmotools.hpp
/home/hqureshi/HACC_GPM/pycosmotools/src/pycosmo.cpp