HACC_GPM: /home/hqureshi/HACC_GPM/src/grid_exchange/gridreturnkernels.cu File Reference
gridreturnkernels.cu File Reference
#include <stdlib.h>
#include <stdio.h>
#include "haccgpm.hpp"
#include "gridexchangekernels.hpp"
Functions
__global__ void loadXReturnKernel (float4 *__restrict d_left, float4 *__restrict d_right, const float4 *__restrict d_in, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
__global__ void storeXReturnKernel (const float4 *__restrict d_left, const float4 *__restrict d_right, float4 *__restrict d_out, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
__global__ void loadYReturnKernel (float4 *__restrict d_left, float4 *__restrict d_right, const float4 *__restrict d_in, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
__global__ void storeYReturnKernel (const float4 *__restrict d_left, const float4 *__restrict d_right, float4 *__restrict d_out, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
__global__ void loadZReturnKernel (float4 *__restrict d_left, float4 *__restrict d_right, const float4 *__restrict d_in, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
__global__ void storeZReturnKernel (const float4 *__restrict d_left, const float4 *__restrict d_right, float4 *__restrict d_out, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
Function Documentation
loadXReturnKernel()
__global__ void loadXReturnKernel (float4 *__restrict d_left, float4 *__restrict d_right, const float4 *__restrict d_in, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
Definition at line 6 of file gridreturnkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if(idx >= n)return;
    int3 idx3dLeft = HACCGPM::parallel::get_local_index(idx,overload,local_grid_size.y,local_grid_size.z);
    idx3dLeft.y += overload;
    idx3dLeft.z += overload;
    int3 idx3dRight = make_int3((local_grid_size.x - idx3dLeft.x) - 1,idx3dLeft.y,idx3dLeft.z);
    idx3dLeft.x += overload;
    idx3dRight.x += overload;
    int idxLeft = idx3dLeft.x * ol_grid_size.y * ol_grid_size.z + idx3dLeft.y * ol_grid_size.z + idx3dLeft.z;
    int idxRight = idx3dRight.x * ol_grid_size.y * ol_grid_size.z + idx3dRight.y * ol_grid_size.z + idx3dRight.z;
    float4 left = __ldg(&d_in[idxLeft]);
    float4 right = __ldg(&d_in[idxRight]);
    //left.w = 0;
    //right.w = 0;
    d_left[idx] = left;
    d_right[idx] = right;
}
References do_return(), and HACCGPM::parallel::get_local_index().
Referenced by XReturn::load().
loadYReturnKernel()
__global__ void loadYReturnKernel (float4 *__restrict d_left, float4 *__restrict d_right, const float4 *__restrict d_in, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
Definition at line 128 of file gridreturnkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if(idx >= n)return;
    int3 idx3dLeft = HACCGPM::parallel::get_local_index(idx,ol_grid_size.x,overload,local_grid_size.z);
    //idx3dLeft.y += overload;
    idx3dLeft.z += overload;
    int3 idx3dRight = make_int3(idx3dLeft.x,(local_grid_size.y - idx3dLeft.y) - 1,idx3dLeft.z);
    idx3dLeft.y += overload;
    idx3dRight.y += overload;
    int idxLeft = idx3dLeft.x * ol_grid_size.y * ol_grid_size.z + idx3dLeft.y * ol_grid_size.z + idx3dLeft.z;
    int idxRight = idx3dRight.x * ol_grid_size.y * ol_grid_size.z + idx3dRight.y * ol_grid_size.z + idx3dRight.z;
    float4 left = __ldg(&d_in[idxLeft]);
    float4 right = __ldg(&d_in[idxRight]);
    //left.w = 0;
    //right.w = 0;
    d_left[idx] = left;
    d_right[idx] = right;
}
References do_return(), and HACCGPM::parallel::get_local_index().
Referenced by YReturn::load().
loadZReturnKernel()
__global__ void loadZReturnKernel (float4 *__restrict d_left, float4 *__restrict d_right, const float4 *__restrict d_in, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
Definition at line 264 of file gridreturnkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if(idx >= n)return;
    int3 idx3dLeft = HACCGPM::parallel::get_local_index(idx,ol_grid_size.x,ol_grid_size.x,overload);
    //idx3dLeft.y += overload;
    //idx3dLeft.z += overload;
    int3 idx3dRight = make_int3(idx3dLeft.x,idx3dLeft.y,(local_grid_size.z - idx3dLeft.z) - 1);
    idx3dLeft.z += overload;
    idx3dRight.z += overload;
    int idxLeft = idx3dLeft.x * ol_grid_size.y * ol_grid_size.z + idx3dLeft.y * ol_grid_size.z + idx3dLeft.z;
    int idxRight = idx3dRight.x * ol_grid_size.y * ol_grid_size.z + idx3dRight.y * ol_grid_size.z + idx3dRight.z;
    float4 left = __ldg(&d_in[idxLeft]);
    float4 right = __ldg(&d_in[idxRight]);
    //left.w = 0;
    //right.w = 0;
    d_left[idx] = left;
    d_right[idx] = right;
}
References do_return(), and HACCGPM::parallel::get_local_index().
Referenced by ZReturn::load().
storeXReturnKernel()
__global__ void storeXReturnKernel (const float4 *__restrict d_left, const float4 *__restrict d_right, float4 *__restrict d_out, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
Definition at line 61 of file gridreturnkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if(idx >= n)return;
    int3 idx3dLeft = HACCGPM::parallel::get_local_index(idx,overload,local_grid_size.y,local_grid_size.z);
    idx3dLeft.y += overload;
    idx3dLeft.z += overload;
    int3 idx3dRight = make_int3((local_grid_size.x - idx3dLeft.x) - 1,idx3dLeft.y,idx3dLeft.z);
    idx3dLeft.x += overload;
    idx3dRight.x += overload;
    //LEFT
    //idx3dLeft is in the local coordinates of the original rank
    //so offset it by overload (now should be negative)
    //transform into our local coordinates
    idx3dLeft.x -= 2*overload;
    idx3dLeft.x += local_grid_size.x + overload + overload;
    int idxLeft = idx3dLeft.x * ol_grid_size.y * ol_grid_size.z + idx3dLeft.y * ol_grid_size.z + idx3dLeft.z;
    float4 left = __ldg(&d_left[idx]);
    d_out[idxLeft] = left;
    //RIGHT
    //idx3dRight is in the local coordinates of the original rank
    //idx3dRight.x -= local_grid_size.x;
    idx3dRight.x += 2*overload;
    idx3dRight.x -= ol_grid_size.x;
    int idxRight = idx3dRight.x * ol_grid_size.y * ol_grid_size.z + idx3dRight.y * ol_grid_size.z + idx3dRight.z;
    float4 right = __ldg(&d_right[idx]);
    d_out[idxRight] = right;
}
References do_return(), and HACCGPM::parallel::get_local_index().
Referenced by XReturn::store().
storeYReturnKernel()
__global__ void storeYReturnKernel (const float4 *__restrict d_left, const float4 *__restrict d_right, float4 *__restrict d_out, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
Definition at line 184 of file gridreturnkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if(idx >= n)return;
    int3 idx3dLeft = HACCGPM::parallel::get_local_index(idx,ol_grid_size.x,overload,local_grid_size.z);
    //idx3dLeft.y += overload;
    idx3dLeft.z += overload;
    int3 idx3dRight = make_int3(idx3dLeft.x,(local_grid_size.y - idx3dLeft.y) - 1,idx3dLeft.z);
    idx3dLeft.y += overload;
    idx3dRight.y += overload;
    //LEFT
    //idx3dLeft is in the local coordinates of the original rank
    //so offset it by overload (now should be negative)
    //transform into our local coordinates
    idx3dLeft.y -= 2*overload;
    idx3dLeft.y += local_grid_size.y + overload + overload;
    int idxLeft = idx3dLeft.x * ol_grid_size.y * ol_grid_size.z + idx3dLeft.y * ol_grid_size.z + idx3dLeft.z;
    float4 left = __ldg(&d_left[idx]);
    d_out[idxLeft] = left;
    //RIGHT
    //idx3dRight is in the local coordinates of the original rank
    //idx3dRight.x -= local_grid_size.x;
    idx3dRight.y += 2*overload;
    idx3dRight.y -= ol_grid_size.y;
    int idxRight = idx3dRight.x * ol_grid_size.y * ol_grid_size.z + idx3dRight.y * ol_grid_size.z + idx3dRight.z;
    float4 right = __ldg(&d_right[idx]);
    d_out[idxRight] = right;
    /*int3 idx3dRight = HACCGPM::parallel::get_local_index(idx,ol_grid_size.x,overload,local_grid_size.z);
    idx3dRight.z += overload;
    int3 idx3dLeft = make_int3(idx3dRight.x,idx3dRight.y + overload + local_grid_size.y,idx3dRight.z);
    int idxRight = idx3dRight.x * ol_grid_size.y * ol_grid_size.z + idx3dRight.y * ol_grid_size.z + idx3dRight.z;
    int idxLeft = idx3dLeft.x * ol_grid_size.y * ol_grid_size.z + idx3dLeft.y * ol_grid_size.z + idx3dLeft.z;
    float4 left = __ldg(&d_left[idx]);
    float4 right = __ldg(&d_right[idx]);
    d_out[idxRight] = right;
    d_out[idxLeft] = left;*/
}
References do_return(), and HACCGPM::parallel::get_local_index().
Referenced by YReturn::store().
storeZReturnKernel()
__global__ void storeZReturnKernel (const float4 *__restrict d_left, const float4 *__restrict d_right, float4 *__restrict d_out, int3 local_grid_size, int3 ol_grid_size, int overload, int n)
Definition at line 320 of file gridreturnkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if(idx >= n)return;
    int3 idx3dLeft = HACCGPM::parallel::get_local_index(idx,ol_grid_size.x,ol_grid_size.x,overload);
    //idx3dLeft.y += overload;
    //idx3dLeft.z += overload;
    int3 idx3dRight = make_int3(idx3dLeft.x,idx3dLeft.y,(local_grid_size.z - idx3dLeft.z) - 1);
    idx3dLeft.z += overload;
    idx3dRight.z += overload;
    //LEFT
    //idx3dLeft is in the local coordinates of the original rank
    //so offset it by overload (now should be negative)
    //transform into our local coordinates
    idx3dLeft.z -= 2*overload;
    idx3dLeft.z += local_grid_size.z + overload + overload;
    int idxLeft = idx3dLeft.x * ol_grid_size.y * ol_grid_size.z + idx3dLeft.y * ol_grid_size.z + idx3dLeft.z;
    float4 left = __ldg(&d_left[idx]);
    d_out[idxLeft] = left;
    //RIGHT
    //idx3dRight is in the local coordinates of the original rank
    //idx3dRight.x -= local_grid_size.x;
    idx3dRight.z += 2*overload;
    idx3dRight.z -= ol_grid_size.z;
    int idxRight = idx3dRight.x * ol_grid_size.y * ol_grid_size.z + idx3dRight.y * ol_grid_size.z + idx3dRight.z;
    float4 right = __ldg(&d_right[idx]);
    d_out[idxRight] = right;
    /*int3 idx3dRight = HACCGPM::parallel::get_local_index(idx,ol_grid_size.x,ol_grid_size.y,overload);
    //idx3dRight.z += overload;
    int3 idx3dLeft = make_int3(idx3dRight.x,idx3dRight.y,idx3dRight.z + overload + local_grid_size.z);
    int idxRight = idx3dRight.x * ol_grid_size.y * ol_grid_size.z + idx3dRight.y * ol_grid_size.z + idx3dRight.z;
    int idxLeft = idx3dLeft.x * ol_grid_size.y * ol_grid_size.z + idx3dLeft.y * ol_grid_size.z + idx3dLeft.z;
    float4 left = __ldg(&d_left[idx]);
    float4 right = __ldg(&d_right[idx]);
    d_out[idxRight] = right;
    d_out[idxLeft] = left;*/
}
References do_return(), and HACCGPM::parallel::get_local_index().
Referenced by ZReturn::store().