HACC_GPM: /home/hqureshi/HACC_GPM/src/grid_exchange/gridexchangekernels.hpp File Reference
gridexchangekernels.hpp File Reference
Classes
class XReturn
class YReturn
class ZReturn
Functions
CPUTimer_t loadXLeft (float *h_out, float *d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t storeXLeft (float *d_out, float *h_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t loadXRight (float *h_out, float *d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t storeXRight (float *d_out, float *h_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t loadYLeft (float *h_out, float *d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t storeYLeft (float *h_out, float *d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t loadYRight (float *h_out, float *d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t storeYRight (float *h_out, float *d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t loadZLeft (float *h_out, float *d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t storeZLeft (float *h_out, float *d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t loadZRight (float *h_out, float *d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t storeZRight (float *h_out, float *d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Function Documentation
loadXLeft()
CPUTimer_t loadXLeft (float * h_out, float * d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 27 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sLoading X Left Buffer\n",indent);
    #endif
    int n = size;//ol_grid_size.x * ol_grid_size.y * ol_grid_size.z;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_out; cudaCall(cudaMalloc,&d_out,sizeof(float)*size);
    gpu_time = InvokeGPUKernelParallel(loadXLeftKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaMemcpy, h_out, d_out, sizeof(float)*size, cudaMemcpyDeviceToHost);
    cudaCall(cudaFree,d_out);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, loadXLeftKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
loadXRight()
CPUTimer_t loadXRight (float * h_out, float * d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 115 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sLoading X Right Buffer\n",indent);
    #endif
    int n = size;//ol_grid_size.x * ol_grid_size.y * ol_grid_size.z;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_out; cudaCall(cudaMalloc,&d_out,sizeof(float)*size);
    gpu_time = InvokeGPUKernelParallel(loadXRightKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaMemcpy, h_out, d_out, sizeof(float)*size, cudaMemcpyDeviceToHost);
    cudaCall(cudaFree,d_out);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, loadXRightKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
loadYLeft()
CPUTimer_t loadYLeft (float * h_out, float * d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 207 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sLoading Y Left Buffer\n",indent);
    #endif
    int n = size;//ol_grid_size.x * ol_grid_size.y * ol_grid_size.z;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_out; cudaCall(cudaMalloc,&d_out,sizeof(float)*size);
    gpu_time = InvokeGPUKernelParallel(loadYLeftKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaMemcpy, h_out, d_out, sizeof(float)*size, cudaMemcpyDeviceToHost);
    cudaCall(cudaFree,d_out);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, loadYLeftKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
loadYRight()
CPUTimer_t loadYRight (float * h_out, float * d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 297 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sLoading Y Right Buffer\n",indent);
    #endif
    int n = size;//ol_grid_size.x * ol_grid_size.y * ol_grid_size.z;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_out; cudaCall(cudaMalloc,&d_out,sizeof(float)*size);
    gpu_time = InvokeGPUKernelParallel(loadYRightKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaMemcpy, h_out, d_out, sizeof(float)*size, cudaMemcpyDeviceToHost);
    cudaCall(cudaFree,d_out);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, loadYRightKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
loadZLeft()
CPUTimer_t loadZLeft (float * h_out, float * d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 392 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sLoading Z Left Buffer\n",indent);
    #endif
    int n = size;//ol_grid_size.x * ol_grid_size.y * ol_grid_size.z;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_out; cudaCall(cudaMalloc,&d_out,sizeof(float)*size);
    gpu_time = InvokeGPUKernelParallel(loadZLeftKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaMemcpy, h_out, d_out, sizeof(float)*size, cudaMemcpyDeviceToHost);
    cudaCall(cudaFree,d_out);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, loadZLeftKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
loadZRight()
CPUTimer_t loadZRight (float * h_out, float * d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 482 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sLoading Z Right Buffer\n",indent);
    #endif
    int n = size;//ol_grid_size.x * ol_grid_size.y * ol_grid_size.z;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_out; cudaCall(cudaMalloc,&d_out,sizeof(float)*size);
    gpu_time = InvokeGPUKernelParallel(loadZRightKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaMemcpy, h_out, d_out, sizeof(float)*size, cudaMemcpyDeviceToHost);
    cudaCall(cudaFree,d_out);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, loadZRightKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
storeXLeft()
CPUTimer_t storeXLeft (float * d_out, float * h_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 66 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sStoring X Left Buffer\n",indent);
    #endif
    int n = size;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_in; cudaCall(cudaMalloc,&d_in,sizeof(float)*size);
    cudaCall(cudaMemcpy, d_in, h_in, sizeof(float)*size, cudaMemcpyHostToDevice);
    gpu_time = InvokeGPUKernelParallel(storeXLeftKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaFree,d_in);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, storeXLeftKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
storeXRight()
CPUTimer_t storeXRight (float * d_out, float * h_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 160 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sStoring X Right Buffer\n",indent);
    #endif
    int n = size;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_in; cudaCall(cudaMalloc,&d_in,sizeof(float)*size);
    cudaCall(cudaMemcpy, d_in, h_in, sizeof(float)*size, cudaMemcpyHostToDevice);
    gpu_time = InvokeGPUKernelParallel(storeXRightKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaFree,d_in);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, storeXRightKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
storeYLeft()
CPUTimer_t storeYLeft (float * h_out, float * d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 248 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sStoring Y Left Buffer\n",indent);
    #endif
    int n = size;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_in; cudaCall(cudaMalloc,&d_in,sizeof(float)*size);
    cudaCall(cudaMemcpy, d_in, h_in, sizeof(float)*size, cudaMemcpyHostToDevice);
    gpu_time = InvokeGPUKernelParallel(storeYLeftKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaFree,d_in);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, storeYLeftKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
storeYRight()
CPUTimer_t storeYRight (float * h_out, float * d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 341 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sStoring Y Right Buffer\n",indent);
    #endif
    int n = size;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_in; cudaCall(cudaMalloc,&d_in,sizeof(float)*size);
    cudaCall(cudaMemcpy, d_in, h_in, sizeof(float)*size, cudaMemcpyHostToDevice);
    gpu_time = InvokeGPUKernelParallel(storeYRightKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaFree,d_in);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, storeYRightKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
storeZLeft()
CPUTimer_t storeZLeft (float * h_out, float * d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 433 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sStoring Z Left Buffer\n",indent);
    #endif
    int n = size;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_in; cudaCall(cudaMalloc,&d_in,sizeof(float)*size);
    cudaCall(cudaMemcpy, d_in, h_in, sizeof(float)*size, cudaMemcpyHostToDevice);
    gpu_time = InvokeGPUKernelParallel(storeZLeftKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaFree,d_in);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, storeZLeftKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().
storeZRight()
CPUTimer_t storeZRight (float * h_out, float * d_in, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 527 of file gridexchangekernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%sStoring Z Right Buffer\n",indent);
    #endif
    int n = size;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    #ifdef VerboseGEKernels
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    #endif
    float* d_in; cudaCall(cudaMalloc,&d_in,sizeof(float)*size);
    cudaCall(cudaMemcpy, d_in, h_in, sizeof(float)*size, cudaMemcpyHostToDevice);
    gpu_time = InvokeGPUKernelParallel(storeZRightKernel,numBlocks,blockSize,d_out,d_in,ol_grid_size,overload,n);
    cudaCall(cudaFree,d_in);
    return gpu_time;
}
References cudaCall, getIndent, InvokeGPUKernelParallel, storeZRightKernel(), and world_rank.
Referenced by HACCGPM::parallel::GridExchange::resolve().