HACC_GPM: /home/hqureshi/HACC_GPM/src/initial_conditions/initializer.cpp File Reference
initializer.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include "ic_kernels.hpp"
#include <math.h>
Functions
void GenerateFourierAmplitudes (HACCGPM::CosmoClass &cosmo, HACCGPM::Params &params, deviceFFT_t *d_grid1, hostFFT_t *d_pkScale, double z, int calls)
void GenerateFourierAmplitudesParallel (HACCGPM::CosmoClass &cosmo, HACCGPM::Params &params, deviceFFT_t *d_grid, hostFFT_t *d_pkScale, double z, int calls)
Function Documentation
GenerateFourierAmplitudes()
void GenerateFourierAmplitudes (HACCGPM::CosmoClass & cosmo, HACCGPM::Params & params, deviceFFT_t * d_grid1, hostFFT_t * d_pkScale, double z, int calls)
Definition at line 10 of file initializer.cpp.
{
    int numBlocks = (params.ng*params.ng*params.ng)/params.blockSize;
    getIndent(calls);
    #ifdef VerboseInitializer
    printf("%sGenerateFourierAmplitudes was called with\n%s   blockSize %d\n%s   numBlocks %d\n%s   z %g\n",indent,indent,params.blockSize,indent,numBlocks,indent,z);
    printf("%s   Calling generate_rng...\n",indent);
    #endif
    launch_generate_rng(d_grid1,params.ng,params.seed,numBlocks,params.blockSize,calls);
    #ifdef VerboseInitializer
    printf("%s      Called generate_rng.\n",indent);
    printf("%s   Doing Forward FFT...\n",indent);
    #endif
    HACCGPM::serial::forward_fft(d_grid1,params.ng,calls+1);
    #ifdef VerboseInitializer
    printf("%s      Done Forward FFT...\n",indent);
    #endif
    #ifdef NOPYTHON
        #ifdef VerboseInitializer
        printf("%s   Getting Pk from ipk...\n",indent);
        #endif
        launch_interpolate_pk(cosmo,d_pkScale,params.ng,params.rl,numBlocks,params.blockSize,calls);
    #else
        #ifdef VerboseInitializer
        printf("%s   Getting Pk from Camb...\n",indent);
        #endif
        launch_get_pk(d_pkScale,z,params.fname,params.ng,params.rl,calls);
        #ifdef VerboseInitializer
        printf("%s      Got Pk from Camb.\n",indent);
        #endif
    #endif
    #ifdef VerboseInitializer
    printf("%s   Scaling Amplitudes...\n",indent);
    #endif
    launch_scale_amplitudes(d_grid1,d_pkScale,params.ng*params.ng*params.ng,numBlocks,params.blockSize,calls);
    #ifdef VerboseInitializer
    printf("%s      Scaled Amplitudes.\n",indent);
    #endif
}
References do_return(), HACCGPM::serial::forward_fft(), getIndent, launch_generate_rng(), launch_get_pk(), launch_interpolate_pk(), and launch_scale_amplitudes().
Referenced by HACCGPM::serial::GenerateDisplacementIC().
GenerateFourierAmplitudesParallel()
void GenerateFourierAmplitudesParallel (HACCGPM::CosmoClass & cosmo, HACCGPM::Params & params, deviceFFT_t * d_grid, hostFFT_t * d_pkScale, double z, int calls)
Definition at line 124 of file initializer.cpp.
{
    int numBlocks = (params.nlocal + (params.blockSize - 1))/params.blockSize;
    int world_rank = params.world_rank;
    getIndent(calls);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%sGenerateFourierAmplitudesParallel was called with\n%s   blockSize %d\n%s   numBlocks %d\n%s   z %g\n",indent,indent,params.blockSize,indent,numBlocks,indent,z);
    if(world_rank == 0)printf("%s   Calling generate_rng...\n",indent);
    #endif
    launch_generate_rng(d_grid,params.ng,params.seed,params.nlocal,params.local_grid_size_vec,params.grid_coords_vec,params.world_rank,numBlocks,params.blockSize,calls);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Called generate_rng.\n",indent);
    if(world_rank == 0)printf("%s   Doing Forward FFT...\n",indent);
    #endif
    HACCGPM::parallel::forward_fft(d_grid,params.ng,calls+1);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Done Forward FFT...\n",indent);
    #endif
    #ifdef NOPYTHON
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s   Getting Pk from ipk...\n",indent);
    #endif
    launch_interpolate_pk(cosmo,d_pkScale,params.ng,params.rl,params.nlocal,params.local_grid_size_vec,params.grid_coords_vec,params.grid_dims_vec,params.world_rank,numBlocks,params.blockSize,calls);
    #else
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s   Getting Pk from Camb...\n",indent);
    #endif
    launch_get_pk(d_pkScale,z,params.fname,params.ng,params.rl,params.nlocal,params.world_rank,calls);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Got Pk from Camb.\n",indent);
    #endif
    #endif
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s   Scaling Amplitudes...\n",indent);
    #endif
    launch_scale_amplitudes(d_grid,d_pkScale,params.nlocal,world_rank,numBlocks,params.blockSize,calls);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Scaled Amplitudes.\n",indent);
    #endif
}
References do_return(), HACCGPM::parallel::forward_fft(), getIndent, launch_generate_rng(), launch_get_pk(), launch_interpolate_pk(), launch_scale_amplitudes(), and world_rank.
Referenced by HACCGPM::parallel::GenerateDisplacementIC().