HACC_GPM: /home/hqureshi/HACC_GPM/src/initial_conditions/ic_kernels.hpp File Reference
ic_kernels.hpp File Reference
#include "haccgpm.hpp"
Functions
void launch_generate_rng (deviceFFT_t *d_grid1, int ng, int seed, int numBlocks, int blockSize, int calls)
void launch_generate_rng (deviceFFT_t *d_grid1, int ng, int seed, int nlocal, int3 local_grid_size, int3 local_coords, int world_rank, int numBlocks, int blockSize, int calls)
void launch_scale_amplitudes (deviceFFT_t *grid, hostFFT_t *scale, int nlocal, int world_rank, int numBlocks, int blockSize, int calls)
void launch_scale_amplitudes (deviceFFT_t *grid, hostFFT_t *scale, int nlocal, int numBlocks, int blockSize, int calls)
void launch_scale_fft (deviceFFT_t *data, double scale, int nlocal, int world_rank, int numBlocks, int blockSize, int calls)
void launch_scale_fft (deviceFFT_t *data, double scale, int nlocal, int numBlocks, int blockSize, int calls)
void launch_interpolate_pk (HACCGPM::CosmoClass &cosmo, hostFFT_t *d_pkScale, int ng, double rl, int numBlocks, int blockSize, int calls)
void launch_interpolate_pk (HACCGPM::CosmoClass &cosmo, hostFFT_t *d_pkScale, int ng, double rl, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int numBlocks, int blockSize, int calls)
void launch_get_pk (hostFFT_t *d_pkScale, double z, const char *fname, int ng, double rl, int calls)
void launch_get_pk (hostFFT_t *d_pkScale, double z, const char *fname, int ng, double rl, int nlocal, int world_rank, int calls)
void launch_transform_density_field (deviceFFT_t *d_grid, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, double delta, double rl, double z_ini, int ng, int numBlocks, int blockSize, int calls)
void launch_transform_density_field (deviceFFT_t *d_grid, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, double delta, double rl, double z_ini, int ng, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int numBlocks, int blockSize, int calls)
void launch_place_particles (float4 *d_pos, float4 *d_vel, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, double delta, double dotDelta, double rl, double z_ini, double deltaT, double fscal, int ng, int numBlocks, int blockSize, int calls)
void launch_place_particles (float4 *d_pos, float4 *d_vel, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, double delta, double dotDelta, double rl, double z_ini, double deltaT, double fscal, int ng, int nlocal, int3 local_grid_size, int world_rank, int numBlocks, int blockSize, int calls)
Function Documentation
launch_generate_rng() [1/2]
void launch_generate_rng (deviceFFT_t * d_grid1, int ng, int seed, int nlocal, int3 local_grid_size, int3 local_coords, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 40 of file rng_initializer.cu.
{
    getIndent(calls);
    curandState* rngState; cudaCall(cudaMalloc,&rngState,sizeof(curandState)*nlocal);
    InvokeGPUKernelParallel(initRNG,numBlocks,blockSize,rngState,seed,nlocal,ng,local_grid_size,local_coords);
    InvokeGPUKernelParallel(GenerateRealRandom,numBlocks,blockSize,rngState,d_grid1,nlocal);
    cudaCall(cudaFree,rngState);
}
References cudaCall, do_return(), GenerateRealRandom(), getIndent, initRNG(), and InvokeGPUKernelParallel.
launch_generate_rng() [2/2]
void launch_generate_rng (deviceFFT_t * d_grid1, int ng, int seed, int numBlocks, int blockSize, int calls)
Definition at line 32 of file rng_initializer.cu.
{
    getIndent(calls);
    curandState* rngState; cudaCall(cudaMalloc,&rngState,sizeof(curandState)*ng*ng*ng);
    InvokeGPUKernel(initRNG,numBlocks,blockSize,rngState,seed);
    InvokeGPUKernel(GenerateRealRandom,numBlocks,blockSize,rngState,d_grid1,ng*ng*ng);
    cudaCall(cudaFree,rngState);
}
References cudaCall, do_return(), GenerateRealRandom(), getIndent, initRNG(), and InvokeGPUKernel.
Referenced by GenerateFourierAmplitudes(), and GenerateFourierAmplitudesParallel().
launch_get_pk() [1/2]
void launch_get_pk (hostFFT_t * d_pkScale, double z, const char * fname, int ng, double rl, int calls)
Definition at line 7 of file read_camb.cu.
{
    hostFFT_t* h_tmp = (hostFFT_t*)malloc(sizeof(hostFFT_t)*ng*ng*ng);
    get_pk(fname,h_tmp,z,ng,rl,calls+1);
    cudaCall(cudaMemcpy, d_pkScale, h_tmp, sizeof(hostFFT_t)*ng*ng*ng, cudaMemcpyHostToDevice);
    free(h_tmp);
}
References cudaCall, do_return(), get_pk(), and hostFFT_t.
Referenced by GenerateFourierAmplitudes(), and GenerateFourierAmplitudesParallel().
launch_get_pk() [2/2]
void launch_get_pk (hostFFT_t * d_pkScale, double z, const char * fname, int ng, double rl, int nlocal, int world_rank, int calls)
Definition at line 19 of file read_camb.cu.
{
    hostFFT_t* h_tmp = (hostFFT_t*)malloc(sizeof(hostFFT_t)*nlocal);
    get_pk_parallel(fname,h_tmp,z,ng,rl,nlocal,world_rank,calls+1);
    cudaCall(cudaMemcpy, d_pkScale, h_tmp, sizeof(hostFFT_t)*nlocal, cudaMemcpyHostToDevice);
    free(h_tmp);
}
References cudaCall, do_return(), get_pk_parallel(), hostFFT_t, and world_rank.
launch_interpolate_pk() [1/2]
void launch_interpolate_pk (HACCGPM::CosmoClass & cosmo, hostFFT_t * d_pkScale, int ng, double rl, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 78 of file interpolation_initializer.cu.
{
    getIndent(calls);
    double* h_ipk;
    int ipk_bins;
    double ipk_delta;
    double ipk_max;
    double ipk_min;
    cosmo.read_ipk(&h_ipk,&ipk_bins,&ipk_delta,&ipk_max,&ipk_min,calls+1);
    double* d_ipk; cudaCall(cudaMalloc,&d_ipk,sizeof(double)*ipk_bins);
    cudaCall(cudaMemcpy, d_ipk, h_ipk, sizeof(double)*ipk_bins, cudaMemcpyHostToDevice);
    double maxK = ((ng/2)*2*M_PI)/rl;
    maxK = sqrt(maxK*maxK*maxK);
    if(world_rank == 0)printf("%s      maxK = %g\n",indent,maxK);
    if (maxK > ipk_max){
        if(world_rank == 0)printf("%s      input ipk only goes to %g\n",indent,ipk_max);
        exit(1);
    }
    InvokeGPUKernelParallel(interpolatePowerSpectrum,numBlocks,blockSize,d_pkScale,d_ipk,ipk_bins,ipk_delta,ipk_min,rl,ng,nlocal,world_rank,local_grid_size,local_coords,dims);
    free(h_ipk);
    cudaCall(cudaFree,d_ipk);
}
References cudaCall, do_return(), getIndent, interpolatePowerSpectrum(), InvokeGPUKernelParallel, and world_rank.
launch_interpolate_pk() [2/2]
void launch_interpolate_pk (HACCGPM::CosmoClass & cosmo, hostFFT_t * d_pkScale, int ng, double rl, int numBlocks, int blockSize, int calls)
Definition at line 52 of file interpolation_initializer.cu.
{
    getIndent(calls);
    double* h_ipk;
    int ipk_bins;
    double ipk_delta;
    double ipk_max;
    double ipk_min;
    cosmo.read_ipk(&h_ipk,&ipk_bins,&ipk_delta,&ipk_max,&ipk_min,calls+1);
    double* d_ipk; cudaCall(cudaMalloc,&d_ipk,sizeof(double)*ipk_bins);
    cudaCall(cudaMemcpy, d_ipk, h_ipk, sizeof(double)*ipk_bins, cudaMemcpyHostToDevice);
    double maxK = ((ng/2)*2*M_PI)/rl;
    maxK = sqrt(maxK*maxK*maxK);
    printf("%s      maxK = %g\n",indent,maxK);
    if (maxK > ipk_max){
        printf("%s      input ipk only goes to %g\n",indent,ipk_max);
        exit(1);
    }
    InvokeGPUKernel(interpolatePowerSpectrum,numBlocks,blockSize,d_pkScale,d_ipk,ipk_bins,ipk_delta,ipk_min,rl,ng);
    free(h_ipk);
    cudaCall(cudaFree,d_ipk);
}
References cudaCall, do_return(), getIndent, interpolatePowerSpectrum(), and InvokeGPUKernel.
Referenced by GenerateFourierAmplitudes(), and GenerateFourierAmplitudesParallel().
launch_place_particles() [1/2]
void launch_place_particles (float4 * d_pos, float4 * d_vel, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, double delta, double dotDelta, double rl, double z_ini, double deltaT, double fscal, int ng, int nlocal, int3 local_grid_size, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 64 of file place_particles_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernelParallel(placeParticles,numBlocks,blockSize,d_pos,d_vel,d_x,d_y,d_z,delta,dotDelta,rl,1/(1+z_ini),deltaT,fscal,ng,local_grid_size.x,local_grid_size.y,local_grid_size.z, nlocal, world_rank);
}
References do_return(), getIndent, InvokeGPUKernelParallel, placeParticles(), and world_rank.
launch_place_particles() [2/2]
void launch_place_particles (float4 * d_pos, float4 * d_vel, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, double delta, double dotDelta, double rl, double z_ini, double deltaT, double fscal, int ng, int numBlocks, int blockSize, int calls)
Definition at line 59 of file place_particles_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernel(placeParticles,numBlocks,blockSize,d_pos,d_vel,d_x,d_y,d_z,delta,dotDelta,rl,1/(1+z_ini),deltaT,fscal,ng);
}
References do_return(), getIndent, InvokeGPUKernel, and placeParticles().
Referenced by HACCGPM::parallel::GenerateDisplacementIC(), and HACCGPM::serial::GenerateDisplacementIC().
launch_scale_amplitudes() [1/2]
void launch_scale_amplitudes (deviceFFT_t * grid, hostFFT_t * scale, int nlocal, int numBlocks, int blockSize, int calls)
Definition at line 19 of file scale_initializer.cu.
{
    launch_scale_amplitudes(grid,scale,nlocal,0,numBlocks,blockSize,calls);
}
References do_return(), and launch_scale_amplitudes().
launch_scale_amplitudes() [2/2]
void launch_scale_amplitudes (deviceFFT_t * grid, hostFFT_t * scale, int nlocal, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 14 of file scale_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernelParallel(ScaleAmplitudes,numBlocks,blockSize,grid,scale,nlocal);
}
References do_return(), getIndent, InvokeGPUKernelParallel, and ScaleAmplitudes().
Referenced by GenerateFourierAmplitudes(), GenerateFourierAmplitudesParallel(), and launch_scale_amplitudes().
launch_scale_fft() [1/2]
void launch_scale_fft (deviceFFT_t * data, double scale, int nlocal, int numBlocks, int blockSize, int calls)
Definition at line 42 of file scale_initializer.cu.
{
    launch_scale_fft(data,scale,nlocal,0,numBlocks,blockSize,calls);
}
References do_return(), and launch_scale_fft().
launch_scale_fft() [2/2]
void launch_scale_fft (deviceFFT_t * data, double scale, int nlocal, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 37 of file scale_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernelParallel(ScaleFFT,numBlocks,blockSize,data,scale,nlocal);
}
References do_return(), getIndent, InvokeGPUKernelParallel, and ScaleFFT().
Referenced by HACCGPM::parallel::GenerateDisplacementIC(), HACCGPM::serial::GenerateDisplacementIC(), and launch_scale_fft().
launch_transform_density_field() [1/2]
void launch_transform_density_field (deviceFFT_t * d_grid, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, double delta, double rl, double z_ini, int ng, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 88 of file transform_density_field_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernelParallel(transformDensityField,numBlocks,blockSize,d_grid,d_x,d_y,d_z,delta,rl,1/(1+z_ini),ng,nlocal,world_rank,local_grid_size,local_coords,dims);
}
References do_return(), getIndent, InvokeGPUKernelParallel, transformDensityField(), and world_rank.
launch_transform_density_field() [2/2]
void launch_transform_density_field (deviceFFT_t * d_grid, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, double delta, double rl, double z_ini, int ng, int numBlocks, int blockSize, int calls)
Definition at line 83 of file transform_density_field_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernel(transformDensityField,numBlocks,blockSize,d_grid,d_x,d_y,d_z,delta,rl,1/(1+z_ini),ng);
}
References do_return(), getIndent, InvokeGPUKernel, and transformDensityField().
Referenced by HACCGPM::parallel::GenerateDisplacementIC(), and HACCGPM::serial::GenerateDisplacementIC().