HACC: HACCGPM::Timestepper Class Reference
HACCGPM::Timestepper Class Reference
#include <haccgpm.hpp>
Public Member Functions
Timestepper (Params iparams)
void setInitialA (double a)
void setInitialZ (double z)
void advanceHalfStep ()
void reverseHalfStep ()
Public Attributes
Params params
double aa
double z
double deltaT
double adot
double fscal
int world_rank
Detailed Description
Definition at line 99 of file haccgpm.hpp.
Constructor & Destructor Documentation
Timestepper()
HACCGPM::Timestepper::Timestepper (HACCGPM::Params iparams)
Definition at line 29 of file timestepper.cu.
{
    world_rank = iparams.world_rank;
    deltaT = (((1/(iparams.z_fin + 1)) - (1/(iparams.z_ini + 1))) / (double)iparams.nsteps);
    params = iparams;
}
References deltaT, HACCGPM::Params::nsteps, params, HACCGPM::Params::world_rank, world_rank, HACCGPM::Params::z_fin, and HACCGPM::Params::z_ini.
Member Function Documentation
advanceHalfStep()
void HACCGPM::Timestepper::advanceHalfStep ()
Definition at line 50 of file timestepper.cu.
{
    aa += deltaT * 0.5;
    z = (1.0f/aa) - 1;
    adot = HACCGPM::serial::get_adot(aa,params.m_w_de,params.m_wa_de,params.m_omega_cb,params.m_omega_radiation,params.m_f_nu_massless,params.m_f_nu_massive,params.m_omega_matter,params.m_omega_nu);
    fscal = HACCGPM::serial::get_fscal(aa,adot,params.m_omega_cb);
    if(world_rank == 0)printf("Timestepper: a=%g, z=%g, adot=%g, fscal=%g\n",aa,z,adot,fscal);
}
References HACCGPM::serial::get_adot(), HACCGPM::serial::get_fscal(), and world_rank.
Referenced by serial().
reverseHalfStep()
void HACCGPM::Timestepper::reverseHalfStep ()
Definition at line 58 of file timestepper.cu.
{
    aa -= deltaT * 0.5;
    z = (1.0f/aa) - 1;
    adot = HACCGPM::serial::get_adot(aa,params.m_w_de,params.m_wa_de,params.m_omega_cb,params.m_omega_radiation,params.m_f_nu_massless,params.m_f_nu_massive,params.m_omega_matter,params.m_omega_nu);
    fscal = HACCGPM::serial::get_fscal(aa,adot,params.m_omega_cb);
}
References HACCGPM::serial::get_adot(), and HACCGPM::serial::get_fscal().
Referenced by parallel(), and serial().
setInitialA()
void HACCGPM::Timestepper::setInitialA (double a)
Definition at line 35 of file timestepper.cu.
{
    aa = a;
    z = (1.0f/aa) - 1;
    adot = HACCGPM::serial::get_adot(aa,params.m_w_de,params.m_wa_de,params.m_omega_cb,params.m_omega_radiation,params.m_f_nu_massless,params.m_f_nu_massive,params.m_omega_matter,params.m_omega_nu);
    fscal = HACCGPM::serial::get_fscal(aa,adot,params.m_omega_cb);
}
References HACCGPM::serial::get_adot(), and HACCGPM::serial::get_fscal().
setInitialZ()
void HACCGPM::Timestepper::setInitialZ (double z)
Definition at line 42 of file timestepper.cu.
{
    z = z;
    aa = 1.0/(z+1.0);
    adot = HACCGPM::serial::get_adot(aa,params.m_w_de,params.m_wa_de,params.m_omega_cb,params.m_omega_radiation,params.m_f_nu_massless,params.m_f_nu_massive,params.m_omega_matter,params.m_omega_nu);
    fscal = HACCGPM::serial::get_fscal(aa,adot,params.m_omega_cb);
    if(world_rank == 0)printf("Timestepper: a=%g, z=%g, adot=%g, fscal=%g\n",aa,z,adot,fscal);
}
References HACCGPM::serial::get_adot(), HACCGPM::serial::get_fscal(), and world_rank.
Referenced by parallel(), and serial().
Member Data Documentation
aa
double HACCGPM::Timestepper::aa
Definition at line 102 of file haccgpm.hpp.
Referenced by serial(), and HACCGPM::serial::UpdatePositions().
adot
double HACCGPM::Timestepper::adot
Definition at line 105 of file haccgpm.hpp.
Referenced by HACCGPM::serial::UpdatePositions().
deltaT
double HACCGPM::Timestepper::deltaT
Definition at line 104 of file haccgpm.hpp.
Referenced by parallel(), serial(), Timestepper(), HACCGPM::serial::UpdatePositions(), and HACCGPM::serial::UpdateVelocities().
fscal
double HACCGPM::Timestepper::fscal
Definition at line 106 of file haccgpm.hpp.
Referenced by parallel(), serial(), and HACCGPM::serial::UpdateVelocities().
params
Params HACCGPM::Timestepper::params
Definition at line 101 of file haccgpm.hpp.
Referenced by Timestepper().
world_rank
int HACCGPM::Timestepper::world_rank
Definition at line 107 of file haccgpm.hpp.
Referenced by Timestepper().
z
double HACCGPM::Timestepper::z
Definition at line 103 of file haccgpm.hpp.
Referenced by serial().
The documentation for this class was generated from the following files:
/home/hqureshi/HACC_GPM/haccgpm.hpp
/home/hqureshi/HACC_GPM/timestepper.cu