HACC_GPM: /home/hqureshi/HACC_GPM/src/power_spectrum/cuda/scale_power.cu File Reference
scale_power.cu File Reference
#include "power_kernels.hpp"
Functions
__global__ void scalePower (deviceFFT_t *__restrict data, double ng, double rl, int nlocal)
Function Documentation
scalePower()
__global__ void scalePower (deviceFFT_t *__restrict data, double ng, double rl, int nlocal)
Definition at line 3 of file scale_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    double scale = (1.0f/(ng*ng*ng)) * (rl/ng);
    deviceFFT_t old = __ldg(&data[idx]);
    old.x = (old.x * old.x + old.y * old.y) * scale;
    data[idx] = old;
}
References deviceFFT_t, and do_return().
Referenced by HACCGPM::parallel::GetPowerSpectrum(), and HACCGPM::serial::GetPowerSpectrum().