HACC_GPM: HACCGPM::parallel Namespace Reference
HACCGPM::parallel Namespace Reference
Classes
class GridExchange
class MemoryManager
Functions
__device__ __forceinline__ int3 get_local_index (int idx, int nx, int ny, int nz)
__device__ __forceinline__ int3 get_global_index (int idx, int ng, int3 local_dims, int3 local_coords)
void init_swfft (HACCGPM::Params &params)
void finalize_swfft ()
void forward_fft (deviceFFT_t *d_grid, int ng, int calls=0)
void backward_fft (deviceFFT_t *d_grid, int ng, int calls=0)
void timing_stats (CPUTimer_t t, CPUTimer_t *mint, CPUTimer_t *maxt, CPUTimer_t *meant)
void printTimingStats (const char *preamble, double dt)
CPUTimer_t LoadIntoBuffers (float4 *h_swap, int *n_swaps, int *h_starts, float4 *d_pos, float4 *d_vel, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int n_particles, int ng, int blockSize, int world_rank, int world_size, int calls=0)
void TransferParticles (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, int calls=0)
CPUTimer_t insertParticles (float4 *d_pos, float4 *d_vel, float4 *h_swap, int n_new, int n_particles, int blockSize, int world_rank, int calls=0)
void GenerateDisplacementIC (HACCGPM::parallel::MemoryManager &mem, HACCGPM::CosmoClass &cosmo, HACCGPM::Params &params, HACCGPM::Timestepper &ts, int calls=0)
void CIC (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, int calls=0)
void CIC (deviceFFT_t *d_grid, float *d_extragrid, float4 *d_pos, int ng, int n_particles, int3 local_grid_size, int3 local_coords, int3 dims, int blockSize, int world_rank, int world_size, int overload, int calls=0)
void GetPowerSpectrum (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, int nbins, const char *fname, int calls=0)
void sendPower (int *binCounts, double *binVals, int nbins, int world_rank, int world_size, int calls=0)
void InitGreens (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, int calls=0)
void UpdatePositions (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, HACCGPM::Timestepper ts, float frac, int calls=0)
int UpdatePositions (float4 *d_pos, float4 *d_vel, HACCGPM::Timestepper ts, float frac, int ng, int n_particles, int3 local_grid_size, int overload, int blockSize, int world_rank, int calls=0)
void UpdateVelocities (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, HACCGPM::Timestepper ts, int calls=0)
void UpdateVelocities (float4 *d_vel, float4 *d_grad, float4 *d_pos, HACCGPM::Timestepper ts, int n_particles, int ng, int overload, int3 local_grid_size, int blockSize, int world_rank, int calls=0)
void SolveGradient (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, int calls=0)
void SolveGradient (float4 *d_grad, deviceFFT_t *d_rho, hostFFT_t *d_greens, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, int ng, int n_particles, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int world_size, int overload, int blockSize, int calls=0)
void printTransferTimes (int world_rank)
void printCICTimes (int world_rank)
void printTransferBytes (int world_rank)
void printFFTStats (int world_rank)
void printGridExchangeTimes (int world_rank)
void printGridExchangeBytes (int world_rank)
Function Documentation
backward_fft()
void HACCGPM::parallel::backward_fft (deviceFFT_t * d_grid, int ng, int calls = 0)
Definition at line 82 of file swfftmanager.cpp.
{
    getIndent(calls);
    #ifdef VerboseFFT
    if(ffts->dist.world_rank == 0)printf("%sbackward_fft was called with\n%s   ng %d\n",indent,indent,ng);
    #endif
    CPUTimer_t start = CPUTimer();
    ffts->dfft.backward(d_grid);
    CPUTimer_t end = CPUTimer();
    BACKWARD_FFT_CALLS++;
    BACKWARD_FFT_TIME += end-start;
    #ifdef VerboseFFT
    if(ffts->dist.world_rank == 0)printf("%s   backward_fft took %llu us\n",indent,end - start);
    #endif
}
References BACKWARD_FFT_CALLS, BACKWARD_FFT_TIME, CPUTimer(), FFTManager::dfft, FFTManager::dist, ffts, and getIndent.
Referenced by GenerateDisplacementIC(), and SolveGradient().
CIC() [1/2]
void HACCGPM::parallel::CIC (deviceFFT_t * d_grid, float * d_extragrid, float4 * d_pos, int ng, int n_particles, int3 local_grid_size, int3 local_coords, int3 dims, int blockSize, int world_rank, int world_size, int overload, int calls = 0)
Definition at line 24 of file pm_actions.cpp.
{
    CPUTimer_t start = CPUTimer();
    int numBlocks = (n_particles + (blockSize - 1))/blockSize;
    //int3 local_grid_size = make_int3(local_grid_size_[0],local_grid_size_[1],local_grid_size_[2]);
    //int3 local_coords = make_int3(local_coords_[0],local_coords_[1],local_coords_[2]);
    //int3 dims = make_int3(dims_[0],dims_[1],dims_[2]);
    getIndent(calls);
    #ifdef VerboseUpdate
    if (world_rank == 0)printf("%sCIC was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,blockSize,indent,numBlocks);
    #endif
    //cudaCall(cudaMemset,d_tempgrid,0,sizeof(float)*(local_grid_size.x + 2*overload)*(local_grid_size.y + 2*overload)*(local_grid_size.z + 2*overload));
    //CIC_KERNEL_TIME += InvokeGPUKernelParallel(CICKernelParallel,numBlocks,blockSize,d_tempgrid,d_pos,ng,overload,local_grid_size,n_particles,1.0f);
    CIC_KERNEL_TIME += launch_cic(d_tempgrid,d_pos,ng,overload,local_grid_size,n_particles,1.0f,world_rank,numBlocks,blockSize,calls);
    HACCGPM::parallel::GridExchange gexch(local_coords,local_grid_size,dims,ng,world_size,world_rank,overload,blockSize);
    gexch.resolve(d_tempgrid,calls+1);
    numBlocks = ((local_grid_size.x + 2*overload)*(local_grid_size.y + 2*overload)*(local_grid_size.z + 2*overload) + (blockSize - 1))/blockSize;
    //InvokeGPUKernelParallel(float2complex,numBlocks,blockSize,d_grid,d_tempgrid,local_grid_size,overload);
    CIC_KERNEL_TIME += launch_f2c(d_grid,d_tempgrid,local_grid_size,overload,world_rank,numBlocks,blockSize,calls);
    //deviceFFT_t* h_tempgrid = (deviceFFT_t*)malloc(sizeof(deviceFFT_t)*(local_grid_size.x)*(local_grid_size.y)*(local_grid_size.z));
    //cudaCall(cudaMemcpy, h_tempgrid, d_grid, sizeof(deviceFFT_t)*(local_grid_size.x)*(local_grid_size.y)*(local_grid_size.z), cudaMemcpyDeviceToHost);
    //free(h_tempgrid);
    CPUTimer_t end = CPUTimer();
    CPUTimer_t t = end-start;
    #ifdef VerboseUpdate
    if (world_rank == 0)printf("%s   CIC took %llu us\n",indent,t);
    #else
    HACCGPM::parallel::printTimingStats("PMAC cicpm",((double)t) * 1e-6);
    #endif
    CIC_TIME += t;
    CIC_CALLS += 1;
}
References CIC_CALLS, CIC_KERNEL_TIME, CIC_TIME, CPUTimer(), do_return(), getIndent, launch_cic(), launch_f2c(), printTimingStats(), and world_rank.
CIC() [2/2]
void HACCGPM::parallel::CIC (HACCGPM::Params & params, HACCGPM::parallel::MemoryManager & mem, int calls = 0)
Definition at line 20 of file pm_actions.cpp.
{
    HACCGPM::parallel::CIC(mem.d_grid,mem.d_tempgrid,mem.d_pos,params.ng,params.n_particles,params.local_grid_size_vec,params.grid_coords_vec,params.grid_dims_vec,params.blockSize,params.world_rank,params.world_size,params.overload,calls);
}
References CIC(), and do_return().
Referenced by CIC(), GetPowerSpectrum(), and parallel().
finalize_swfft()
void HACCGPM::parallel::finalize_swfft ()
Definition at line 63 of file swfftmanager.cpp.
{
    delete ffts;
}
References ffts.
Referenced by parallel().
forward_fft()
void HACCGPM::parallel::forward_fft (deviceFFT_t * d_grid, int ng, int calls = 0)
Definition at line 67 of file swfftmanager.cpp.
{
    getIndent(calls);
    #ifdef VerboseFFT
    if(ffts->dist.world_rank == 0)printf("%sforward_fft was called with\n%s   ng %d\n",indent,indent,ng);
    #endif
    CPUTimer_t start = CPUTimer();
    ffts->dfft.forward(d_grid);
    CPUTimer_t end = CPUTimer();
    FORWARD_FFT_CALLS++;
    FORWARD_FFT_TIME += end-start;
    #ifdef VerboseFFT
    if(ffts->dist.world_rank == 0)printf("%s   forward_fft took %llu us\n",indent,end - start);
    #endif
}
References CPUTimer(), FFTManager::dfft, FFTManager::dist, ffts, FORWARD_FFT_CALLS, FORWARD_FFT_TIME, and getIndent.
Referenced by GenerateFourierAmplitudesParallel(), GetPowerSpectrum(), and SolveGradient().
GenerateDisplacementIC()
void HACCGPM::parallel::GenerateDisplacementIC (HACCGPM::parallel::MemoryManager & mem, HACCGPM::CosmoClass & cosmo, HACCGPM::Params & params, HACCGPM::Timestepper & ts, int calls = 0)
Definition at line 176 of file initializer.cpp.
{
    int world_rank = params.world_rank;
    int numBlocks = (params.nlocal)/params.blockSize;
    getIndent(calls);
    #ifdef VerboseInitializer
    if (params.world_rank == 0)printf("%sGenerateDisplacementIC was called with\n%s   blockSize %d\n%s   numBlocks %d\n%s   params %s\n",indent,indent,params.blockSize,indent,numBlocks,indent,params.fname);
    if (params.world_rank == 0)printf("%s   Calling GenerateFourierAmplitudesParallel...\n",indent);
    #endif
    GenerateFourierAmplitudesParallel(cosmo, params, mem.d_grid, mem.d_greens, params.z_ini, calls+1);
    #ifdef VerboseInitializer
    if (params.world_rank == 0)printf("%s      Called GenerateFourierAmplitudes.\n",indent);
    if (params.world_rank == 0)printf("%s   Calling get_delta_and_dotDelta...\n",indent);
    #endif
    double delta;
    double dotDelta;
    double this_a = (1/(params.z_ini + 1)) - (ts.deltaT/2.0f);
    double velZ = (1.0f/this_a) - 1.0f;
    cosmo.get_delta_and_dotDelta(params.z_ini,velZ,&delta,&dotDelta);
    if (params.world_rank == 0)printf("%s      Delta %g, dotDelta %g\n",indent,delta,dotDelta);
    #ifdef VerboseInitializer
    if (params.world_rank == 0)printf("%s      Called get_delta_and_dotDelta.\n",indent);
    if (params.world_rank == 0)printf("%s   Calling transformDensityField...\n",indent);
    #endif
    launch_transform_density_field(mem.d_grid,mem.d_x,mem.d_y,mem.d_z,delta,params.rl,params.z_ini,params.ng,params.nlocal,params.local_grid_size_vec,params.grid_coords_vec,params.grid_dims_vec,params.world_rank,numBlocks,params.blockSize,calls);
    #ifdef VerboseInitializer
    if (params.world_rank == 0)printf("%s      Called transformVelocityField.\n",indent);
    if (params.world_rank == 0)printf("%s   Doing Backward FFTs...\n",indent);
    #endif
    HACCGPM::parallel::backward_fft(mem.d_x,params.ng,calls+1);
    HACCGPM::parallel::backward_fft(mem.d_y,params.ng,calls+1);
    HACCGPM::parallel::backward_fft(mem.d_z,params.ng,calls+1);
    double scale_by = 1.0f/((double)(params.ng*params.ng*params.ng));
    launch_scale_fft(mem.d_x,scale_by,params.nlocal,params.world_rank,numBlocks,params.blockSize,calls);
    launch_scale_fft(mem.d_y,scale_by,params.nlocal,params.world_rank,numBlocks,params.blockSize,calls);
    launch_scale_fft(mem.d_z,scale_by,params.nlocal,params.world_rank,numBlocks,params.blockSize,calls);
    #ifdef VerboseInitializer
    if (params.world_rank == 0)printf("%s      Done Backward FFTs.\n",indent);
    if (params.world_rank == 0)printf("%s   Calling placeParticles.\n",indent);
    #endif
    launch_place_particles(mem.d_pos,mem.d_vel,mem.d_x,mem.d_y,mem.d_z,delta,dotDelta,params.rl,params.z_ini,ts.deltaT,ts.fscal,params.ng,params.nlocal,params.local_grid_size_vec,params.world_rank,numBlocks,params.blockSize,calls);
    #ifdef VerboseInitializer
    if (params.world_rank == 0)printf("%s      Called placeParticles.\n",indent);
    #endif
}
References backward_fft(), do_return(), GenerateFourierAmplitudesParallel(), getIndent, launch_place_particles(), launch_scale_fft(), launch_transform_density_field(), and world_rank.
Referenced by parallel().
get_global_index()
__device__ __forceinline__ int3 HACCGPM::parallel::get_global_index (int idx, int ng, int3 local_dims, int3 local_coords)
Definition at line 278 of file haccgpm.hpp.
{
            int3 out;
            int3 local = get_local_index(idx,local_dims.x,local_dims.y,local_dims.z);
            out.x = local.x + local_coords.x * local_dims.x;
            out.y = local.y + local_coords.y * local_dims.y;
            out.z = local.z + local_coords.z * local_dims.z;
            return out;
        }
References do_return(), and get_local_index().
Referenced by BinPower(), combine_parallel(), getGreensParallelKernel(), initRNG(), interpolatePowerSpectrum(), kspace_solve_gradient_parallel(), PkCICFilter(), and transformDensityField().
get_local_index()
__device__ __forceinline__ int3 HACCGPM::parallel::get_local_index (int idx, int nx, int ny, int nz)
Definition at line 270 of file haccgpm.hpp.
{
            int3 out;
            out.x = idx/(ny*nz);
            out.y = (idx - (out.x*ny*nz))/nz;
            out.z = (idx - (out.x*ny*nz)) - out.y*nz;
            return out;
        }
References do_return().
Referenced by combine_parallel(), float2complex(), get_global_index(), loadXLeftKernel(), loadXReturnKernel(), loadXRightKernel(), loadYLeftKernel(), loadYReturnKernel(), loadYRightKernel(), loadZLeftKernel(), loadZReturnKernel(), loadZRightKernel(), placeParticles(), storeXLeftKernel(), storeXReturnKernel(), storeXRightKernel(), storeYLeftKernel(), storeYReturnKernel(), storeYRightKernel(), storeZLeftKernel(), storeZReturnKernel(), and storeZRightKernel().
GetPowerSpectrum()
void HACCGPM::parallel::GetPowerSpectrum (HACCGPM::Params & params, HACCGPM::parallel::MemoryManager & mem, int nbins, const char * fname, int calls = 0)
Definition at line 28 of file power.cu.
{
    CPUTimer_t start = CPUTimer();
    int world_rank = params.world_rank;
    int numBlocks = (params.nlocal + (params.blockSize - 1))/params.blockSize;
    getIndent(calls);
    #ifdef VerbosePower
    if(params.world_rank == 0)printf("%sGetPowerSpectrum was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,params.blockSize,indent,numBlocks);
    if(params.world_rank == 0)printf("%s   Allocating kBins, binCounts, binVals, d_binCounts, d_binVals\n",indent);
    #endif
    double* kBins = (double*)malloc(sizeof(double)*nbins);
    int* binCounts = (int*)malloc(sizeof(int)*(nbins));
    double* binVals = (double*)malloc(sizeof(double)*nbins);
    int* d_binCounts; cudaCall(cudaMalloc,&d_binCounts,sizeof(int)*nbins);
    double* d_binVals; cudaCall(cudaMalloc,&d_binVals,sizeof(double)*nbins);
    #ifdef VerbosePower
    if(params.world_rank == 0)printf("%s      Allocated kBins, binCounts, binVals, d_binCounts, d_binVals\n",indent);
    if(params.world_rank == 0)printf("%s   Filling kBins\n",indent);
    #endif
    double new_rl = params.rl;//(params.rl/(pow(2,nfolds)));
    double d = (2*M_PI)/(new_rl);
    double d3 = sqrt(3*d*d);
    double minK = d;
    double maxK = sqrt(3*((params.ng/2)*(params.ng/2)*d*d));
    double binDelta = (maxK - minK)/((double)nbins);
    for (int i = 0; i < nbins; i++){
        kBins[i] = minK + binDelta * (((float)i) + 0.5f);
    }
    new_rl = params.rl;
    d = (2*M_PI)/(new_rl);
    #ifdef VerbosePower
    if(params.world_rank == 0)printf("%s      Filled kBins: minK = %g, maxK = %g, binDelta = %g, nbins = %d\n",indent,minK,maxK,binDelta,nbins);
    if(params.world_rank == 0)printf("%s   Calling CIC\n",indent);
    #endif
    HACCGPM::parallel::CIC(mem.d_grid,mem.d_tempgrid,mem.d_pos,params.ng,params.n_particles,params.local_grid_size_vec,params.grid_coords_vec,params.grid_dims_vec,params.blockSize,params.world_rank, params.world_size,params.overload,calls+1);
    #ifdef VerbosePower
    if(params.world_rank == 0)printf("%s      Called CIC\n",indent);
    if(params.world_rank == 0)printf("%s   Calculating PK\n",indent);
    #endif
    HACCGPM::parallel::forward_fft(mem.d_grid,params.ng,calls+1);
    InvokeGPUKernelParallel(scalePower,numBlocks,params.blockSize,mem.d_grid,(double)params.ng,params.rl,params.nlocal);
    InvokeGPUKernelParallel(PkCICFilter,numBlocks,params.blockSize,mem.d_grid,params.ng,params.nlocal,params.local_grid_size_vec,params.grid_coords_vec);
    cudaCall(cudaMemset,d_binCounts,0,sizeof(int)*nbins);
    cudaCall(cudaMemset,d_binVals,0,sizeof(double)*nbins);
    InvokeGPUKernelParallel(BinPower,numBlocks,params.blockSize,mem.d_grid,d_binVals,d_binCounts,minK,binDelta,new_rl,params.ng,params.nlocal,params.world_rank,params.local_grid_size_vec,params.grid_coords_vec,params.grid_dims_vec);
    #ifdef VerbosePower
    if(params.world_rank == 0)printf("%s      Calculated PK\n",indent);
    if(params.world_rank == 0)printf("%s   Sending values\n",indent);
    #endif
    cudaCall(cudaMemcpy, binVals, d_binVals, sizeof(double)*nbins, cudaMemcpyDeviceToHost);
    cudaCall(cudaMemcpy, binCounts, d_binCounts, sizeof(int)*nbins, cudaMemcpyDeviceToHost);
    HACCGPM::parallel::sendPower(binCounts,binVals,nbins,params.world_rank,params.world_size,calls+1);
    #ifdef VerbosePower
    if(params.world_rank == 0)printf("%s      Sent values\n",indent);
    #endif
    if (params.world_rank == 0)writePkOutput(fname,binVals,binCounts,kBins,nbins,0);
    free(kBins);
    free(binCounts);
    free(binVals);
    cudaCall(cudaFree,d_binCounts);
    cudaCall(cudaFree,d_binVals);
}
References BinPower(), CIC(), CPUTimer(), cudaCall, do_return(), forward_fft(), getIndent, InvokeGPUKernelParallel, PkCICFilter(), scalePower(), sendPower(), world_rank, and writePkOutput().
Referenced by parallel().
init_swfft()
void HACCGPM::parallel::init_swfft (HACCGPM::Params & params)
Definition at line 58 of file swfftmanager.cpp.
{
    //FFTManager tmp(params);
    ffts = new FFTManager(params);
}
References ffts.
Referenced by parallel().
InitGreens()
void HACCGPM::parallel::InitGreens (HACCGPM::Params & params, HACCGPM::parallel::MemoryManager & mem, int calls = 0)
Definition at line 27 of file greens.cpp.
{
    int world_rank = params.world_rank;
    int numBlocks = (params.nlocal + (params.blockSize - 1))/params.blockSize;
    getIndent(calls);
    #ifdef VerboseGreens
    if(params.world_rank == 0)printf("%sInitGreens was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,params.blockSize,indent,numBlocks);
    if(params.world_rank == 0)printf("%s   Calling getGreens...\n",indent);
    #endif
    launch_getgreens(mem.d_greens,params.ng,params.nlocal,params.local_grid_size_vec,params.grid_coords_vec,params.world_rank,numBlocks,params.blockSize,calls);
    #ifdef VerboseGreens
    if(params.world_rank == 0)printf("%s      Called getGreens...\n",indent);
    #endif
}
References do_return(), getIndent, launch_getgreens(), and world_rank.
Referenced by parallel().
insertParticles()
CPUTimer_t HACCGPM::parallel::insertParticles (float4 * d_pos, float4 * d_vel, float4 * h_swap, int n_new, int n_particles, int blockSize, int world_rank, int calls = 0)
Definition at line 5 of file particleswapkernels.cpp.
{
    int numBlocks = (n_particles + blockSize - 1) / blockSize;
    getIndent(calls);
    #ifdef VerboseSwap
    if(world_rank == 0)printf("%sinsertParticles was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,blockSize,indent,numBlocks);
    if(world_rank == 0)printf("%s   Copying to device\n",indent);
    #endif
    CPUTimer_t start = CPUTimer();
    float4* d_swap; cudaCall(cudaMalloc,&d_swap,sizeof(float4)*2*n_new);
    cudaCall(cudaMemcpy,d_swap,h_swap,sizeof(float4)*2*n_new,cudaMemcpyHostToDevice);
    int* d_count; cudaCall(cudaMalloc,&d_count,sizeof(int)*1);
    cudaCall(cudaMemset,d_count,0,sizeof(int)*1);
    #ifdef VerboseSwap
    if(world_rank == 0)printf("%s      Copied to device\n",indent);
    #endif
    CPUTimer_t gpu_time = 0;
    gpu_time += launch_combine_particles(d_pos,d_vel,d_swap,d_count,n_new,n_particles,world_rank,numBlocks,blockSize,calls);
    cudaCall(cudaFree,d_swap);
    cudaCall(cudaFree,d_count);
    CPUTimer_t end = CPUTimer();
    CPUTimer_t total_time = end-start;
    #ifdef VerboseSwap
    if(world_rank == 0)printf("%s   insertParticles took %llu us\n",indent,total_time);
    #endif
    return gpu_time;
}
References CPUTimer(), cudaCall, do_return(), getIndent, launch_combine_particles(), and world_rank.
Referenced by TransferParticles().
LoadIntoBuffers()
CPUTimer_t HACCGPM::parallel::LoadIntoBuffers (float4 * h_swap, int * n_swaps, int * h_starts, float4 * d_pos, float4 * d_vel, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int n_particles, int ng, int blockSize, int world_rank, int world_size, int calls = 0)
Definition at line 40 of file particleswapkernels.cpp.
{
    int numBlocks = (n_particles + blockSize - 1) / blockSize;
    getIndent(calls);
    #ifdef VerboseSwap
    if(world_rank == 0)printf("%sLoadIntoBuffers was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,blockSize,indent,numBlocks);
    #endif
    CPUTimer_t start = CPUTimer();
    CPUTimer_t gpu_time = 0;
    int* d_ns; cudaCall(cudaMalloc,&d_ns,sizeof(int)*world_size);
    int* d_count; cudaCall(cudaMalloc,&d_count,sizeof(int)*world_size);
    cudaCall(cudaMemset,d_ns,0,sizeof(int) * world_size);
    cudaCall(cudaMemset,d_count,0,sizeof(int) * world_size);
    gpu_time += launch_count_buffer(d_ns,d_pos,n_particles,ng,local_grid_size,local_coords,dims,world_rank,numBlocks,blockSize,calls);
    cudaCall(cudaMemcpy, n_swaps, d_ns, sizeof(int)*world_size, cudaMemcpyDeviceToHost);
    h_starts[0] = 0;
    int transfer_size = 0;
    for (int i = 0; i < world_size; i++){
        if (i != world_rank){
            transfer_size += n_swaps[i];
        }
        if (i != (world_size - 1))h_starts[i+1] = transfer_size;
    }
    int* d_starts; cudaCall(cudaMalloc,&d_starts,sizeof(int)*world_size);
    cudaCall(cudaMemcpy,d_starts,h_starts,sizeof(int)*world_size,cudaMemcpyHostToDevice);
    float4* d_swap; cudaCall(cudaMalloc,&d_swap,sizeof(float4)*2*transfer_size);
    gpu_time += launch_load_buffer(d_swap,d_starts,d_count,d_pos,d_vel,n_particles,ng,local_grid_size,local_coords,dims,world_rank,numBlocks,blockSize,calls);
    cudaCall(cudaMemcpy, h_swap, d_swap, sizeof(float4)*2*transfer_size, cudaMemcpyDeviceToHost);
    cudaCall(cudaFree,d_ns);
    cudaCall(cudaFree,d_count);
    cudaCall(cudaFree,d_swap);
    cudaCall(cudaFree,d_starts);
    CPUTimer_t end = CPUTimer();
    CPUTimer_t total_time = end-start;
    #ifdef VerboseSwap
    if(world_rank == 0)printf("%s   LoadIntoBuffers took %llu us\n",indent,total_time);
    #endif
    return gpu_time;
}
References CPUTimer(), cudaCall, do_return(), getIndent, launch_count_buffer(), launch_load_buffer(), and world_rank.
Referenced by TransferParticles().
printCICTimes()
void HACCGPM::parallel::printCICTimes (int world_rank)
Definition at line 135 of file pm_actions.cpp.
{
    //MPI_Barrier(MPI_COMM_WORLD);
    CPUTimer_t total_min,total_max,total_mean,gpu_min,gpu_max,gpu_mean;
    HACCGPM::parallel::timing_stats(CIC_TIME,&total_min,&total_max,&total_mean);
    HACCGPM::parallel::timing_stats(CIC_KERNEL_TIME,&gpu_min,&gpu_max,&gpu_mean);
    //HACCGPM::parallel::timing_stats(TRANSFER_MPI_TIME,&mpi_min,&mpi_max,&mpi_mean);
    if (world_rank != 0)return;
    printf("   CIC                   -> calls: %d\n",CIC_CALLS);
    printf("                               total: %10llu us mean | %10llu us max  | %10llu us min  |\n",total_mean,total_max,total_min);
    printf("                                 cpu: %10llu us mean | %10llu us max  | %10llu us min  |\n",(total_mean-gpu_mean),(total_max - gpu_max), (total_min - gpu_min));
    printf("                                 gpu: %10llu us mean | %10llu us max  | %10llu us min  |\n",gpu_mean,gpu_max,gpu_min);
    //printf("                                 mpi: %10llu us mean | %10llu us max  | %10llu us min  |\n",mpi_mean,mpi_max,mpi_min);
    printf("                                 avg: %10llu us mean | %10llu us max  | %10llu us min  |\n",total_mean / CIC_CALLS,total_max / CIC_CALLS,total_min / CIC_CALLS);
}
References CIC_CALLS, CIC_KERNEL_TIME, CIC_TIME, do_return(), timing_stats(), and world_rank.
Referenced by parallel().
printFFTStats()
void HACCGPM::parallel::printFFTStats (int world_rank)
Definition at line 97 of file swfftmanager.cpp.
{
    CPUTimer_t forward_mean,forward_min,forward_max;
    CPUTimer_t backward_mean,backward_min,backward_max;
    HACCGPM::parallel::timing_stats(FORWARD_FFT_TIME,&forward_min,&forward_max,&forward_mean);
    HACCGPM::parallel::timing_stats(BACKWARD_FFT_TIME,&backward_min,&backward_max,&backward_mean);
    if (world_rank != 0)return;
    printf("   forward_fft           -> calls: %d\n",FORWARD_FFT_CALLS);
    printf("                               total: %10llu us mean | %10llu us max  | %10llu us min  |\n",forward_mean,forward_max,forward_min);
    printf("                                 avg: %10llu us mean | %10llu us max  | %10llu us min  |\n",forward_mean / FORWARD_FFT_CALLS,forward_max / FORWARD_FFT_CALLS,forward_min / FORWARD_FFT_CALLS);
    printf("   backward_fft          -> calls: %d\n",BACKWARD_FFT_CALLS);
    printf("                               total: %10llu us mean | %10llu us max  | %10llu us min  |\n",backward_mean,backward_max,backward_min);
    printf("                                 avg: %10llu us mean | %10llu us max  | %10llu us min  |\n",backward_mean / BACKWARD_FFT_CALLS,backward_max / BACKWARD_FFT_CALLS,backward_min / BACKWARD_FFT_CALLS);
}
References BACKWARD_FFT_CALLS, BACKWARD_FFT_TIME, FORWARD_FFT_CALLS, FORWARD_FFT_TIME, timing_stats(), and world_rank.
Referenced by parallel().
printGridExchangeBytes()
void HACCGPM::parallel::printGridExchangeBytes (int world_rank)
Definition at line 540 of file gridexchange.cpp.
{
    MPI_Barrier(MPI_COMM_WORLD);
    unsigned long long my_bytes = RESOLVE_BYTES;
    unsigned long long bytes;
    MPI_Reduce(&my_bytes,&bytes,1,MPI_UNSIGNED_LONG_LONG,MPI_SUM,0,MPI_COMM_WORLD);
    if (world_rank != 0)return;
    printf("   gridExchange.resolve -> calls: %10d | transferred %llu bytes\n",RESOLVE_CALLS,bytes);
}
References do_return(), RESOLVE_BYTES, RESOLVE_CALLS, and world_rank.
Referenced by parallel().
printGridExchangeTimes()
void HACCGPM::parallel::printGridExchangeTimes (int world_rank)
Definition at line 549 of file gridexchange.cpp.
{
    MPI_Barrier(MPI_COMM_WORLD);
    CPUTimer_t total_min,total_max,total_mean,gpu_min,gpu_max,gpu_mean,mpi_min,mpi_max,mpi_mean,cpu_min,cpu_max,cpu_mean;
    HACCGPM::parallel::timing_stats(RESOLVE_TIME,&total_min,&total_max,&total_mean);
    HACCGPM::parallel::timing_stats(RESOLVE_GPU_TIME,&gpu_min,&gpu_max,&gpu_mean);
    HACCGPM::parallel::timing_stats(RESOLVE_MPI_TIME,&mpi_min,&mpi_max,&mpi_mean);
    HACCGPM::parallel::timing_stats(RESOLVE_TIME - (RESOLVE_GPU_TIME + RESOLVE_MPI_TIME),&cpu_min,&cpu_max,&cpu_mean);
    if (world_rank != 0)return;
    printf("   gridExchange.resolve  -> calls: %d\n",RESOLVE_CALLS);
    printf("                               total: %10llu us mean | %10llu us max  | %10llu us min  |\n",total_mean,total_max,total_min);
    printf("                                 cpu: %10llu us mean | %10llu us max  | %10llu us min  |\n",cpu_mean,cpu_max, cpu_min);
    printf("                                 gpu: %10llu us mean | %10llu us max  | %10llu us min  |\n",gpu_mean,gpu_max,gpu_min);
    printf("                                 mpi: %10llu us mean | %10llu us max  | %10llu us min  |\n",mpi_mean,mpi_max,mpi_min);
    printf("                                 avg: %10llu us mean | %10llu us max  | %10llu us min  |\n",total_mean / RESOLVE_CALLS,total_max / RESOLVE_CALLS,total_min / RESOLVE_CALLS);
}
References do_return(), RESOLVE_CALLS, RESOLVE_GPU_TIME, RESOLVE_MPI_TIME, RESOLVE_TIME, timing_stats(), and world_rank.
Referenced by parallel().
printTimingStats()
void HACCGPM::parallel::printTimingStats (const char * preamble, double dt)
Definition at line 22 of file timers.cpp.
{
  int myrank, nranks;
  double max, min, sum, avg, var, stdev;
  MPI_Comm_rank(MPI_COMM_WORLD, &myrank);
  MPI_Comm_size(MPI_COMM_WORLD, &nranks);
  MPI_Allreduce(&dt, &max, 1, MPI_DOUBLE, MPI_MAX, MPI_COMM_WORLD);
  MPI_Allreduce(&dt, &min, 1, MPI_DOUBLE, MPI_MIN, MPI_COMM_WORLD);
  MPI_Allreduce(&dt, &sum, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
  avg = sum/nranks;
  dt -= avg;
  dt *= dt;
  MPI_Allreduce(&dt, &var, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
  var *= 1.0/nranks;
  stdev = sqrt(var);
  if(myrank==0) {
    printf("%s  max %.3es  avg %.3es  min %.3es  dev %.3es\n",
       preamble, max, avg, min, stdev);
  }
  MPI_Barrier(MPI_COMM_WORLD);
  return;
}
References do_return().
Referenced by CIC(), UpdatePositions(), and UpdateVelocities().
printTransferBytes()
void HACCGPM::parallel::printTransferBytes (int world_rank)
Definition at line 205 of file transfers.cpp.
{
    MPI_Barrier(MPI_COMM_WORLD);
    unsigned long long my_bytes = TRANSFER_BYTES;
    unsigned long long bytes;
    MPI_Reduce(&my_bytes,&bytes,1,MPI_UNSIGNED_LONG_LONG,MPI_SUM,0,MPI_COMM_WORLD);
    if (world_rank != 0)return;
    printf("   transferParticles    -> calls: %10d | transferred %llu bytes\n",TRANSFER_CALLS,bytes);
}
References do_return(), TRANSFER_BYTES, TRANSFER_CALLS, and world_rank.
Referenced by parallel().
printTransferTimes()
void HACCGPM::parallel::printTransferTimes (int world_rank)
Definition at line 214 of file transfers.cpp.
{
    MPI_Barrier(MPI_COMM_WORLD);
    CPUTimer_t total_min,total_max,total_mean,gpu_min,gpu_max,gpu_mean,mpi_min,mpi_max,mpi_mean,cpu_min,cpu_max,cpu_mean;
    HACCGPM::parallel::timing_stats(TRANSFER_TIME,&total_min,&total_max,&total_mean);
    HACCGPM::parallel::timing_stats(TRANSFER_GPU_TIME,&gpu_min,&gpu_max,&gpu_mean);
    HACCGPM::parallel::timing_stats(TRANSFER_MPI_TIME,&mpi_min,&mpi_max,&mpi_mean);
    HACCGPM::parallel::timing_stats(TRANSFER_TIME - (TRANSFER_GPU_TIME + TRANSFER_MPI_TIME),&cpu_min,&cpu_max,&cpu_mean);
    if (world_rank != 0)return;
    printf("   transferParticles     -> calls: %d\n",TRANSFER_CALLS);
    printf("                               total: %10llu us mean | %10llu us max  | %10llu us min  |\n",total_mean,total_max,total_min);
    printf("                                 cpu: %10llu us mean | %10llu us max  | %10llu us min  |\n",cpu_mean,cpu_max, cpu_mean);
    printf("                                 gpu: %10llu us mean | %10llu us max  | %10llu us min  |\n",gpu_mean,gpu_max,gpu_min);
    printf("                                 mpi: %10llu us mean | %10llu us max  | %10llu us min  |\n",mpi_mean,mpi_max,mpi_min);
    if(TRANSFER_CALLS != 0)printf("                                 avg: %10llu us mean | %10llu us max  | %10llu us min  |\n",total_mean / TRANSFER_CALLS,total_max / TRANSFER_CALLS,total_min / TRANSFER_CALLS);
}
References do_return(), timing_stats(), TRANSFER_CALLS, TRANSFER_GPU_TIME, TRANSFER_MPI_TIME, TRANSFER_TIME, and world_rank.
Referenced by parallel().
sendPower()
void HACCGPM::parallel::sendPower (int * binCounts, double * binVals, int nbins, int world_rank, int world_size, int calls = 0)
Definition at line 153 of file transfers.cpp.
{
    getIndent(calls);
    #ifdef VerboseTransfer
    if(world_rank == 0)printf("%ssendPower was called\n",indent);
    if(world_rank == 0)printf("%s   Waiting for all\n",indent);
    #endif
    MPI_Barrier(MPI_COMM_WORLD);
    #ifdef VerboseTransfer
    if(world_rank == 0)printf("%s      Waited for all\n",indent);
    if(world_rank == 0)printf("%s   Allocating binCountsOut, binValsOut\n",indent);
    #endif
    int* binCountsOut = (int*)malloc(sizeof(int)*nbins);
    double* binValsOut = (double*)malloc(sizeof(double)*nbins);
    #ifdef VerboseTransfer
    if(world_rank == 0)printf("%s      Allocated binCountsOut, binValsOut\n",indent);
    if(world_rank == 0)printf("%s   Doing reduce\n",indent);
    #endif
    MPI_Reduce(binCounts,binCountsOut,nbins,MPI_INT,MPI_SUM,0,MPI_COMM_WORLD);
    MPI_Reduce(binVals,binValsOut,nbins,MPI_DOUBLE,MPI_SUM,0,MPI_COMM_WORLD);
    #ifdef VerboseTransfer
    if(world_rank == 0)printf("%s      Done return\n",indent);
    if(world_rank == 0)printf("%s   Copying to rank 0\n",indent);
    #endif
    if(world_rank == 0){
        for (int i = 0; i < nbins; i++){
            binCounts[i] = binCountsOut[i];
            binVals[i] = binValsOut[i];
        }
    }
    #ifdef VerboseTransfer
    if(world_rank == 0)printf("%s      Copied to rank 0\n",indent);
    if(world_rank == 0)printf("%s   Freeing binCountsOut, binValsOut\n",indent);
    #endif
    free(binCountsOut);
    free(binValsOut);
    MPI_Barrier(MPI_COMM_WORLD);
    #ifdef VerboseTransfer
    if(world_rank == 0)printf("%s      Freed binCountsOut, binValsOut\n",indent);
    //if(world_rank == 0)printf("%s   Freeing binCountsOut, binValsOut\n",indent);
    #endif
}
References do_return(), getIndent, and world_rank.
Referenced by GetPowerSpectrum().
SolveGradient() [1/2]
void HACCGPM::parallel::SolveGradient (float4 * d_grad, deviceFFT_t * d_rho, hostFFT_t * d_greens, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, int ng, int n_particles, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int world_size, int overload, int blockSize, int calls = 0)
Definition at line 11 of file solver.cpp.
{
    int numBlocks = (nlocal + (blockSize - 1))/blockSize;
    getIndent(calls);
    #ifdef VerboseSolver
    if(world_rank == 0)printf("%sSolveGradent was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,blockSize,indent,numBlocks);
    if(world_rank == 0)printf("%s   Doing forward fft...\n",indent);
    #endif
    HACCGPM::parallel::forward_fft(d_rho,ng,calls+1);
    #ifdef VerboseSolver
    if(world_rank == 0)printf("%s      Done forward fft.\n",indent);
    if(world_rank == 0)printf("%s   Calling kspace_solve_gradient_parallel...\n",indent);
    #endif
    launch_kspace_solve_gradient(d_x,d_y,d_z,d_rho,d_greens,ng,nlocal,overload,local_grid_size,local_coords,world_rank,numBlocks,blockSize,calls);
    #ifdef VerboseSolver
    if(world_rank == 0)printf("%s      Called kspace_solve_gradient_parallel.\n",indent);
    if(world_rank == 0)printf("%s   Doing backward ffts...\n",indent);
    #endif
    HACCGPM::parallel::backward_fft(d_x,ng,calls+1);
    HACCGPM::parallel::backward_fft(d_y,ng,calls+1);
    HACCGPM::parallel::backward_fft(d_z,ng,calls+1);
    #ifdef VerboseSolver
    if(world_rank == 0)printf("%s      Done backward ffts.\n",indent);
    if(world_rank == 0)printf("%s   Calling combine_parallel...\n",indent);
    #endif
    launch_combine(d_grad,d_x,d_y,d_z,local_grid_size,local_coords,overload,nlocal,ng,world_rank,numBlocks,blockSize,calls);
    #ifdef VerboseSolver
    if(world_rank == 0)printf("%s      Done combine_parallel.\n",indent);
    #endif
    HACCGPM::parallel::GridExchange gexch(local_coords,local_grid_size,dims,ng,world_size,world_rank,overload,blockSize);
    gexch.fill(d_grad,calls+1);
}
References backward_fft(), do_return(), forward_fft(), getIndent, launch_combine(), launch_kspace_solve_gradient(), and world_rank.
SolveGradient() [2/2]
void HACCGPM::parallel::SolveGradient (HACCGPM::Params & params, HACCGPM::parallel::MemoryManager & mem, int calls = 0)
Definition at line 7 of file solver.cpp.
{
    HACCGPM::parallel::SolveGradient(mem.d_grad,mem.d_grid,mem.d_greens,mem.d_x,mem.d_y,mem.d_z,params.ng,params.n_particles,params.nlocal,params.local_grid_size_vec,params.grid_coords_vec,params.grid_dims_vec,params.world_rank,params.world_size,params.overload,params.blockSize,calls);
}
References do_return(), and SolveGradient().
Referenced by parallel(), and SolveGradient().
timing_stats()
void HACCGPM::parallel::timing_stats (CPUTimer_t t, CPUTimer_t * mint, CPUTimer_t * maxt, CPUTimer_t * meant)
Definition at line 6 of file timers.cpp.
{
    MPI_Barrier(MPI_COMM_WORLD);
    CPUTimer_t t = t_;
    MPI_Reduce(&t,mint,1,MPI_UNSIGNED_LONG_LONG,MPI_MIN,0,MPI_COMM_WORLD);
    MPI_Barrier(MPI_COMM_WORLD);
    t = t_;
    MPI_Reduce(&t,maxt,1,MPI_UNSIGNED_LONG_LONG,MPI_MAX,0,MPI_COMM_WORLD);
    MPI_Barrier(MPI_COMM_WORLD);
    t = t_;
    MPI_Reduce(&t,meant,1,MPI_UNSIGNED_LONG_LONG,MPI_SUM,0,MPI_COMM_WORLD);
    MPI_Barrier(MPI_COMM_WORLD);
    int comm_size;
    MPI_Comm_size(MPI_COMM_WORLD,&comm_size);
    *meant /= comm_size;
}
References do_return().
Referenced by parallel(), printCICTimes(), printFFTStats(), printGridExchangeTimes(), and printTransferTimes().
TransferParticles()
void HACCGPM::parallel::TransferParticles (HACCGPM::Params & params, HACCGPM::parallel::MemoryManager & mem, int calls = 0)
Definition at line 14 of file transfers.cpp.
{
    getIndent(calls);
    size_t bytes = 0;
    CPUTimer_t start = CPUTimer();
    int n_particles = params.n_particles;
    int3 local_grid_size = make_int3(params.local_grid_size[0],params.local_grid_size[1],params.local_grid_size[2]);
    int3 global_grid_size = make_int3(params.grid_dims[0],params.grid_dims[1],params.grid_dims[2]);
    int3 grid_coords = make_int3(params.grid_coords[0],params.grid_coords[1],params.grid_coords[2]);
    #ifdef VerboseTransfer
    if(params.world_rank == 0)printf("%sTransferParticles was called\n",indent);
    #endif
    int n_swaps[params.world_size];
    int n_recvs[params.world_size];
    for (int i = 0; i < params.world_size; i++){
        n_recvs[i] = 0;
    }
    int starts[params.world_size];
    #ifdef VerboseTransfer
    if(params.world_rank == 0)printf("%s   Loading buffers\n",indent);
    #endif
    //float4* swap = (float4*)malloc(sizeof(float4)*2*n_particles);
    float4* swap; HostMalloc(&swap,sizeof(float4)*2*n_particles);
    CPUTimer_t gpu_time = 0;
    gpu_time += HACCGPM::parallel::LoadIntoBuffers(swap,n_swaps,starts,mem.d_pos,mem.d_vel,params.nlocal,local_grid_size,grid_coords,global_grid_size,n_particles,params.ng,params.blockSize,params.world_rank,params.world_size,calls+1);
    bool neighbor_ranks[params.world_size];
    for (int i = 0; i < params.world_size; i++){
        neighbor_ranks[i] = false;
    }
    for (int x = -1; x < 2; x++){
        for (int y = -1; y < 2; y++){
            for (int z = -1; z < 2; z++){
                int3 neighbor_coords;
                neighbor_coords.x = ((grid_coords.x + x) + global_grid_size.x) % global_grid_size.x;
                neighbor_coords.y = ((grid_coords.y + y) + global_grid_size.y) % global_grid_size.y;
                neighbor_coords.z = ((grid_coords.z + z) + global_grid_size.z) % global_grid_size.z;
                int this_rank = neighbor_coords.x * global_grid_size.y * global_grid_size.z + neighbor_coords.y * global_grid_size.z + neighbor_coords.z;
                if (this_rank == params.world_rank)continue;
                neighbor_ranks[this_rank] = true;
            }
        }
    }
    neighbor_ranks[params.world_rank] = false;
    #ifdef VerboseTransfer
    if(params.world_rank == 0)printf("%s   Send Counts\n",indent);
    #endif
    MPI_Barrier(MPI_COMM_WORLD);
    CPUTimer_t mpi_start = CPUTimer();
    for (int i = 0; i < params.world_size; i++){
        if (!neighbor_ranks[i])continue;
        if (i == params.world_rank)continue;
        MPI_Request req;
        MPI_Isend(&n_swaps[i],1,MPI_INT,i,0,MPI_COMM_WORLD,&req);
        bytes += sizeof(int) * 1;
        //printf("%s      Rank %d sending n_swaps[%d] = %d to rank %d\n",indent,params.world_rank,i,n_swaps[i],i);
        MPI_Request_free(&req);
        //printf("rank %d is neighbors with %d\n",params.world_rank,i);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #ifdef VerboseTransfer
    if(params.world_rank == 0)printf("%s   Recv Counts\n",indent);
    #endif
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < params.world_size; i++){
        if (!neighbor_ranks[i])continue;
        if (i == params.world_rank)continue;
        MPI_Recv(&n_recvs[i],1,MPI_INT,i,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
        //printf("%s      Rank %d recieving n_recvs[%d] = %d from rank %d\n",indent,params.world_rank,i,n_recvs[i],i);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    int total_recieved = 0;
    int recv_starts[params.world_size];
    for (int i = 0; i < params.world_size; i++){
        recv_starts[i] = total_recieved;
        if (i == params.world_rank)continue;
        total_recieved += n_recvs[i];
    }
    //float4* recieved = (float4*)malloc(sizeof(float4)*2*n_particles);
    float4* recieved; HostMalloc(&recieved,sizeof(float4)*2*n_particles);
    MPI_Barrier(MPI_COMM_WORLD);
    #ifdef VerboseTransfer
    if(params.world_rank == 0)printf("%s   Send particles\n",indent);
    #endif
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < params.world_size; i++){
        if ((!neighbor_ranks[i]) || (n_swaps[i] == 0))continue;
        if (i == params.world_rank)continue;
        MPI_Request req;
        MPI_Isend(&swap[starts[i]*2],n_swaps[i]*4*2,MPI_FLOAT,i,0,MPI_COMM_WORLD,&req);
        bytes += sizeof(float) * 4 * 2 * n_swaps[i];
        //printf("%s      Rank %d sending %d particles (start = %d) to rank %d\n",indent,params.world_rank,n_swaps[i],starts[i]*2,i);
        MPI_Request_free(&req);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #ifdef VerboseTransfer
    if(params.world_rank == 0)printf("%s   Recv particles\n",indent);
    #endif
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < params.world_size; i++){
        if ((!neighbor_ranks[i]) || (n_recvs[i] == 0))continue;
        if (i == params.world_rank)continue;
        MPI_Recv(&recieved[recv_starts[i]*2],n_recvs[i]*4*2,MPI_FLOAT,i,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
        //printf("%s      Rank %d reciving %d particles (start = %d) from rank %d\n",indent,params.world_rank,n_recvs[i],recv_starts[i]*2,i);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    CPUTimer_t mpi_end = CPUTimer();
    gpu_time += HACCGPM::parallel::insertParticles(mem.d_pos,mem.d_vel,recieved,total_recieved,params.n_particles,params.blockSize,params.world_rank,calls+1);
    //free(swap);
    HostFree(swap);
    HostFree(recieved);
    CPUTimer_t end = CPUTimer();
    CPUTimer_t total_time = end-start;
    TRANSFER_CALLS++;
    TRANSFER_TIME += total_time;
    TRANSFER_GPU_TIME += gpu_time;
    TRANSFER_MPI_TIME += mpi_end - mpi_start;
    TRANSFER_BYTES += bytes;
    #ifdef VerboseTransfer
    if(params.world_rank == 0)printf("%s   TransferParticles took %llu us\n",indent,total_time);
    #endif
}
References CPUTimer(), do_return(), getIndent, HostFree, HostMalloc, insertParticles(), LoadIntoBuffers(), TRANSFER_BYTES, TRANSFER_CALLS, TRANSFER_GPU_TIME, TRANSFER_MPI_TIME, and TRANSFER_TIME.
Referenced by parallel(), and UpdatePositions().
UpdatePositions() [1/2]
int HACCGPM::parallel::UpdatePositions (float4 * d_pos, float4 * d_vel, HACCGPM::Timestepper ts, float frac, int ng, int n_particles, int3 local_grid_size, int overload, int blockSize, int world_rank, int calls = 0)
Definition at line 82 of file pm_actions.cpp.
{
    CPUTimer_t start = CPUTimer();
    int numBlocks = (n_particles + (blockSize - 1))/blockSize;
    float prefactor = ((ts.deltaT)/(ts.aa * ts.aa * ts.adot)) * frac;
    getIndent(calls);
    #ifdef VerboseUpdate
    if(world_rank == 0)printf("%sUpdate Positions was called with\n%s   blockSize %d\n%s   numBlocks %d\n%s   frac %g\n%s   prefactor %g\n",indent,indent,blockSize,indent,numBlocks,indent,frac,indent,prefactor);
    #endif
    //UPDATE_POS_KERNEL_TIME += InvokeGPUKernelParallel(UpdatePosKernelParallel,numBlocks,blockSize,d_pos,d_vel,prefactor,n_particles);
    int do_refresh;
    UPDATE_POS_KERNEL_TIME += launch_updatepos(d_pos,d_vel,prefactor,n_particles,local_grid_size,overload,&do_refresh,world_rank,numBlocks,blockSize,calls);
    //printf("DO_REFRESH %d\n",do_refresh);
    int refresh_now;
    MPI_Allreduce(&do_refresh,&refresh_now,1,MPI_INT,MPI_LOR,MPI_COMM_WORLD);
    //printf("refresh_now %d\n",refresh_now);
    //if (refresh_now){
    //    printf("ALLL!!!!\n");
    //}
    CPUTimer_t end = CPUTimer();
    CPUTimer_t t = end-start;
    #ifdef VerboseUpdate
    if (world_rank == 0)printf("%s   UpdatePositions took %llu us\n",indent,t);
    #else
    HACCGPM::parallel::printTimingStats("PMAC uppos",((double)t) * 1e-6);
    #endif
    UPDATE_POS_TIME += t;
    UPDATE_POS_CALLS += 1;
    return refresh_now;
}
References CPUTimer(), do_return(), getIndent, launch_updatepos(), printTimingStats(), UPDATE_POS_CALLS, UPDATE_POS_KERNEL_TIME, UPDATE_POS_TIME, and world_rank.
UpdatePositions() [2/2]
void HACCGPM::parallel::UpdatePositions (HACCGPM::Params & params, HACCGPM::parallel::MemoryManager & mem, HACCGPM::Timestepper ts, float frac, int calls = 0)
Definition at line 75 of file pm_actions.cpp.
{
    if(HACCGPM::parallel::UpdatePositions(mem.d_pos,mem.d_vel,ts,frac,params.ng,params.n_particles,params.local_grid_size_vec,params.overload,params.blockSize,params.world_rank,calls)){
        //if(params.world_rank == 0)printf("DOING TRANSFER!!!!\n");
        HACCGPM::parallel::TransferParticles(params,mem);
    }
}
References do_return(), TransferParticles(), and UpdatePositions().
Referenced by parallel(), and UpdatePositions().
UpdateVelocities() [1/2]
void HACCGPM::parallel::UpdateVelocities (float4 * d_vel, float4 * d_grad, float4 * d_pos, HACCGPM::Timestepper ts, int n_particles, int ng, int overload, int3 local_grid_size, int blockSize, int world_rank, int calls = 0)
Definition at line 116 of file pm_actions.cpp.
{
    CPUTimer_t start = CPUTimer();
    int numBlocks = (n_particles + (blockSize - 1))/blockSize;
    getIndent(calls);
    #ifdef VerboseUpdate
    if(world_rank == 0)printf("%sUpdate Velocities was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,blockSize,indent,numBlocks);
    #endif
    UPDATE_VEL_KERNEL_TIME += launch_icic(d_vel,d_grad,d_pos,ts.deltaT,ts.fscal,overload,local_grid_size,ng,n_particles,world_rank,numBlocks,blockSize,calls);
    CPUTimer_t end = CPUTimer();
    CPUTimer_t t = end-start;
    #ifdef VerboseUpdate
    if(world_rank == 0)printf("%s   UpdateVelocities took %llu us\n",indent,t);
    #else
    HACCGPM::parallel::printTimingStats("PMAC upvel",((double)t) * 1e-6);
    #endif
    UPDATE_VEL_TIME += t;
    UPDATE_VEL_CALLS += 1;
}
References CPUTimer(), do_return(), getIndent, launch_icic(), printTimingStats(), UPDATE_VEL_CALLS, UPDATE_VEL_KERNEL_TIME, UPDATE_VEL_TIME, and world_rank.
UpdateVelocities() [2/2]
void HACCGPM::parallel::UpdateVelocities (HACCGPM::Params & params, HACCGPM::parallel::MemoryManager & mem, HACCGPM::Timestepper ts, int calls = 0)
Definition at line 112 of file pm_actions.cpp.
{
    HACCGPM::parallel::UpdateVelocities(mem.d_vel,mem.d_grad,mem.d_pos,ts,params.n_particles,params.ng,params.overload,params.local_grid_size_vec,params.blockSize,params.world_rank,calls);
}
References do_return(), and UpdateVelocities().
Referenced by parallel(), and UpdateVelocities().