HACC_GPM: PlanManager Class Reference
PlanManager Class Reference
Public Member Functions
PlanManager ()
~PlanManager ()
cufftHandle get_plan (int ng, int calls)
Public Attributes
cufftHandle plans [FFTCacheSize]
int ngs [FFTCacheSize]
int used
Detailed Description
Definition at line 25 of file ffts.cu.
Constructor & Destructor Documentation
PlanManager()
PlanManager::PlanManager () inline
Definition at line 30 of file ffts.cu.
                     {
            //printf("FFT PlanManager:\n");
            //printf("   Initialized\n");
            used = 0;
        }
References used.
~PlanManager()
PlanManager::~PlanManager () inline
Definition at line 35 of file ffts.cu.
                      {
            if (used != 0){
                printf("FFT PlanManager:\n");
                for (int i = 0; i < used; i++){
                    printf("   Freeing plan %d\n",ngs[i]);
                    cufftDestroy(plans[i]);
                }
            } else {
                //printf("   No plans to free\n");
            }
        }
References ngs, plans, and used.
Member Function Documentation
get_plan()
cufftHandle PlanManager::get_plan (int ng, int calls) inline
Definition at line 46 of file ffts.cu.
{
            getIndent(calls);
            printf("%sFFT PlanManager:\n",indent);
            printf("%s   Searching for cached plan %d\n",indent,ng);
            for (int i = 0; i < used; i++){
                if (ngs[i] == ng){
                    printf("%s   Found cached plan %d\n",indent,ngs[i]);
                    return plans[i];
                }
            }
            if (used >= FFTCacheSize){
                printf("%s   No more space to create new plan!!!\n",indent);
                exit(1);
            }
            printf("%s   No cached plan %d found, creating one\n",indent,ng);
            if (cufftPlan3d(&plans[used], ng, ng, ng, CUFFT_Z2Z) != CUFFT_SUCCESS){
                printf("CUFFT error: Plan creation failed\n");
                exit(1);
            };
            ngs[used] = ng;
            used++;
            return plans[used-1];
        }
References FFTCacheSize, getIndent, ngs, plans, and used.
Referenced by HACCGPM::serial::backward_fft(), HACCGPM::serial::backward_fft(), HACCGPM::serial::fft_cache_plan(), HACCGPM::serial::forward_fft(), and HACCGPM::serial::forward_fft().
Member Data Documentation
ngs
int PlanManager::ngs[FFTCacheSize]
Definition at line 28 of file ffts.cu.
Referenced by get_plan(), and ~PlanManager().
plans
cufftHandle PlanManager::plans[FFTCacheSize]
Definition at line 27 of file ffts.cu.
Referenced by get_plan(), and ~PlanManager().
used
int PlanManager::used
Definition at line 29 of file ffts.cu.
Referenced by get_plan(), PlanManager(), and ~PlanManager().
The documentation for this class was generated from the following file:
/home/hqureshi/HACC_GPM/src/fft_tools/ffts.cu