HACC_GPM: /home/hqureshi/HACC_GPM/src/initializer.cu File Reference
initializer.cu File Reference
#include <stdlib.h>
#include <stdio.h>
#include "haccgpm.hpp"
#include <math.h>
#include <curand.h>
#include <curand_kernel.h>
#include "../cambTools/ccamb.h"
Macros
#define VerboseInitializer
Functions
__global__ void initRNG (curandState *state, int seed)
__global__ void initRNG (curandState *state, int seed, int nlocal, int world_rank)
__global__ void GenerateRealRandom (curandState *state, deviceFFT_t *__restrict grid)
__global__ void ScaleAmplitudes (deviceFFT_t *__restrict grid, const hostFFT_t *__restrict scale)
__global__ void ScaleFFT (deviceFFT_t *__restrict data, double scale)
__global__ void transformDensityField (const deviceFFT_t *__restrict oldGrid, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double rl, double a, int ng)
__global__ void transformDensityField (const deviceFFT_t *__restrict oldGrid, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double rl, double a, int ng, int nlocal, int world_rank)
__global__ void placeParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double dotDelta, double rl, double a, double deltaT, double fscal, int ng)
__global__ void placeParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double dotDelta, double rl, double a, double deltaT, double fscal, int ng, int nx, int ny, int nz, int nlocal, int world_rank)
void GenerateFourierAmplitudes (const char *params_file, deviceFFT_t *d_grid1, int ng, double rl, double z, int seed, int blockSize, int calls)
void GenerateFourierAmplitudesParallel (const char *params_file, deviceFFT_t *d_grid, int ng, double rl, double z, int seed, int blockSize, int world_rank, int world_size, int nlocal, int calls)
Macro Definition Documentation
VerboseInitializer
#define VerboseInitializer
Definition at line 9 of file initializer.cu.
Function Documentation
GenerateFourierAmplitudes()
void GenerateFourierAmplitudes (const char * params_file, deviceFFT_t * d_grid1, int ng, double rl, double z, int seed, int blockSize, int calls)
Definition at line 195 of file initializer.cu.
{
    int numBlocks = (ng*ng*ng)/blockSize;
    getIndent(calls);
    #ifdef VerboseInitializer
    printf("%sGenerateFourierAmplitudes was called with\n%s   blockSize %d\n%s   numBlocks %d\n%s   z %g\n",indent,indent,blockSize,indent,numBlocks,indent,z);
    printf("%s   Allocating rngState, h_tmp, d_pkScale...\n",indent);
    #endif
    curandState* rngState; cudaCall(cudaMalloc,&rngState,sizeof(curandState)*ng*ng*ng);
    hostFFT_t* h_tmp = (hostFFT_t*)malloc(sizeof(hostFFT_t)*ng*ng*ng);
    hostFFT_t* d_pkScale; cudaCall(cudaMalloc,&d_pkScale,sizeof(hostFFT_t)*ng*ng*ng);
    #ifdef VerboseInitializer
    printf("%s      Allocated rngState, h_tmp, d_pkScale.\n",indent);
    printf("%s   Calling initRNG...\n",indent);
    #endif
    InvokeGPUKernel(initRNG,numBlocks,blockSize,rngState,seed);
    #ifdef VerboseInitializer
    printf("%s      Called initRNG.\n",indent);
    printf("%s   Calling GenerateRealRandom...\n",indent);
    #endif
    InvokeGPUKernel(GenerateRealRandom,numBlocks,blockSize,rngState,d_grid1);
    #ifdef VerboseInitializer
    printf("%s      Called GenerateRealRandom.\n",indent);
    printf("%s   Doing Forward FFT...\n",indent);
    #endif
    HACCGPM::serial::forward_fft(d_grid1,ng,calls+1);
    #ifdef VerboseInitializer
    printf("%s      Done Forward FFT...\n",indent);
    printf("%s   Getting Pk from Camb...\n",indent);
    #endif
    //init_python(calls + 1);
    get_pk(params_file,h_tmp,z,ng,rl,calls+1);
    #ifdef VerboseInitializer
    printf("%s      Got Pk from Camb.\n",indent);
    printf("%s   Copying Pk from host to device...\n",indent);
    #endif
    cudaCall(cudaMemcpy, d_pkScale, h_tmp, sizeof(hostFFT_t)*ng*ng*ng, cudaMemcpyHostToDevice);
    #ifdef VerboseInitializer
    printf("%s      Copied Pk from host to device.\n",indent);
    printf("%s   Scaling Amplitudes...\n",indent);
    #endif
    InvokeGPUKernel(ScaleAmplitudes,numBlocks,blockSize,d_grid1,d_pkScale);
    #ifdef VerboseInitializer
    printf("%s      Scaled Amplitudes.\n",indent);
    printf("%s   Freeing rngState, h_tmp, d_pkScale...\n",indent);
    #endif
    free(h_tmp);
    cudaFree(d_pkScale);
    cudaFree(rngState);
    #ifdef VerboseInitializer
    printf("%s      Freed rngState, h_tmp, d_pkScale.\n",indent);
    #endif
}
References cudaCall, HACCGPM::serial::forward_fft(), GenerateRealRandom(), get_pk(), getIndent, hostFFT_t, initRNG(), InvokeGPUKernel, and ScaleAmplitudes().
Referenced by HACCGPM::serial::GenerateDisplacementIC().
GenerateFourierAmplitudesParallel()
void GenerateFourierAmplitudesParallel (const char * params_file, deviceFFT_t * d_grid, int ng, double rl, double z, int seed, int blockSize, int world_rank, int world_size, int nlocal, int calls)
Definition at line 344 of file initializer.cu.
{
    int numBlocks = (nlocal)/blockSize;
    getIndent(calls);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%sGenerateFourierAmplitudesParallel was called with\n%s   blockSize %d\n%s   numBlocks %d\n%s   z %g\n",indent,indent,blockSize,indent,numBlocks,indent,z);
    if(world_rank == 0)printf("%s   Allocating rngState, h_tmp, d_pkScale...\n",indent);
    #endif
    curandState* rngState; cudaCall(cudaMalloc,&rngState,sizeof(curandState)*nlocal);
    hostFFT_t* h_tmp = (hostFFT_t*)malloc(sizeof(hostFFT_t)*nlocal);
    hostFFT_t* d_pkScale; cudaCall(cudaMalloc,&d_pkScale,sizeof(hostFFT_t)*nlocal);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Allocated rngState, h_tmp, d_pkScale.\n",indent);
    if(world_rank == 0)printf("%s   Calling initRNG...\n",indent);
    #endif
    InvokeGPUKernelParallel(initRNG,numBlocks,blockSize,rngState,seed,nlocal,world_rank);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Called initRNG.\n",indent);
    if(world_rank == 0)printf("%s   Calling GenerateRealRandom...\n",indent);
    #endif
    InvokeGPUKernelParallel(GenerateRealRandom,numBlocks,blockSize,rngState,d_grid);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Called GenerateRealRandom.\n",indent);
    if(world_rank == 0)printf("%s   Doing Forward FFT...\n",indent);
    #endif
    HACCGPM::parallel::forward_fft(d_grid,ng,calls+1);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Done Forward FFT...\n",indent);
    if(world_rank == 0)printf("%s   Getting Pk from Camb...\n",indent);
    #endif
    get_pk_parallel(params_file,h_tmp,z,ng,rl,nlocal,world_rank,calls+1);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Got Pk from Camb.\n",indent);
    if(world_rank == 0)printf("%s   Copying Pk from host to device...\n",indent);
    #endif
    cudaCall(cudaMemcpy, d_pkScale, h_tmp, sizeof(hostFFT_t)*nlocal, cudaMemcpyHostToDevice);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Copied Pk from host to device.\n",indent);
    if(world_rank == 0)printf("%s   Scaling Amplitudes...\n",indent);
    #endif
    InvokeGPUKernelParallel(ScaleAmplitudes,numBlocks,blockSize,d_grid,d_pkScale);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Scaled Amplitudes.\n",indent);
    if(world_rank == 0)printf("%s   Freeing rngState, h_tmp, d_pkScale...\n",indent);
    #endif
    free(h_tmp);
    cudaFree(d_pkScale);
    cudaFree(rngState);
    #ifdef VerboseInitializer
    if(world_rank == 0)printf("%s      Freed rngState, h_tmp, d_pkScale.\n",indent);
    #endif
}
References cudaCall, HACCGPM::parallel::forward_fft(), GenerateRealRandom(), get_pk_parallel(), getIndent, hostFFT_t, initRNG(), InvokeGPUKernelParallel, ScaleAmplitudes(), and world_rank.
Referenced by HACCGPM::parallel::GenerateDisplacementIC().
GenerateRealRandom()
__global__ void GenerateRealRandom (curandState * state, deviceFFT_t *__restrict grid)
Definition at line 25 of file initializer.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    hostFFT_t amp = curand_normal_double(state + idx);
    deviceFFT_t out;
    out.x = amp;
    out.y = 0;
    grid[idx] = out;
}
References deviceFFT_t, and hostFFT_t.
Referenced by GenerateFourierAmplitudes(), and GenerateFourierAmplitudesParallel().
initRNG() [1/2]
__global__ void initRNG (curandState * state, int seed)
Definition at line 11 of file initializer.cu.
{
  int idx = threadIdx.x+blockDim.x*blockIdx.x;
  curand_init(seed, idx, 0, &state[idx]);
}
Referenced by GenerateFourierAmplitudes(), and GenerateFourierAmplitudesParallel().
initRNG() [2/2]
__global__ void initRNG (curandState * state, int seed, int nlocal, int world_rank)
Definition at line 18 of file initializer.cu.
{
  int idx = threadIdx.x+blockDim.x*blockIdx.x;
  curand_init(seed, idx + nlocal * world_rank, 0, &state[idx]);
}
References world_rank.
placeParticles() [1/2]
__global__ void placeParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double dotDelta, double rl, double a, double deltaT, double fscal, int ng)
Definition at line 137 of file initializer.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    float4 my_particle = make_float4(idx3d.x,idx3d.y,idx3d.z,idx);
    deviceFFT_t thisSx = __ldg(&outSx[idx]);
    deviceFFT_t thisSy = __ldg(&outSy[idx]);
    deviceFFT_t thisSz = __ldg(&outSz[idx]);
    float3 s = make_float3(thisSx.x,thisSy.x,thisSz.x);
    float velA = a - (deltaT * 0.5f);
    float velMul = (velA * velA * dotDelta * fscal);
    float4 my_vel = make_float4(velMul*s.x,velMul*s.y,velMul*s.z,idx);
    my_particle.x += delta * s.x + ng;
    my_particle.x = fmod(my_particle.x,(float)ng);
    my_particle.y += delta * s.y + ng;
    my_particle.y = fmod(my_particle.y,(float)ng);
    my_particle.z += delta * s.z + ng;
    my_particle.z = fmod(my_particle.z,(float)ng);
    d_pos[idx] = my_particle;
    d_vel[idx] = my_vel;
}
References deviceFFT_t, and HACCGPM::serial::get_index().
Referenced by HACCGPM::parallel::GenerateDisplacementIC(), and HACCGPM::serial::GenerateDisplacementIC().
placeParticles() [2/2]
__global__ void placeParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double dotDelta, double rl, double a, double deltaT, double fscal, int ng, int nx, int ny, int nz, int nlocal, int world_rank)
Definition at line 165 of file initializer.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    int3 idx3d = HACCGPM::parallel::get_local_index(idx,nx,ny,nz);
    float4 my_particle = make_float4(idx3d.x,idx3d.y,idx3d.z,idx + nlocal*world_rank);
    deviceFFT_t thisSx = __ldg(&outSx[idx]);
    deviceFFT_t thisSy = __ldg(&outSy[idx]);
    deviceFFT_t thisSz = __ldg(&outSz[idx]);
    float3 s = make_float3(thisSx.x,thisSy.x,thisSz.x);
    float velA = a - (deltaT * 0.5f);
    float velMul = (velA * velA * dotDelta * fscal);
    float4 my_vel = make_float4(velMul*s.x,velMul*s.y,velMul*s.z,idx + nlocal*world_rank);
    my_particle.x += delta * s.x;
    //my_particle.x = fmod(my_particle.x,(float)ng);
    my_particle.y += delta * s.y;
    //my_particle.y = fmod(my_particle.y,(float)ng);
    my_particle.z += delta * s.z;
    //my_particle.z = fmod(my_particle.z,(float)ng);
    //printf("delta %g, sx %g, sy %g, sz %g\n",delta,s.x,s.y,s.z);
    //printf("%g %g %g %g, %g %g %g %g\n",my_particle.x,my_particle.y,my_particle.z,my_particle.w,my_vel.x,my_vel.y,my_vel.z,my_vel.w);
    d_pos[idx] = my_particle;
    d_vel[idx] = my_vel;
}
References deviceFFT_t, HACCGPM::parallel::get_local_index(), and world_rank.
ScaleAmplitudes()
__global__ void ScaleAmplitudes (deviceFFT_t *__restrict grid, const hostFFT_t *__restrict scale)
Definition at line 34 of file initializer.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    hostFFT_t base_scale_by = __ldg(&scale[idx]);
    hostFFT_t scale_by = sqrt(base_scale_by);
    deviceFFT_t current = __ldg(&grid[idx]);
    //printf("d_grid[%d]: %g %g\n",idx,current.x,current.y);
    current.x *= scale_by;
    current.y *= scale_by;
    //printf("%g %g\n",current.x,current.y);
    grid[idx] = current;
}
References deviceFFT_t, and hostFFT_t.
Referenced by GenerateFourierAmplitudes(), and GenerateFourierAmplitudesParallel().
ScaleFFT()
__global__ void ScaleFFT (deviceFFT_t *__restrict data, double scale)
Definition at line 46 of file initializer.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    deviceFFT_t old = __ldg(&data[idx]);
    old.x *= scale;
    old.y *= scale;
    data[idx] = old;
}
References deviceFFT_t.
Referenced by HACCGPM::parallel::GenerateDisplacementIC(), and HACCGPM::serial::GenerateDisplacementIC().
transformDensityField() [1/2]
__global__ void transformDensityField (const deviceFFT_t *__restrict oldGrid, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double rl, double a, int ng)
Definition at line 59 of file initializer.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    double d = (2*M_PI)/rl;
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    float3 kmodes = HACCGPM::serial::get_kmodes(idx3d,ng,d);
    double k2 = kmodes.x * kmodes.x + kmodes.y * kmodes.y + kmodes.z * kmodes.z;
    double k2mul = (1/k2);
    if (k2 == 0){
        k2mul = 0;
    }
    double mul = (1/delta) * k2mul;
    deviceFFT_t current = __ldg(&oldGrid[idx]);
    current.x *= mul;
    current.y *= mul;
    deviceFFT_t sx,sy,sz;
    sx.x = current.y * kmodes.x;
    sx.y = -current.x * kmodes.x;
    sy.x = current.y * kmodes.y;
    sy.y = -current.x * kmodes.y;
    sz.x = current.y * kmodes.z;
    sz.y = -current.x * kmodes.z;
    outSx[idx] = sx;
    outSy[idx] = sy;
    outSz[idx] = sz;
}
References deviceFFT_t, HACCGPM::serial::get_index(), and HACCGPM::serial::get_kmodes().
Referenced by HACCGPM::parallel::GenerateDisplacementIC(), and HACCGPM::serial::GenerateDisplacementIC().
transformDensityField() [2/2]
__global__ void transformDensityField (const deviceFFT_t *__restrict oldGrid, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double rl, double a, int ng, int nlocal, int world_rank)
Definition at line 98 of file initializer.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    double d = (2*M_PI)/rl;
    int3 idx3d = HACCGPM::parallel::get_global_index(idx,ng,nlocal,world_rank);
    float3 kmodes = HACCGPM::parallel::get_kmodes(idx3d,ng,d);
    double k2 = kmodes.x * kmodes.x + kmodes.y * kmodes.y + kmodes.z * kmodes.z;
    double k2mul = (1/k2);
    if (k2 == 0){
        k2mul = 0;
    }
    double mul = (1/delta) * k2mul;
    deviceFFT_t current = __ldg(&oldGrid[idx]);
    current.x *= mul;
    current.y *= mul;
    deviceFFT_t sx,sy,sz;
    sx.x = current.y * kmodes.x;
    sx.y = -current.x * kmodes.x;
    sy.x = current.y * kmodes.y;
    sy.y = -current.x * kmodes.y;
    sz.x = current.y * kmodes.z;
    sz.y = -current.x * kmodes.z;
    outSx[idx] = sx;
    outSy[idx] = sy;
    outSz[idx] = sz;
}
References deviceFFT_t, HACCGPM::parallel::get_global_index(), HACCGPM::parallel::get_kmodes(), and world_rank.