HACC_GPM: /home/hqureshi/HACC_GPM/src/particle_transfer/kernels.hpp File Reference
kernels.hpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include "haccgpm.hpp"
Functions
CPUTimer_t launch_count_buffer (int *d_ns, float4 *d_pos, int n_particles, int ng, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_load_buffer (float4 *d_swap, int *d_starts, int *d_count, float4 *d_pos, float4 *d_vel, int n_particles, int ng, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_combine_particles (float4 *d_pos, float4 *d_vel, float4 *d_swap, int *d_count, int n_new, int n_particles, int world_rank, int numBlocks, int blockSize, int calls)
Function Documentation
launch_combine_particles()
CPUTimer_t launch_combine_particles (float4 * d_pos, float4 * d_vel, float4 * d_swap, int * d_count, int n_new, int n_particles, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 17 of file combine_particles.cu.
{
    getIndent(calls);
    return InvokeGPUKernelParallel(combineParticles,numBlocks,blockSize,d_pos,d_vel,d_swap,d_count,n_new,n_particles);
}
References combineParticles(), do_return(), getIndent, and InvokeGPUKernelParallel.
Referenced by HACCGPM::parallel::insertParticles().
launch_count_buffer()
CPUTimer_t launch_count_buffer (int * d_ns, float4 * d_pos, int n_particles, int ng, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 28 of file count_buffer.cu.
{
    getIndent(calls);
    return InvokeGPUKernelParallel(init_count_buffer,numBlocks,blockSize,d_ns,d_pos,n_particles,ng,local_grid_size,local_coords,dims);
}
References do_return(), getIndent, init_count_buffer(), and InvokeGPUKernelParallel.
Referenced by HACCGPM::parallel::LoadIntoBuffers().
launch_load_buffer()
CPUTimer_t launch_load_buffer (float4 * d_swap, int * d_starts, int * d_count, float4 * d_pos, float4 * d_vel, int n_particles, int ng, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 47 of file load_buffer.cu.
{
    getIndent(calls);
    return InvokeGPUKernelParallel(init_load_buffer,numBlocks,blockSize,d_swap,d_starts,d_count,d_pos,d_vel,n_particles,ng,local_grid_size,local_coords,dims,world_rank);
}
References do_return(), getIndent, init_load_buffer(), InvokeGPUKernelParallel, and world_rank.
Referenced by HACCGPM::parallel::LoadIntoBuffers().