HACC_GPM: /home/hqureshi/HACC_GPM/src/initial_conditions/cuda/rng_initializer.cu File Reference
rng_initializer.cu File Reference
#include "../ic_kernels.hpp"
#include <curand.h>
#include <curand_kernel.h>
Functions
__global__ void initRNG (curandState *state, int seed)
__global__ void initRNG (curandState *state, int seed, int nlocal, int ng, int3 local_grid_size, int3 local_coords)
__global__ void GenerateRealRandom (curandState *state, deviceFFT_t *__restrict grid, int nlocal)
void launch_generate_rng (deviceFFT_t *d_grid1, int ng, int seed, int numBlocks, int blockSize, int calls)
void launch_generate_rng (deviceFFT_t *d_grid1, int ng, int seed, int nlocal, int3 local_grid_size, int3 local_coords, int world_rank, int numBlocks, int blockSize, int calls)
Function Documentation
GenerateRealRandom()
__global__ void GenerateRealRandom (curandState * state, deviceFFT_t *__restrict grid, int nlocal)
Definition at line 22 of file rng_initializer.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= nlocal)return;
    hostFFT_t amp = curand_normal_double(state + idx);
    deviceFFT_t out;
    out.x = amp;
    out.y = 0;
    grid[idx] = out;
}
References deviceFFT_t, do_return(), and hostFFT_t.
Referenced by launch_generate_rng(), and launch_generate_rng().
initRNG() [1/2]
__global__ void initRNG (curandState * state, int seed)
Definition at line 5 of file rng_initializer.cu.
{
  int idx = threadIdx.x+blockDim.x*blockIdx.x;
  curand_init(seed, idx, 0, &state[idx]);
}
References do_return().
Referenced by launch_generate_rng(), and launch_generate_rng().
initRNG() [2/2]
__global__ void initRNG (curandState * state, int seed, int nlocal, int ng, int3 local_grid_size, int3 local_coords)
Definition at line 12 of file rng_initializer.cu.
{
  int idx = threadIdx.x+blockDim.x*blockIdx.x;
  if (idx >= nlocal)return;
  int3 idx3d = HACCGPM::parallel::get_global_index(idx,ng,local_grid_size,local_coords);
  int global_idx = idx3d.x * ng * ng + idx3d.y * ng + idx3d.z;
  curand_init(seed, global_idx, 0, &state[idx]);
}
References do_return(), and HACCGPM::parallel::get_global_index().
launch_generate_rng() [1/2]
void launch_generate_rng (deviceFFT_t * d_grid1, int ng, int seed, int nlocal, int3 local_grid_size, int3 local_coords, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 40 of file rng_initializer.cu.
{
    getIndent(calls);
    curandState* rngState; cudaCall(cudaMalloc,&rngState,sizeof(curandState)*nlocal);
    InvokeGPUKernelParallel(initRNG,numBlocks,blockSize,rngState,seed,nlocal,ng,local_grid_size,local_coords);
    InvokeGPUKernelParallel(GenerateRealRandom,numBlocks,blockSize,rngState,d_grid1,nlocal);
    cudaCall(cudaFree,rngState);
}
References cudaCall, do_return(), GenerateRealRandom(), getIndent, initRNG(), and InvokeGPUKernelParallel.
launch_generate_rng() [2/2]
void launch_generate_rng (deviceFFT_t * d_grid1, int ng, int seed, int numBlocks, int blockSize, int calls)
Definition at line 32 of file rng_initializer.cu.
{
    getIndent(calls);
    curandState* rngState; cudaCall(cudaMalloc,&rngState,sizeof(curandState)*ng*ng*ng);
    InvokeGPUKernel(initRNG,numBlocks,blockSize,rngState,seed);
    InvokeGPUKernel(GenerateRealRandom,numBlocks,blockSize,rngState,d_grid1,ng*ng*ng);
    cudaCall(cudaFree,rngState);
}
References cudaCall, do_return(), GenerateRealRandom(), getIndent, initRNG(), and InvokeGPUKernel.
Referenced by GenerateFourierAmplitudes(), and GenerateFourierAmplitudesParallel().