HACC_GPM: /home/hqureshi/HACC_GPM/src/pm_solver/solver.cu File Reference
solver.cu File Reference
#include <stdlib.h>
#include <stdio.h>
#include "haccgpm.hpp"
Macros
#define VerboseSolver
Functions
__device__ __forceinline__ float get_gradient (float kmode)
__global__ void kspace_solve (deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens)
__global__ void kspace_solve_gradient (deviceFFT_t *__restrict d_x, deviceFFT_t *__restrict d_y, deviceFFT_t *__restrict d_z, const deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens, float b1, float b2, int ng)
__global__ void kspace_solve_gradient_parallel (deviceFFT_t *__restrict d_x, deviceFFT_t *__restrict d_y, deviceFFT_t *__restrict d_z, const deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens, float b1, float b2, int ng, int nlocal, int overload, int3 local_grid_size, int3 local_coords)
__global__ void combine (float4 *__restrict out, const deviceFFT_t *__restrict d_x, const deviceFFT_t *__restrict d_y, const deviceFFT_t *__restrict d_z)
__global__ void combine_parallel (float4 *__restrict out, const deviceFFT_t *__restrict d_x, const deviceFFT_t *__restrict d_y, const deviceFFT_t *__restrict d_z, int3 local_grid_size, int3 local_coords, int overload, int nlocal, int ng)
Macro Definition Documentation
VerboseSolver
#define VerboseSolver
Definition at line 5 of file solver.cu.
Function Documentation
combine()
__global__ void combine (float4 *__restrict out, const deviceFFT_t *__restrict d_x, const deviceFFT_t *__restrict d_y, const deviceFFT_t *__restrict d_z)
Definition at line 96 of file solver.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    deviceFFT_t x = __ldg(&d_x[idx]);
    deviceFFT_t y = __ldg(&d_y[idx]);
    deviceFFT_t z = __ldg(&d_z[idx]);
    float4 this_out;
    this_out.x = x.x;
    this_out.y = y.x;
    this_out.z = z.x;
    out[idx] = this_out;
}
References deviceFFT_t, and do_return().
Referenced by HACCGPM::serial::SolveGradient().
combine_parallel()
__global__ void combine_parallel (float4 *__restrict out, const deviceFFT_t *__restrict d_x, const deviceFFT_t *__restrict d_y, const deviceFFT_t *__restrict d_z, int3 local_grid_size, int3 local_coords, int overload, int nlocal, int ng)
Definition at line 110 of file solver.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    deviceFFT_t x = __ldg(&d_x[idx]);
    deviceFFT_t y = __ldg(&d_y[idx]);
    deviceFFT_t z = __ldg(&d_z[idx]);
    int3 globalIdx3d = HACCGPM::parallel::get_global_index(idx,ng,local_grid_size,local_coords);
    int globalIdx = globalIdx3d.x * ng * ng + globalIdx3d.y * ng + globalIdx3d.z;
    float4 this_out;
    this_out.x = x.x;
    this_out.y = y.x;
    this_out.z = z.x;
    this_out.w = globalIdx;
    int3 rhoIdx3d = HACCGPM::parallel::get_local_index(idx,local_grid_size.x,local_grid_size.y,local_grid_size.z);
    rhoIdx3d.x += overload;
    rhoIdx3d.y += overload;
    rhoIdx3d.z += overload;
    int3 overload_dims = make_int3(local_grid_size.x + 2*overload, local_grid_size.y + 2*overload, local_grid_size.z + 2*overload);
    int rhoIdx = rhoIdx3d.x * overload_dims.y * overload_dims.z + rhoIdx3d.y * overload_dims.z + rhoIdx3d.z;
    out[rhoIdx] = this_out;
}
References deviceFFT_t, do_return(), HACCGPM::parallel::get_global_index(), and HACCGPM::parallel::get_local_index().
Referenced by HACCGPM::parallel::SolveGradient().
get_gradient()
__device__ __forceinline__ float get_gradient (float kmode)
Definition at line 7 of file solver.cu.
{
    return sinf(kmode);
}
References do_return().
Referenced by kspace_solve_gradient(), and kspace_solve_gradient_parallel().
kspace_solve()
__global__ void kspace_solve (deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens)
Definition at line 11 of file solver.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    hostFFT_t greens = __ldg(&d_greens[idx]);
    deviceFFT_t rho = __ldg(&d_rho[idx]);
    rho.x *= greens;
    rho.y *= greens;
    d_rho[idx] = rho;
}
References deviceFFT_t, do_return(), and hostFFT_t.
Referenced by HACCGPM::serial::Solve().
kspace_solve_gradient()
__global__ void kspace_solve_gradient (deviceFFT_t *__restrict d_x, deviceFFT_t *__restrict d_y, deviceFFT_t *__restrict d_z, const deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens, float b1, float b2, int ng)
Definition at line 21 of file solver.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    double d = ((2*M_PI)/(((double)(ng))));
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    float3 kmodes = HACCGPM::get_kmodes(idx3d,ng,d);
    hostFFT_t greens = __ldg(&d_greens[idx]);
    float3 c;
    c.x = -get_gradient(kmodes.x) * greens;
    c.y = -get_gradient(kmodes.y) * greens;
    c.z = -get_gradient(kmodes.z) * greens;
    deviceFFT_t rho = __ldg(&d_rho[idx]);
    deviceFFT_t out_x;
    out_x.x = -c.x * rho.y;
    out_x.y = c.x * rho.x;
    d_x[idx] = out_x;
    deviceFFT_t out_y;
    out_y.x = -c.y * rho.y;
    out_y.y = c.y * rho.x;
    d_y[idx] = out_y;
    deviceFFT_t out_z;
    out_z.x = -c.z * rho.y;
    out_z.y = c.z * rho.x;
    d_z[idx] = out_z;
}
References deviceFFT_t, do_return(), get_gradient(), HACCGPM::serial::get_index(), HACCGPM::get_kmodes(), and hostFFT_t.
Referenced by HACCGPM::serial::SolveGradient().
kspace_solve_gradient_parallel()
__global__ void kspace_solve_gradient_parallel (deviceFFT_t *__restrict d_x, deviceFFT_t *__restrict d_y, deviceFFT_t *__restrict d_z, const deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens, float b1, float b2, int ng, int nlocal, int overload, int3 local_grid_size, int3 local_coords)
Definition at line 57 of file solver.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    double d = ((2*M_PI)/(((double)(ng))));
    int3 idx3d = HACCGPM::parallel::get_global_index(idx,ng,local_grid_size,local_coords);
    float3 kmodes = HACCGPM::get_kmodes(idx3d,ng,d);
    hostFFT_t greens = __ldg(&d_greens[idx]);
    float3 c;
    c.x = -get_gradient(kmodes.x) * greens;
    c.y = -get_gradient(kmodes.y) * greens;
    c.z = -get_gradient(kmodes.z) * greens;
    deviceFFT_t rho = __ldg(&d_rho[idx]);
    deviceFFT_t out_x;
    out_x.x = -c.x * rho.y;
    out_x.y = c.x * rho.x;
    d_x[idx] = out_x;
    deviceFFT_t out_y;
    out_y.x = -c.y * rho.y;
    out_y.y = c.y * rho.x;
    d_y[idx] = out_y;
    deviceFFT_t out_z;
    out_z.x = -c.z * rho.y;
    out_z.y = c.z * rho.x;
    d_z[idx] = out_z;
}
References deviceFFT_t, do_return(), HACCGPM::parallel::get_global_index(), get_gradient(), HACCGPM::get_kmodes(), and hostFFT_t.
Referenced by HACCGPM::parallel::SolveGradient().