HACC_GPM: /home/hqureshi/HACC_GPM/src/haccgpm.hpp File Reference
haccgpm.hpp File Reference
#include <cuda_runtime.h>
#include <cufft.h>
#include <stdio.h>
#include <time.h>
#include <sys/time.h>
#include <cstring>
#include "pycosmotools.hpp"
Classes
struct HACCGPM::Params
class HACCGPM::Timestepper
class HACCGPM::CosmoClass
class HACCGPM::parallel::MemoryManager
class HACCGPM::parallel::GridExchange
class HACCGPM::serial::MemoryManager
Namespaces
namespace HACCGPM
namespace HACCGPM::parallel
namespace HACCGPM::serial
Macros
#define USECPSEC 1000000ULL
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define deviceFFT_t cufftDoubleComplex
#define hostFFT_t double
#define getIndent(calls) char indent[50] = ""; for (int i = 0; i < (calls*6); i++){strcat(indent," ");}
#define gpuErrchk(ans) { gpuAssert((ans), __FILE__, __LINE__); }
#define cudaCall(func, ...) if (func(__VA_ARGS__) != cudaSuccess)printf("Error >> %s\n", cudaGetErrorString(cudaGetLastError()));cudaDeviceSynchronize()
#define InvokeGPUKernel(func, numBlocks, blockSize, ...) ({CPUTimer_t start = CPUTimer();func<<<numBlocks,blockSize>>>(__VA_ARGS__);gpuErrchk(cudaPeekAtLastError());gpuErrchk(cudaDeviceSynchronize());CPUTimer_t end = CPUTimer();CPUTimer_t t = end-start; t;})
#define InvokeGPUKernelParallel(func, numBlocks, blockSize, ...) ({CPUTimer_t start = CPUTimer();func<<<numBlocks,blockSize>>>(__VA_ARGS__);gpuErrchk(cudaPeekAtLastError());gpuErrchk(cudaDeviceSynchronize());CPUTimer_t end = CPUTimer();CPUTimer_t t = end-start; t;})
#define hostFFT_t double
#define deviceFFT_t cufftDoubleComplex
#define MAX_STEPS 1000
#define HostMalloc(ptr, sz) cudaCall(cudaMallocHost,ptr,sz)
#define HostFree(ptr) cudaCall(cudaFreeHost,ptr)
Typedefs
typedef unsigned long long CPUTimer_t
Functions
unsigned long long CPUTimer (unsigned long long start=0)
void gpuAssert (cudaError_t code, const char *file, int line, bool abort=true)
__forceinline__ __host__ __device__ float3 operator* (int3 a, float s)
Params HACCGPM::read_params (const char *fname)
__device__ __forceinline__ float3 HACCGPM::get_kmodes (int3 idx3d, int ng, double d)
__device__ __forceinline__ int3 HACCGPM::parallel::get_local_index (int idx, int nx, int ny, int nz)
__device__ __forceinline__ int3 HACCGPM::parallel::get_global_index (int idx, int ng, int3 local_dims, int3 local_coords)
void HACCGPM::parallel::init_swfft (HACCGPM::Params &params)
void HACCGPM::parallel::finalize_swfft ()
void HACCGPM::parallel::forward_fft (deviceFFT_t *d_grid, int ng, int calls=0)
void HACCGPM::parallel::backward_fft (deviceFFT_t *d_grid, int ng, int calls=0)
void HACCGPM::parallel::timing_stats (CPUTimer_t t, CPUTimer_t *mint, CPUTimer_t *maxt, CPUTimer_t *meant)
void HACCGPM::parallel::printTimingStats (const char *preamble, double dt)
CPUTimer_t HACCGPM::parallel::LoadIntoBuffers (float4 *h_swap, int *n_swaps, int *h_starts, float4 *d_pos, float4 *d_vel, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int n_particles, int ng, int blockSize, int world_rank, int world_size, int calls=0)
void HACCGPM::parallel::TransferParticles (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, int calls=0)
CPUTimer_t HACCGPM::parallel::insertParticles (float4 *d_pos, float4 *d_vel, float4 *h_swap, int n_new, int n_particles, int blockSize, int world_rank, int calls=0)
void HACCGPM::parallel::GenerateDisplacementIC (HACCGPM::parallel::MemoryManager &mem, HACCGPM::CosmoClass &cosmo, HACCGPM::Params &params, HACCGPM::Timestepper &ts, int calls=0)
void HACCGPM::parallel::CIC (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, int calls=0)
void HACCGPM::parallel::CIC (deviceFFT_t *d_grid, float *d_extragrid, float4 *d_pos, int ng, int n_particles, int3 local_grid_size, int3 local_coords, int3 dims, int blockSize, int world_rank, int world_size, int overload, int calls=0)
void HACCGPM::parallel::GetPowerSpectrum (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, int nbins, const char *fname, int calls=0)
void HACCGPM::parallel::sendPower (int *binCounts, double *binVals, int nbins, int world_rank, int world_size, int calls=0)
void HACCGPM::parallel::InitGreens (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, int calls=0)
void HACCGPM::parallel::UpdatePositions (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, HACCGPM::Timestepper ts, float frac, int calls=0)
int HACCGPM::parallel::UpdatePositions (float4 *d_pos, float4 *d_vel, HACCGPM::Timestepper ts, float frac, int ng, int n_particles, int3 local_grid_size, int overload, int blockSize, int world_rank, int calls=0)
void HACCGPM::parallel::UpdateVelocities (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, HACCGPM::Timestepper ts, int calls=0)
void HACCGPM::parallel::UpdateVelocities (float4 *d_vel, float4 *d_grad, float4 *d_pos, HACCGPM::Timestepper ts, int n_particles, int ng, int overload, int3 local_grid_size, int blockSize, int world_rank, int calls=0)
void HACCGPM::parallel::SolveGradient (HACCGPM::Params &params, HACCGPM::parallel::MemoryManager &mem, int calls=0)
void HACCGPM::parallel::SolveGradient (float4 *d_grad, deviceFFT_t *d_rho, hostFFT_t *d_greens, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, int ng, int n_particles, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int world_size, int overload, int blockSize, int calls=0)
void HACCGPM::parallel::printTransferTimes (int world_rank)
void HACCGPM::parallel::printCICTimes (int world_rank)
void HACCGPM::parallel::printTransferBytes (int world_rank)
void HACCGPM::parallel::printFFTStats (int world_rank)
void HACCGPM::parallel::printGridExchangeTimes (int world_rank)
void HACCGPM::parallel::printGridExchangeBytes (int world_rank)
__device__ __forceinline__ int3 HACCGPM::serial::get_index (int idx, int ng)
void HACCGPM::serial::UpdatePositions (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, HACCGPM::Timestepper ts, float frac, int calls=0)
void HACCGPM::serial::UpdatePositions (float4 *d_pos, float4 *d_vel, HACCGPM::Timestepper ts, float frac, int ng, int blockSize, int calls=0)
void HACCGPM::serial::UpdateVelocities (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, HACCGPM::Timestepper ts, int calls=0)
void HACCGPM::serial::UpdateVelocities (float4 *d_vel, float4 *d_grad, float4 *d_pos, HACCGPM::Timestepper ts, int ng, int blockSize, int calls=0)
void HACCGPM::serial::CIC (deviceFFT_t *d_grid, float *d_temp, float4 *d_pos, int ng, int blockSize, int calls=0)
void HACCGPM::serial::CIC (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, int calls=0)
double HACCGPM::serial::get_fscal (double m_aa, double m_adot, double m_omega_cb)
double HACCGPM::serial::get_adot (double m_aa, double m_w, double m_wa, double m_omega_cb, double m_omega_radiation, double m_f_nu_massless, double m_f_nu_massive, double m_omega_matter, double m_omega_nu)
void HACCGPM::serial::writeOutput (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, char *fname, int calls=0)
void HACCGPM::serial::writeOutput (char *fname, float4 *d_pos, float4 *d_vel, int ng, int calls=0)
void HACCGPM::serial::GetPowerSpectrum (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, int nbins, const char *fname, int calls=0)
void HACCGPM::serial::GenerateDisplacementIC (HACCGPM::serial::MemoryManager &mem, HACCGPM::CosmoClass &cosmo, HACCGPM::Params &params, HACCGPM::Timestepper &ts, int calls=0)
void HACCGPM::serial::Solve (deviceFFT_t *d_rho, hostFFT_t *d_greens, int ng, int blockSize, int calls=0)
void HACCGPM::serial::SolveGradient (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, int calls=0)
void HACCGPM::serial::SolveGradient (float4 *d_grad, deviceFFT_t *d_rho, hostFFT_t *d_greens, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, int ng, int blockSize, int calls=0)
void HACCGPM::serial::InitGreens (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, int calls=0)
void HACCGPM::serial::forward_fft (deviceFFT_t *data, deviceFFT_t *out, int ng, int calls=0)
void HACCGPM::serial::forward_fft (deviceFFT_t *data, int ng, int calls=0)
void HACCGPM::serial::backward_fft (deviceFFT_t *data, deviceFFT_t *out, int ng, int calls=0)
void HACCGPM::serial::backward_fft (deviceFFT_t *data, int ng, int calls=0)
void HACCGPM::serial::fft_cache_plan (int ng)
void HACCGPM::serial::printCICTimes ()
void HACCGPM::serial::printFFTTimes ()
void HACCGPM::serial::printPowerTimes ()
void HACCGPM::serial::printOutputTimes ()
void HACCGPM::serial::PyAnalysis (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, HACCGPM::Timestepper &ts, PyCosmoTools &pytools, int step)
Macro Definition Documentation
cudaCall
#define cudaCall (func, ...) if (func(__VA_ARGS__) != cudaSuccess)printf("Error >> %s\n", cudaGetErrorString(cudaGetLastError()));cudaDeviceSynchronize()
Definition at line 42 of file haccgpm.hpp.
deviceFFT_t [1/2]
#define deviceFFT_t cufftDoubleComplex
Definition at line 26 of file haccgpm.hpp.
deviceFFT_t [2/2]
#define deviceFFT_t cufftDoubleComplex
Definition at line 26 of file haccgpm.hpp.
getIndent
#define getIndent (calls) char indent[50] = ""; for (int i = 0; i < (calls*6); i++){strcat(indent," ");}
Definition at line 29 of file haccgpm.hpp.
gpuErrchk
#define gpuErrchk (ans) { gpuAssert((ans), __FILE__, __LINE__); }
Definition at line 31 of file haccgpm.hpp.
hostFFT_t [1/2]
#define hostFFT_t double
Definition at line 27 of file haccgpm.hpp.
hostFFT_t [2/2]
#define hostFFT_t double
Definition at line 27 of file haccgpm.hpp.
HostFree
#define HostFree (ptr) cudaCall(cudaFreeHost,ptr)
Definition at line 64 of file haccgpm.hpp.
HostMalloc
#define HostMalloc (ptr, sz) cudaCall(cudaMallocHost,ptr,sz)
Definition at line 63 of file haccgpm.hpp.
InvokeGPUKernel
#define InvokeGPUKernel (func, numBlocks, blockSize, ...) ({CPUTimer_t start = CPUTimer();func<<<numBlocks,blockSize>>>(__VA_ARGS__);gpuErrchk(cudaPeekAtLastError());gpuErrchk(cudaDeviceSynchronize());CPUTimer_t end = CPUTimer();CPUTimer_t t = end-start; t;})
Definition at line 53 of file haccgpm.hpp.
InvokeGPUKernelParallel
#define InvokeGPUKernelParallel (func, numBlocks, blockSize, ...) ({CPUTimer_t start = CPUTimer();func<<<numBlocks,blockSize>>>(__VA_ARGS__);gpuErrchk(cudaPeekAtLastError());gpuErrchk(cudaDeviceSynchronize());CPUTimer_t end = CPUTimer();CPUTimer_t t = end-start; t;})
Definition at line 54 of file haccgpm.hpp.
MAX_STEPS
#define MAX_STEPS 1000
Definition at line 61 of file haccgpm.hpp.
STRINGIFY
#define STRINGIFY (x) #x
Definition at line 14 of file haccgpm.hpp.
TOSTRING
#define TOSTRING (x) STRINGIFY(x)
Definition at line 15 of file haccgpm.hpp.
USECPSEC
#define USECPSEC 1000000ULL
Definition at line 12 of file haccgpm.hpp.
Typedef Documentation
CPUTimer_t
typedef unsigned long long CPUTimer_t
Definition at line 17 of file haccgpm.hpp.
Function Documentation
CPUTimer()
unsigned long long CPUTimer (unsigned long long start = 0) inline
Definition at line 19 of file haccgpm.hpp.
{
  timeval tv;
  gettimeofday(&tv, 0);
  return ((tv.tv_sec*USECPSEC)+tv.tv_usec)-start;
}
References do_return(), and USECPSEC.
Referenced by HACCGPM::parallel::backward_fft(), HACCGPM::serial::backward_fft(), HACCGPM::serial::backward_fft(), HACCGPM::parallel::CIC(), HACCGPM::serial::CIC(), do_return(), HACCGPM::parallel::forward_fft(), HACCGPM::serial::forward_fft(), HACCGPM::serial::forward_fft(), HACCGPM::parallel::GetPowerSpectrum(), HACCGPM::serial::GetPowerSpectrum(), HACCGPM::parallel::insertParticles(), HACCGPM::parallel::LoadIntoBuffers(), parallel(), HACCGPM::parallel::GridExchange::resolve(), serial(), HACCGPM::parallel::TransferParticles(), HACCGPM::serial::UpdatePositions(), HACCGPM::parallel::UpdatePositions(), HACCGPM::parallel::UpdateVelocities(), HACCGPM::serial::UpdateVelocities(), and HACCGPM::serial::writeOutput().
gpuAssert()
void gpuAssert (cudaError_t code, const char * file, int line, bool abort = true) inline
Definition at line 32 of file haccgpm.hpp.
{
   if (code != cudaSuccess)
   {
      fprintf(stderr,"GPUassert: %s %s %d\n", cudaGetErrorString(code), file, line);
      if (abort) exit(code);
   } else{
   }
}
References do_return().
operator*()
__forceinline__ __host__ __device__ float3 operator* (int3 a, float s)
Definition at line 66 of file haccgpm.hpp.
{
    return make_float3(a.x * s, a.y * s, a.z * s);
}
References do_return().