HACC_GPM: generate_ipk Namespace Reference
generate_ipk Namespace Reference
Functions
read_params (fname)
hacc2camb (params)
hacc2cosmology (params)
initcambpy ()
get_pk (z, k, fname)
D_plus (OmM, OmL)
z2a (z)
a2z (a)
da_dtau (a, OmM, OmL)
da_dtau__3 (a, OmM, OmL)
int_1_da_dtau_3 (a, OmM, OmL)
delta (a, OmM, OmL)
dotDelta (a, OmM, OmL)
f (z, OmM, OmL)
get_delta_and_dotDelta (z, z1, fname)
Variables
int k_min = 0
int k_max = 1000
int k_bins = 20000
int z = 200
str fname = ""
outfile = sys.argv[2]
params = read_params(fname)
list quantities = ["OMEGA_CDM","DEUT","OMEGA_NU","HUBBLE","SS8","NS","W_DE","WA_DE","T_CMB","N_EFF_MASSLESS","N_EFF_MASSIVE","Z_IN"]
ks = np.linspace(k_min,k_max,k_bins).astype(np.float64)
list header = [k_min,k_max,k_bins,ks[1]-ks[0]]
pk = get_pk(z,ks,fname)
out = np.zeros((len(pk) + 20),dtype=np.float64)
Function Documentation
a2z()
generate_ipk.a2z (a)
Definition at line 110 of file generate_ipk.py.
def a2z(a):
    return (1/a) - 1
D_plus()
generate_ipk.D_plus (OmM, OmL)
Definition at line 104 of file generate_ipk.py.
def D_plus(OmM,OmL):
    return (5/2)*OmM*(1/(OmM**(4/7) - OmL + (1+0.5*OmM)*(1+(1/70)*OmL)))
da_dtau()
generate_ipk.da_dtau (a, OmM, OmL)
Definition at line 113 of file generate_ipk.py.
def da_dtau(a,OmM,OmL):
    da_dtau_2 = 1+OmM*((1/a)-1) + OmL*((a**2) - 1)
    return np.sqrt(da_dtau_2)
Referenced by delta().
da_dtau__3()
generate_ipk.da_dtau__3 (a, OmM, OmL)
Definition at line 117 of file generate_ipk.py.
def da_dtau__3(a,OmM,OmL):
    da_dtau_2 = 1+OmM*((1/a)-1) + OmL*((a**2) - 1)
    return 1/(np.sqrt(da_dtau_2)**3)
delta()
generate_ipk.delta (a, OmM, OmL)
Definition at line 124 of file generate_ipk.py.
def delta(a,OmM,OmL):
    integral = int_1_da_dtau_3(a,OmM,OmL)
    diff = da_dtau(a,OmM,OmL)
    mul = (5*OmM)/(2*a)
    return mul*diff*integral[0]
References da_dtau(), and int_1_da_dtau_3().
Referenced by get_delta_and_dotDelta().
dotDelta()
generate_ipk.dotDelta (a, OmM, OmL)
Definition at line 130 of file generate_ipk.py.
def dotDelta(a,OmM,OmL):
    return scipy.misc.derivative(delta,a,1e-3,args=(OmM,OmL))
Referenced by get_delta_and_dotDelta().
f()
generate_ipk.f (z, OmM, OmL)
Definition at line 133 of file generate_ipk.py.
def f(z,OmM,OmL):
    top = OmM*((1+z)**3)
    bottom = OmM*((1+z)**3) - (OmM + OmL - 1)*((1+z)**2) + OmL
    return (top/bottom)**(4/7)
get_delta_and_dotDelta()
generate_ipk.get_delta_and_dotDelta (z, z1, fname)
Definition at line 138 of file generate_ipk.py.
def get_delta_and_dotDelta(z,z1,fname):
    haccparams = read_params(fname)
    cambparams,ns = hacc2camb(haccparams)
    pars = camb.CAMBparams()
    pars.set_cosmology(**cambparams)
    OmB = pars.ombh2 / (pars.h**2)
    OmC = pars.omch2 / (pars.h**2)
    OmNu = pars.omnuh2 / (pars.h**2)
    OmK = pars.omk
    OmM = OmB + OmC
    OmL = 1 - (OmB + OmC + OmNu + OmK)
    d = delta(z2a(z),OmM,OmL)
    d_dot = dotDelta(z2a(z1),OmM,OmL)
    return np.array([d,d_dot],dtype=np.float64)
References delta(), dotDelta(), hacc2camb(), read_params(), and z2a().
get_pk()
generate_ipk.get_pk (z, k, fname)
Definition at line 85 of file generate_ipk.py.
def get_pk(z,k,fname):
    #print('FNAME:',fname)
    haccparams = read_params(fname)
    cambparams,ns = hacc2camb(haccparams)
    pars = camb.CAMBparams()
    pars.set_cosmology(**cambparams)
    pars.InitPower.set_params(ns=ns)
    pars.set_matter_power(redshifts=[z], kmax=np.max(k))
    results = camb.get_results(pars)
    pars.NonLinear = model.NonLinear_none
    PK = results.get_matter_power_interpolator()
    idx = k==0
    k[idx] = 1
    out = PK.P(z,k)
    #out *= ((ng*ng*ng)/(rl*rl*rl))
    out[idx] = 0
    return out
References hacc2camb(), and read_params().
hacc2camb()
generate_ipk.hacc2camb (params)
Definition at line 34 of file generate_ipk.py.
def hacc2camb(params):
    h = params['HUBBLE']
    Om_c = params['OMEGA_CDM']
    Om_b = params['DEUT'] / (h**2)
    Om_nu = params['OMEGA_NU']
    n_eff_massless = params['N_EFF_MASSLESS']
    n_eff_massive = params['N_EFF_MASSIVE']
    w_0 = params['W_DE']
    w_a = params['WA_DE']
    T_cmb = params['T_CMB']
    n_s = params['NS']
    omch2 = Om_c * (h**2)
    ombh2 = Om_b * (h**2)
    omnuh2 = Om_nu * (h**2)
    h = h * 100
    return {'H0': h,'ombh2': ombh2,'omch2':omch2}, n_s
Referenced by get_delta_and_dotDelta(), and get_pk().
hacc2cosmology()
generate_ipk.hacc2cosmology (params)
Definition at line 52 of file generate_ipk.py.
def hacc2cosmology(params):
    h = params['HUBBLE']
    Om_c = params['OMEGA_CDM']
    Om_b = params['DEUT'] / (h**2)
    Om_nu = params['OMEGA_NU']
    n_eff_massless = params['N_EFF_MASSLESS']
    n_eff_massive = params['N_EFF_MASSIVE']
    w_0 = params['W_DE']
    w_a = params['WA_DE']
    T_cmb = params['T_CMB']
    n_s = params['NS']
    omch2 = Om_c * (h**2)
    ombh2 = Om_b * (h**2)
    omnuh2 = Om_nu * (h**2)
    h = h * 100
    return omch2,ombh2,omnuh2
initcambpy()
generate_ipk.initcambpy ()
Definition at line 70 of file generate_ipk.py.
def initcambpy():
    fname = 'params'
    #global PK
    #print('Initializing Camb')
    #haccparams = read_params(fname)
    #cambparams,ns = hacc2camb(haccparams)
    #pars = camb.CAMBparams()
    #pars.set_cosmology(**cambparams)
    #pars.InitPower.set_params(ns=ns)
    #pars.set_matter_power(redshifts=[200], kmax=10.0)
    #results = camb.get_results(pars)
    #pars.NonLinear = model.NonLinear_none
    #PK = results.get_matter_power_interpolator()
    return None
int_1_da_dtau_3()
generate_ipk.int_1_da_dtau_3 (a, OmM, OmL)
Definition at line 121 of file generate_ipk.py.
def int_1_da_dtau_3(a,OmM,OmL):
    return scipy.integrate.quad(da_dtau__3,0,a,(OmM,OmL))
Referenced by delta().
read_params()
generate_ipk.read_params (fname)
Definition at line 13 of file generate_ipk.py.
def read_params(fname):
    with open(fname,'r') as f:
        raw = f.read().splitlines()
    data = {}
    for i in raw:
        if (len(i.strip()) == 0) or (i.strip().startswith('#')):
            pass
        else:
            try:
                name,val = i.split()
                data[name] = float(val)
            except:
                try:
                    name,val = i.split()
                    data[name] = val
                except:
                    pass
    return data
Referenced by get_delta_and_dotDelta(), and get_pk().
z2a()
generate_ipk.z2a (z)
Definition at line 107 of file generate_ipk.py.
def z2a(z):
    return 1/(1+z)
Referenced by get_delta_and_dotDelta().
Variable Documentation
fname
generate_ipk.fname = ""
Definition at line 158 of file generate_ipk.py.
header
generate_ipk.header = [k_min,k_max,k_bins,ks[1]-ks[0]]
Definition at line 193 of file generate_ipk.py.
k_bins
generate_ipk.k_bins = 20000
Definition at line 156 of file generate_ipk.py.
k_max
generate_ipk.k_max = 1000
Definition at line 155 of file generate_ipk.py.
k_min
generate_ipk.k_min = 0
Definition at line 154 of file generate_ipk.py.
ks
generate_ipk.ks = np.linspace(k_min,k_max,k_bins).astype(np.float64)
Definition at line 192 of file generate_ipk.py.
out
generate_ipk.out = np.zeros((len(pk) + 20),dtype=np.float64)
Definition at line 198 of file generate_ipk.py.
outfile
generate_ipk.outfile = sys.argv[2]
Definition at line 164 of file generate_ipk.py.
params
generate_ipk.params = read_params(fname)
Definition at line 182 of file generate_ipk.py.
pk
generate_ipk.pk = get_pk(z,ks,fname)
Definition at line 197 of file generate_ipk.py.
quantities
list generate_ipk.quantities = ["OMEGA_CDM","DEUT","OMEGA_NU","HUBBLE","SS8","NS","W_DE","WA_DE","T_CMB","N_EFF_MASSLESS","N_EFF_MASSIVE","Z_IN"]
Definition at line 183 of file generate_ipk.py.
z
generate_ipk.z = 200
Definition at line 157 of file generate_ipk.py.