HACC_GPM: /home/hqureshi/HACC_GPM/src/initial_conditions/cuda/transform_density_field_initializer.cu File Reference
transform_density_field_initializer.cu File Reference
#include "../ic_kernels.hpp"
Functions
__global__ void transformDensityField (const deviceFFT_t *__restrict oldGrid, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double rl, double a, int ng)
__global__ void transformDensityField (const deviceFFT_t *__restrict oldGrid, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double rl, double a, int ng, int nlocal, int world_rank, int3 local_grid_size, int3 local_coords, int3 dims)
void launch_transform_density_field (deviceFFT_t *d_grid, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, double delta, double rl, double z_ini, int ng, int numBlocks, int blockSize, int calls)
void launch_transform_density_field (deviceFFT_t *d_grid, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, double delta, double rl, double z_ini, int ng, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int numBlocks, int blockSize, int calls)
Function Documentation
launch_transform_density_field() [1/2]
void launch_transform_density_field (deviceFFT_t * d_grid, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, double delta, double rl, double z_ini, int ng, int nlocal, int3 local_grid_size, int3 local_coords, int3 dims, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 88 of file transform_density_field_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernelParallel(transformDensityField,numBlocks,blockSize,d_grid,d_x,d_y,d_z,delta,rl,1/(1+z_ini),ng,nlocal,world_rank,local_grid_size,local_coords,dims);
}
References do_return(), getIndent, InvokeGPUKernelParallel, transformDensityField(), and world_rank.
launch_transform_density_field() [2/2]
void launch_transform_density_field (deviceFFT_t * d_grid, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, double delta, double rl, double z_ini, int ng, int numBlocks, int blockSize, int calls)
Definition at line 83 of file transform_density_field_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernel(transformDensityField,numBlocks,blockSize,d_grid,d_x,d_y,d_z,delta,rl,1/(1+z_ini),ng);
}
References do_return(), getIndent, InvokeGPUKernel, and transformDensityField().
Referenced by HACCGPM::parallel::GenerateDisplacementIC(), and HACCGPM::serial::GenerateDisplacementIC().
transformDensityField() [1/2]
__global__ void transformDensityField (const deviceFFT_t *__restrict oldGrid, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double rl, double a, int ng)
Definition at line 3 of file transform_density_field_initializer.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    double d = (2*M_PI)/rl;
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    float3 kmodes = HACCGPM::get_kmodes(idx3d,ng,d);
    double k2 = kmodes.x * kmodes.x + kmodes.y * kmodes.y + kmodes.z * kmodes.z;
    double k2mul = (1/k2);
    if (k2 == 0){
        k2mul = 0;
    }
    double mul = (1/delta) * k2mul;
    deviceFFT_t current = __ldg(&oldGrid[idx]);
    current.x *= mul;
    current.y *= mul;
    deviceFFT_t sx,sy,sz;
    sx.x = current.y * kmodes.x;
    sx.y = -current.x * kmodes.x;
    sy.x = current.y * kmodes.y;
    sy.y = -current.x * kmodes.y;
    sz.x = current.y * kmodes.z;
    sz.y = -current.x * kmodes.z;
    outSx[idx] = sx;
    outSy[idx] = sy;
    outSz[idx] = sz;
}
References deviceFFT_t, do_return(), HACCGPM::serial::get_index(), and HACCGPM::get_kmodes().
Referenced by launch_transform_density_field(), and launch_transform_density_field().
transformDensityField() [2/2]
__global__ void transformDensityField (const deviceFFT_t *__restrict oldGrid, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double rl, double a, int ng, int nlocal, int world_rank, int3 local_grid_size, int3 local_coords, int3 dims)
Definition at line 42 of file transform_density_field_initializer.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    double d = (2*M_PI)/rl;
    int3 idx3d = HACCGPM::parallel::get_global_index(idx,ng,local_grid_size,local_coords);
    float3 kmodes = HACCGPM::get_kmodes(idx3d,ng,d);
    double k2 = kmodes.x * kmodes.x + kmodes.y * kmodes.y + kmodes.z * kmodes.z;
    double k2mul = (1/k2);
    if (k2 == 0){
        k2mul = 0;
    }
    double mul = (1/delta) * k2mul;
    deviceFFT_t current = __ldg(&oldGrid[idx]);
    current.x *= mul;
    current.y *= mul;
    deviceFFT_t sx,sy,sz;
    sx.x = current.y * kmodes.x;
    sx.y = -current.x * kmodes.x;
    sy.x = current.y * kmodes.y;
    sy.y = -current.x * kmodes.y;
    sz.x = current.y * kmodes.z;
    sz.y = -current.x * kmodes.z;
    outSx[idx] = sx;
    outSy[idx] = sy;
    outSz[idx] = sz;
}
References deviceFFT_t, do_return(), HACCGPM::parallel::get_global_index(), and HACCGPM::get_kmodes().