HACC_GPM: /home/hqureshi/HACC_GPM/transfers.cpp File Reference
/home/hqureshi/HACC_GPM/transfers.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
#include "bdwgc/include/gc.h"
#include "haccgpm.hpp"
Macros
#define VerboseTransfer
Functions
int coords2rank (int3 coords, int3 dims)
void zero (int *ptr, int n)
void sends_per_rank (int *n_sends, int *n_swaps, int3 grid_coords, int3 global_grid_size)
void combine_sends (float4 **pos_sends, float4 **vel_sends, float4 **tmp_swap_pos, float4 **tmp_swap_vel, int *n_sends, int *n_swaps, int3 grid_coords, int3 global_grid_size, int world_size, int world_rank)
CPUTimer_t send_recv_data (int world_size, int world_rank, int *n_sends, int *n_recvs, float4 **pos_recvs, float4 **vel_recvs, float4 **pos_sends, float4 **vel_sends, int calls)
Variables
int TRANSFER_CALLS = 0
CPUTimer_t TRANSFER_TIME = 0
CPUTimer_t TRANSFER_MPI_TIME = 0
CPUTimer_t TRANSFER_GPU_TIME = 0
size_t TRANSFER_BYTES = 0
Macro Definition Documentation
VerboseTransfer
#define VerboseTransfer
Definition at line 7 of file transfers.cpp.
Function Documentation
combine_sends()
void combine_sends (float4 ** pos_sends, float4 ** vel_sends, float4 ** tmp_swap_pos, float4 ** tmp_swap_vel, int * n_sends, int * n_swaps, int3 grid_coords, int3 global_grid_size, int world_size, int world_rank)
Definition at line 43 of file transfers.cpp.
{
    for (int i = 0; i < world_size; i++){
        if (n_sends[i] > 0){
            pos_sends[i] = (float4*)GC_MALLOC(sizeof(float4)*n_sends[i]);
            vel_sends[i] = (float4*)GC_MALLOC(sizeof(float4)*n_sends[i]);
        }
    }
    int counts[world_size];
    zero(counts,world_size);
    int idx = 0;
    for (int x = -1; x < 2; x++){
        for (int y = -1; y < 2; y++){
            for (int z = -1; z < 2; z++){
                if (!(x == 0 && y == 0 && z == 0)){
                    int3 dest_coords = make_int3((grid_coords.x + x + global_grid_size.x)%global_grid_size.x,
                                            (grid_coords.y + y + global_grid_size.y)%global_grid_size.y,
                                            (grid_coords.z + z + global_grid_size.z)%global_grid_size.z);
                    int dest_rank = coords2rank(dest_coords,global_grid_size);
                    for (int i = 0; i < n_swaps[idx]; i++){
                        float4 this_particle = tmp_swap_pos[idx][i];
                        float4 this_vel = tmp_swap_vel[idx][i];
                        int store_idx = counts[dest_rank];
                        counts[dest_rank]++;
                        pos_sends[dest_rank][store_idx] = this_particle;
                        vel_sends[dest_rank][store_idx] = this_vel;
                    }
                }
                idx++;
            }
        }
    }
}
References coords2rank(), and zero().
Referenced by HACCGPM::parallel::transferParticles().
coords2rank()
int coords2rank (int3 coords, int3 dims)
Definition at line 15 of file transfers.cpp.
{
    return coords.x * dims.y * dims.z + coords.y * dims.z + coords.z;
}
Referenced by combine_sends(), and sends_per_rank().
send_recv_data()
CPUTimer_t send_recv_data (int world_size, int world_rank, int * n_sends, int * n_recvs, float4 ** pos_recvs, float4 ** vel_recvs, float4 ** pos_sends, float4 ** vel_sends, int calls)
Definition at line 78 of file transfers.cpp.
{
    getIndent(calls);
    #ifdef VerboseTransfer
    if(world_rank == 0)printf("%ssend_recv_data was called\n",indent);
    if(world_rank == 0)printf("%s   Sending/Recieving counts\n",indent);
    #endif
    CPUTimer_t start_counts = CPUTimer();
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if (i != world_rank)MPI_Send(&n_sends[i],1,MPI_INT,i,0,MPI_COMM_WORLD);
        TRANSFER_BYTES += n_sends[i] * sizeof(int);
    }
    for (int i = 0; i < world_size; i++){
        if (i != world_rank)MPI_Recv(&n_recvs[i],1,MPI_INT,i,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    CPUTimer_t end_counts = CPUTimer();
    #ifdef VerboseTransfer
    /*if(world_rank == 0)printf("%s      Sent/Recieved counts\n",indent);
    for (int i = 0; i < world_size; i++){
        if (world_rank == i){
            //printf("%s   Rank %d\n",indent,world_rank);
            for (int j = 0; j < world_size; j++){
                //if (j == world_rank)continue;
                printf("%s      Rank %d send %5d to   Rank %4d\n",indent,world_rank,n_sends[j],j);
            }
            for (int j = 0; j < world_size; j++){
                //if (j == world_rank)continue;
                printf("%s      Rank %d recv %5d from Rank %4d\n",indent,world_rank,n_recvs[j],j);
            }
        }
        MPI_Barrier(MPI_COMM_WORLD);
    }*/
    #endif
    CPUTimer_t start_particles = CPUTimer();
    for (int i = 0; i < world_size; i++){
        if (n_recvs[i] > 0){
            pos_recvs[i] = (float4*)GC_MALLOC(sizeof(float4)*n_recvs[i]);
            vel_recvs[i] = (float4*)GC_MALLOC(sizeof(float4)*n_recvs[i]);
        }
    }
    #ifdef VerboseTransfer
    if(world_rank == 0)printf("%s   Sending/Recieving particles\n",indent);
    #endif
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if (i != world_rank){
            if (n_sends[i] != 0){
                MPI_Send(pos_sends[i],n_sends[i]*4,MPI_FLOAT,i,0,MPI_COMM_WORLD);
                MPI_Send(vel_sends[i],n_sends[i]*4,MPI_FLOAT,i,1,MPI_COMM_WORLD);
                TRANSFER_BYTES += n_sends[i] * 4 * sizeof(float) * 2;
            }
        }
    }
    for (int i = 0; i < world_size; i++){
        if (i != world_rank){
            if (n_recvs[i] != 0){
                MPI_Recv(pos_recvs[i],n_recvs[i]*4,MPI_FLOAT,i,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
                MPI_Recv(vel_recvs[i],n_recvs[i]*4,MPI_FLOAT,i,1,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
            }
        }
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #ifdef VerboseTransfer
    if(world_rank == 0)printf("%s      Sent/Recieved particles\n",indent);
    #endif
    CPUTimer_t end_particles = CPUTimer();
    CPUTimer_t count_time = end_counts - start_counts;
    CPUTimer_t particle_time = end_particles - start_particles;
    CPUTimer_t total_time = particle_time + count_time;
    if(world_rank == 0)printf("%s   send_recv_data took %llu us\n",indent,total_time);
    return total_time;
}
References CPUTimer(), getIndent, TRANSFER_BYTES, and world_rank.
Referenced by HACCGPM::parallel::transferParticles().
sends_per_rank()
void sends_per_rank (int * n_sends, int * n_swaps, int3 grid_coords, int3 global_grid_size)
Definition at line 25 of file transfers.cpp.
{
    int idx = 0;
    for (int x = -1; x < 2; x++){
        for (int y = -1; y < 2; y++){
            for (int z = -1; z < 2; z++){
                if (!(x == 0 && y == 0 && z == 0)){
                    int3 dest_coords = make_int3((grid_coords.x + x + global_grid_size.x)%global_grid_size.x,
                                            (grid_coords.y + y + global_grid_size.y)%global_grid_size.y,
                                            (grid_coords.z + z + global_grid_size.z)%global_grid_size.z);
                    int dest_rank = coords2rank(dest_coords,global_grid_size);
                    n_sends[dest_rank] += n_swaps[idx];
                }
                idx++;
            }
        }
    }
}
References coords2rank().
Referenced by HACCGPM::parallel::transferParticles().
zero()
void zero (int * ptr, int n)
Definition at line 19 of file transfers.cpp.
{
    for (int i = 0; i < n; i++){
        ptr[i] = 0;
    }
}
Referenced by combine_sends(), and HACCGPM::parallel::transferParticles().
Variable Documentation
TRANSFER_BYTES
size_t TRANSFER_BYTES = 0
Definition at line 13 of file transfers.cpp.
Referenced by HACCGPM::parallel::printTransferBytes(), and send_recv_data().
TRANSFER_CALLS
int TRANSFER_CALLS = 0
Definition at line 9 of file transfers.cpp.
Referenced by HACCGPM::parallel::printTransferBytes(), HACCGPM::parallel::printTransferTimes(), and HACCGPM::parallel::transferParticles().
TRANSFER_GPU_TIME
CPUTimer_t TRANSFER_GPU_TIME = 0
Definition at line 12 of file transfers.cpp.
Referenced by HACCGPM::parallel::printTransferTimes(), and HACCGPM::parallel::transferParticles().
TRANSFER_MPI_TIME
CPUTimer_t TRANSFER_MPI_TIME = 0
Definition at line 11 of file transfers.cpp.
Referenced by HACCGPM::parallel::printTransferTimes(), and HACCGPM::parallel::transferParticles().
TRANSFER_TIME
CPUTimer_t TRANSFER_TIME = 0
Definition at line 10 of file transfers.cpp.
Referenced by HACCGPM::parallel::printTransferTimes(), and HACCGPM::parallel::transferParticles().