HACC_GPM: HACCGPM::serial Namespace Reference
HACCGPM::serial Namespace Reference
Classes
class MemoryManager
Functions
__device__ __forceinline__ int3 get_index (int idx, int ng)
void UpdatePositions (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, HACCGPM::Timestepper ts, float frac, int calls=0)
void UpdatePositions (float4 *d_pos, float4 *d_vel, HACCGPM::Timestepper ts, float frac, int ng, int blockSize, int calls=0)
void UpdateVelocities (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, HACCGPM::Timestepper ts, int calls=0)
void UpdateVelocities (float4 *d_vel, float4 *d_grad, float4 *d_pos, HACCGPM::Timestepper ts, int ng, int blockSize, int calls=0)
void CIC (deviceFFT_t *d_grid, float *d_temp, float4 *d_pos, int ng, int blockSize, int calls=0)
void CIC (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, int calls=0)
double get_fscal (double m_aa, double m_adot, double m_omega_cb)
double get_adot (double m_aa, double m_w, double m_wa, double m_omega_cb, double m_omega_radiation, double m_f_nu_massless, double m_f_nu_massive, double m_omega_matter, double m_omega_nu)
void writeOutput (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, char *fname, int calls=0)
void writeOutput (char *fname, float4 *d_pos, float4 *d_vel, int ng, int calls=0)
void GetPowerSpectrum (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, int nbins, const char *fname, int calls=0)
void GenerateDisplacementIC (HACCGPM::serial::MemoryManager &mem, HACCGPM::CosmoClass &cosmo, HACCGPM::Params &params, HACCGPM::Timestepper &ts, int calls=0)
void Solve (deviceFFT_t *d_rho, hostFFT_t *d_greens, int ng, int blockSize, int calls=0)
void SolveGradient (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, int calls=0)
void SolveGradient (float4 *d_grad, deviceFFT_t *d_rho, hostFFT_t *d_greens, int ng, int blockSize, int calls=0)
void InitGreens (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, int calls=0)
void forward_fft (deviceFFT_t *data, deviceFFT_t *out, int ng, int calls=0)
void forward_fft (deviceFFT_t *data, int ng, int calls=0)
void backward_fft (deviceFFT_t *data, deviceFFT_t *out, int ng, int calls=0)
void backward_fft (deviceFFT_t *data, int ng, int calls=0)
void fft_cache_plan (int ng)
void printCICTimes ()
void printFFTTimes ()
void printPowerTimes ()
void printOutputTimes ()
void PyAnalysis (HACCGPM::Params &params, HACCGPM::serial::MemoryManager &mem, HACCGPM::Timestepper &ts, PyCosmoTools &pytools, int step)
Function Documentation
backward_fft() [1/2]
void HACCGPM::serial::backward_fft (deviceFFT_t * data, deviceFFT_t * out, int ng, int calls = 0)
Definition at line 169 of file ffts.cu.
{
    CPUTimer_t start = CPUTimer();
    getIndent(calls);
    #ifdef VerboseFFT
    printf("%sbackward_fft (out of place) was called with\n%s   ng %d\n",indent,indent,ng);
    #endif
    cufftHandle plan;
    #ifdef UsePlanManager
    plan = plan_manager.get_plan(ng,calls+1);
    #else
    printf("%s   Creating plan %d\n",indent,ng);
    if (cufftPlan3d(&plan, ng, ng, ng, CUFFT_Z2Z) != CUFFT_SUCCESS){
        printf("CUFFT error: Plan creation failed\n");
        return;
    };
    #endif
    CPUTimer_t plan_t = CPUTimer();
    printf("%s   Executing Z2Z CUFFT_INVERSE\n",indent);
    if (cufftExecZ2Z(plan, data, out, CUFFT_INVERSE) != CUFFT_SUCCESS){
        printf("CUFFT error: ExecZ2Z Backward failed\n");
        return;
    }
    cudaDeviceSynchronize();
    #ifndef UsePlanManager
    printf("%s   Destroying plan %d\n",indent,ng);
    cufftDestroy(plan);
    #endif
    CPUTimer_t end = CPUTimer();
    CPUTimer_t plan_time = plan_t - start;
    CPUTimer_t t = end-start;
    printf("%s   backward_fft (out of place) took %llu us (%llu us planning)\n",indent,t,plan_time);
    FFT_BACKWARD_CALLS_OP++;
    FFT_BACKWARD_TIME_OP += t;
    FFT_BACKWARD_PLAN_TIME_OP += plan_time;
}
References CPUTimer(), FFT_BACKWARD_CALLS_OP, FFT_BACKWARD_PLAN_TIME_OP, FFT_BACKWARD_TIME_OP, PlanManager::get_plan(), getIndent, and plan_manager.
Referenced by GenerateDisplacementIC(), Solve(), and SolveGradient().
backward_fft() [2/2]
void HACCGPM::serial::backward_fft (deviceFFT_t * data, int ng, int calls = 0)
Definition at line 213 of file ffts.cu.
{
    CPUTimer_t start = CPUTimer();
    getIndent(calls);
    #ifdef VerboseFFT
    printf("%sbackward_fft (in place) was called with\n%s   ng %d\n",indent,indent,ng);
    #endif
    cufftHandle plan;
    #ifdef UsePlanManager
    plan = plan_manager.get_plan(ng,calls+1);
    #else
    printf("%s   Creating plan %d\n",indent,ng);
    if (cufftPlan3d(&plan, ng, ng, ng, CUFFT_Z2Z) != CUFFT_SUCCESS){
        printf("CUFFT error: Plan creation failed\n");
        return;
    };
    #endif
    CPUTimer_t plan_t = CPUTimer();
    printf("%s   Executing Z2Z CUFFT_INVERSE\n",indent);
    if (cufftExecZ2Z(plan, data, data, CUFFT_INVERSE) != CUFFT_SUCCESS){
        printf("CUFFT error: ExecZ2Z Backward failed\n");
        return;
    }
    cudaDeviceSynchronize();
    #ifndef UsePlanManager
    printf("%s   Destroying plan %d\n",indent,ng);
    cufftDestroy(plan);
    #endif
    CPUTimer_t end = CPUTimer();
    CPUTimer_t plan_time = plan_t - start;
    CPUTimer_t t = end-start;
    printf("%s   backward_fft (in place) took %llu us (%llu us planning)\n",indent,t,plan_time);
    FFT_BACKWARD_CALLS_IP++;
    FFT_BACKWARD_TIME_IP += t;
    FFT_BACKWARD_PLAN_TIME_IP += plan_time;
}
References CPUTimer(), FFT_BACKWARD_CALLS_IP, FFT_BACKWARD_PLAN_TIME_IP, FFT_BACKWARD_TIME_IP, PlanManager::get_plan(), getIndent, and plan_manager.
CIC() [1/2]
void HACCGPM::serial::CIC (deviceFFT_t * d_grid, float * d_temp, float4 * d_pos, int ng, int blockSize, int calls = 0)
Definition at line 127 of file pm_actions.cu.
{
    CPUTimer_t start = CPUTimer();
    int numBlocks = (ng*ng*ng)/blockSize;
    getIndent(calls);
    #ifdef VerboseUpdate
    printf("%sCIC (complex,float) was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,blockSize,indent,numBlocks);
    #endif
    cudaCall(cudaMemset,d_temp,0,sizeof(float)*ng*ng*ng);
    CIC_KERNEL_TIME += InvokeGPUKernel(CICKernel,numBlocks,blockSize,d_temp,d_pos,ng,1.0f);
    CIC_KERNEL_TIME += InvokeGPUKernel(float2complex,numBlocks,blockSize,d_grid,d_temp,ng*ng*ng);
    CPUTimer_t end = CPUTimer();
    CPUTimer_t t = end-start;
    printf("%s   CIC (complex,float) took %llu us\n",indent,t);
    CIC_TIME += t;
    CIC_CALLS += 1;
}
References CIC_CALLS, CIC_KERNEL_TIME, CIC_TIME, CICKernel(), CPUTimer(), cudaCall, do_return(), float2complex(), getIndent, and InvokeGPUKernel.
Referenced by CIC(), GetPowerSpectrum(), and serial().
CIC() [2/2]
void HACCGPM::serial::CIC (HACCGPM::Params & params, HACCGPM::serial::MemoryManager & mem, int calls = 0)
Definition at line 123 of file pm_actions.cu.
{
    HACCGPM::serial::CIC(mem.d_grid,mem.d_tempgrid,mem.d_pos,params.ng,params.blockSize,calls);
}
References CIC(), and do_return().
fft_cache_plan()
void HACCGPM::serial::fft_cache_plan (int ng)
Definition at line 75 of file ffts.cu.
{
    #ifdef UsePlanManager
    plan_manager.get_plan(ng,0);
    #endif
}
References PlanManager::get_plan(), and plan_manager.
Referenced by serial().
forward_fft() [1/2]
void HACCGPM::serial::forward_fft (deviceFFT_t * data, deviceFFT_t * out, int ng, int calls = 0)
Definition at line 81 of file ffts.cu.
{
    CPUTimer_t start = CPUTimer();
    getIndent(calls);
    #ifdef VerboseFFT
    printf("%sforward_fft (out of place) was called with\n%s   ng %d\n",indent,indent,ng);
    #endif
    cufftHandle plan;
    #ifdef UsePlanManager
    plan = plan_manager.get_plan(ng,calls+1);
    #else
    printf("%s   Creating plan %d\n",indent,ng);
    if (cufftPlan3d(&plan, ng, ng, ng, CUFFT_Z2Z) != CUFFT_SUCCESS){
        printf("CUFFT error: Plan creation failed\n");
        return;
    };
    #endif
    CPUTimer_t plan_t = CPUTimer();
    printf("%s   Executing Z2Z CUFFT_FORWARD\n",indent);
    if (cufftExecZ2Z(plan, data, out, CUFFT_FORWARD) != CUFFT_SUCCESS){
        printf("CUFFT error: ExecZ2Z Forward failed\n");
        return;
    }
    cudaDeviceSynchronize();
    #ifndef UsePlanManager
    printf("%s   Destroying plan %d\n",indent,ng);
    cufftDestroy(plan);
    #endif
    CPUTimer_t end = CPUTimer();
    CPUTimer_t plan_time = plan_t - start;
    CPUTimer_t t = end-start;
    printf("%s   forward_fft (out of place) took %llu us (%llu us planning)\n",indent,t,plan_time);
    FFT_FORWARD_CALLS_OP++;
    FFT_FORWARD_TIME_OP += t;
    FFT_FORWARD_PLAN_TIME_OP += plan_time;
}
References CPUTimer(), FFT_FORWARD_CALLS_OP, FFT_FORWARD_PLAN_TIME_OP, FFT_FORWARD_TIME_OP, PlanManager::get_plan(), getIndent, and plan_manager.
Referenced by GenerateFourierAmplitudes(), GetPowerSpectrum(), Solve(), and SolveGradient().
forward_fft() [2/2]
void HACCGPM::serial::forward_fft (deviceFFT_t * data, int ng, int calls = 0)
Definition at line 124 of file ffts.cu.
{
    CPUTimer_t start = CPUTimer();
    getIndent(calls);
    #ifdef VerboseFFT
    printf("%sforward_fft (in place) was called with\n%s   ng %d\n",indent,indent,ng);
    #endif
    cufftHandle plan;
    #ifdef UsePlanManager
    plan = plan_manager.get_plan(ng,calls+1);
    #else
    printf("%s   Creating plan %d\n",indent,ng);
    if (cufftPlan3d(&plan, ng, ng, ng, CUFFT_Z2Z) != CUFFT_SUCCESS){
        printf("CUFFT error: Plan creation failed\n");
        return;
    };
    #endif
    CPUTimer_t plan_t = CPUTimer();
    printf("%s   Executing Z2Z CUFFT_FORWARD\n",indent);
    if (cufftExecZ2Z(plan, data, data, CUFFT_FORWARD) != CUFFT_SUCCESS){
        printf("CUFFT error: ExecZ2Z Forward failed\n");
        return;
    }
    cudaDeviceSynchronize();
    #ifndef UsePlanManager
    printf("%s   Destroying plan %d\n",indent,ng);
    cufftDestroy(plan);
    #endif
    CPUTimer_t end = CPUTimer();
    CPUTimer_t plan_time = plan_t - start;
    CPUTimer_t t = end-start;
    printf("%s   forward_fft (in place) took %llu us (%llu us planning)\n",indent,t,plan_time);
    FFT_FORWARD_CALLS_IP++;
    FFT_FORWARD_TIME_IP += t;
    FFT_FORWARD_PLAN_TIME_IP += plan_time;
}
References CPUTimer(), FFT_FORWARD_CALLS_IP, FFT_FORWARD_PLAN_TIME_IP, FFT_FORWARD_TIME_IP, PlanManager::get_plan(), getIndent, and plan_manager.
GenerateDisplacementIC()
void HACCGPM::serial::GenerateDisplacementIC (HACCGPM::serial::MemoryManager & mem, HACCGPM::CosmoClass & cosmo, HACCGPM::Params & params, HACCGPM::Timestepper & ts, int calls = 0)
Definition at line 119 of file initializer.cu.
{
    int numBlocks = (params.ng*params.ng*params.ng)/params.blockSize;
    getIndent(calls);
    #ifdef VerboseInitializer
    printf("%sGenerateDisplacementIC was called with\n%s   blockSize %d\n%s   numBlocks %d\n%s   params %s\n",indent,indent,params.blockSize,indent,numBlocks,indent,params.fname);
    printf("%s   Calling GenerateFourierAmplitudes...\n",indent);
    #endif
    GenerateFourierAmplitudes(cosmo, params, mem.d_grid, params.z_ini, calls+1);
    #ifdef VerboseInitializer
    printf("%s      Called GenerateFourierAmplitudes.\n",indent);
    printf("%s   Allocating d_sx, d_sy, d_sz...\n",indent);
    #endif
    deviceFFT_t* d_sx; cudaCall(cudaMalloc,&d_sx,sizeof(deviceFFT_t)*params.ng*params.ng*params.ng);
    deviceFFT_t* d_sy; cudaCall(cudaMalloc,&d_sy,sizeof(deviceFFT_t)*params.ng*params.ng*params.ng);
    deviceFFT_t* d_sz; cudaCall(cudaMalloc,&d_sz,sizeof(deviceFFT_t)*params.ng*params.ng*params.ng);
    #ifdef VerboseInitializer
    printf("%s      Allocated d_sx, d_sy, d_sz.\n",indent);
    printf("%s   Calling get_delta_and_dotDelta...\n",indent);
    #endif
    double delta;
    double dotDelta;
    double this_a = (1/(params.z_ini + 1)) - (ts.deltaT/2.0f);
    double velZ = (1.0f/this_a) - 1.0f;
    //get_delta_and_dotDelta(params_file, z,velZ,&delta,&dotDelta,calls+1);
    cosmo.get_delta_and_dotDelta(params.z_ini,velZ,&delta,&dotDelta);
    printf("%s      Delta %g, dotDelta %g\n",indent,delta,dotDelta);
    //finalize_python(calls+1);
    #ifdef VerboseInitializer
    printf("%s      Called get_delta_and_dotDelta.\n",indent);
    printf("%s   Calling transformDensityField...\n",indent);
    #endif
    InvokeGPUKernel(transformDensityField,numBlocks,params.blockSize,mem.d_grid,d_sx,d_sy,d_sz,delta,params.rl,1/(1+params.z_ini),params.ng);
    #ifdef VerboseInitializer
    printf("%s      Called transformVelocityField.\n",indent);
    printf("%s   Doing Backward FFTs...\n",indent);
    #endif
    HACCGPM::serial::backward_fft(d_sx,params.ng,calls+1);
    HACCGPM::serial::backward_fft(d_sy,params.ng,calls+1);
    HACCGPM::serial::backward_fft(d_sz,params.ng,calls+1);
    double scale_by = 1.0f/((double)(params.ng*params.ng*params.ng));
    int scale_n = params.ng*params.ng*params.ng;
    InvokeGPUKernel(ScaleFFT,numBlocks,params.blockSize,d_sx,scale_by,scale_n);
    InvokeGPUKernel(ScaleFFT,numBlocks,params.blockSize,d_sy,scale_by,scale_n);
    InvokeGPUKernel(ScaleFFT,numBlocks,params.blockSize,d_sz,scale_by,scale_n);
    #ifdef VerboseInitializer
    printf("%s      Done Backward FFTs.\n",indent);
    #endif
    InvokeGPUKernel(placeParticles,numBlocks,params.blockSize,mem.d_pos,mem.d_vel,d_sx,d_sy,d_sz,delta,dotDelta,params.rl,1/(1+params.z_ini),ts.deltaT,ts.fscal,params.ng);
    #ifdef VerboseInitializer
    printf("%s   Freeing d_sx, d_sy, d_sz...\n",indent);
    #endif
    cudaFree(d_sx);
    cudaFree(d_sy);
    cudaFree(d_sz);
    #ifdef VerboseInitializer
    printf("%s      Freed d_sx, d_sy, d_sz.\n",indent);
    #endif
}
References backward_fft(), cudaCall, deviceFFT_t, do_return(), GenerateFourierAmplitudes(), getIndent, InvokeGPUKernel, placeParticles(), ScaleFFT(), and transformDensityField().
Referenced by serial().
get_adot()
double HACCGPM::serial::get_adot (double m_aa, double m_w, double m_wa, double m_omega_cb, double m_omega_radiation, double m_f_nu_massless, double m_f_nu_massive, double m_omega_matter, double m_omega_nu)
Definition at line 11 of file timestepper.cpp.
{
    double pp1 = pow(m_aa, -3.0*(m_w+m_wa))*exp(-3.0*m_wa*(1.0-m_aa));
    double tmp = m_omega_cb
    + (1.0+m_f_nu_massless)*m_omega_radiation/m_aa
    + omega_nu_massive(m_aa,m_omega_nu,m_f_nu_massive,m_omega_radiation)*pow(m_aa,3.0)
    + (1.0-m_omega_matter-(1.0+m_f_nu_massless)*m_omega_radiation)*pp1;
    tmp /= m_aa;
    return sqrt(tmp);
}
References do_return(), and omega_nu_massive().
Referenced by HACCGPM::Timestepper::advanceHalfStep(), HACCGPM::Timestepper::reverseHalfStep(), HACCGPM::Timestepper::setInitialA(), and HACCGPM::Timestepper::setInitialZ().
get_fscal()
double HACCGPM::serial::get_fscal (double m_aa, double m_adot, double m_omega_cb)
Definition at line 21 of file timestepper.cpp.
{
    float dtdy = m_aa/(m_aa*m_adot);
    double m_phiscal = 1.5*m_omega_cb;//Poisson equation is grad^2 phi = 3/2 omega_m (rho-1)
    double m_fscal = m_phiscal*dtdy*(1.0/m_aa);
    return m_fscal;
}
References do_return().
Referenced by HACCGPM::Timestepper::advanceHalfStep(), HACCGPM::Timestepper::reverseHalfStep(), HACCGPM::Timestepper::setInitialA(), and HACCGPM::Timestepper::setInitialZ().
get_index()
__device__ __forceinline__ int3 HACCGPM::serial::get_index (int idx, int ng)
Definition at line 334 of file haccgpm.hpp.
{
            int3 out;
            out.x = idx/(ng*ng);
            out.y = (idx - (out.x*ng*ng))/ng;
            out.z = (idx - (out.x*ng*ng)) - out.y*ng;
            return out;
        }
References do_return().
Referenced by BinPower(), getGreens(), interpolatePowerSpectrum(), kspace_solve_gradient(), PkCICFilter(), placeParticles(), and transformDensityField().
GetPowerSpectrum()
void HACCGPM::serial::GetPowerSpectrum (HACCGPM::Params & params, HACCGPM::serial::MemoryManager & mem, int nbins, const char * fname, int calls = 0)
Definition at line 114 of file power.cu.
{
    CPUTimer_t start = CPUTimer();
    int numBlocks = (params.ng*params.ng*params.ng)/params.blockSize;
    getIndent(calls);
    #ifdef VerbosePower
    printf("%sGetPowerSpectrum was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,params.blockSize,indent,numBlocks);
    printf("%s   Allocating d_temp_pos, kBins, binCounts, binVals, d_binCounts, d_binVals\n",indent);
    #endif
    float4* d_temp_pos; cudaCall(cudaMalloc,&d_temp_pos,sizeof(float4)*params.ng*params.ng*params.ng);
    //hostFFT_t* d_powerSpectrum; cudaCall(cudaMalloc,&d_powerSpectrum,sizeof(hostFFT_t)*ng*ng*ng);
    double* kBins = (double*)malloc(sizeof(double)*nbins);
    int* binCounts = (int*)malloc(sizeof(int)*(nbins));
    double* binVals = (double*)malloc(sizeof(double)*nbins);
    int* d_binCounts; cudaCall(cudaMalloc,&d_binCounts,sizeof(int)*nbins);
    double* d_binVals; cudaCall(cudaMalloc,&d_binVals,sizeof(double)*nbins);
    //hostFFT_t* tmp = (hostFFT_t*)malloc(sizeof(hostFFT_t)*ng*ng*ng);
    POWER_KERNEL_TIME += InvokeGPUKernel(cpy,numBlocks,params.blockSize,d_temp_pos,mem.d_pos);
    double new_rl = (params.rl/(pow(2,params.pkFolds)));
    double d = (2*M_PI)/(new_rl);
    double d3 = sqrt(3*d*d);
    double minK = d;
    double maxK = sqrt(3*((params.ng/2)*(params.ng/2)*d*d));
    double binDelta = (maxK - minK)/((double)nbins);
    for (int i = 0; i < nbins; i++){
        kBins[i] = minK + binDelta * (((float)i) + 0.5f);
    }
    new_rl = params.rl;
    for (int current_fold = 0; current_fold < params.pkFolds + 1; current_fold++){
        cudaCall(cudaMemset,d_binCounts,0,sizeof(int)*nbins);
        cudaCall(cudaMemset,d_binVals,0,sizeof(double)*nbins);
        new_rl = (params.rl/(pow(2,current_fold)));
        d = (2*M_PI)/(new_rl);
        if (current_fold > 0){
            POWER_KERNEL_TIME += InvokeGPUKernel(foldParticles,numBlocks,params.blockSize,d_temp_pos,(double)params.ng);
        }
        CPUTimer_t start_extras = CPUTimer();
        HACCGPM::serial::CIC(mem.d_grid,mem.d_tempgrid,d_temp_pos,params.ng,params.blockSize,calls+1);
        HACCGPM::serial::forward_fft(mem.d_grid,params.ng,calls + 1);
        CPUTimer_t end_extras = CPUTimer();
        POWER_KERNEL_TIME += end_extras - start_extras;
        POWER_KERNEL_TIME += InvokeGPUKernel(scalePower,numBlocks,params.blockSize,mem.d_grid,(double)params.ng,params.rl,params.ng*params.ng*params.ng);
        POWER_KERNEL_TIME += InvokeGPUKernel(PkCICFilter,numBlocks,params.blockSize,mem.d_grid,params.ng);
        POWER_KERNEL_TIME += InvokeGPUKernel(BinPower,numBlocks,params.blockSize,mem.d_grid,d_binVals,d_binCounts,minK,binDelta,new_rl,params.ng);
        cudaCall(cudaMemcpy, binVals, d_binVals, sizeof(double)*nbins, cudaMemcpyDeviceToHost);
        cudaCall(cudaMemcpy, binCounts, d_binCounts, sizeof(int)*nbins, cudaMemcpyDeviceToHost);
        writePkOutput(fname,binVals,binCounts,kBins,nbins,0);
    }
    free(kBins);
    free(binCounts);
    free(binVals);
    cudaCall(cudaFree,d_temp_pos);
    cudaCall(cudaFree,d_binCounts);
    cudaCall(cudaFree,d_binVals);
    CPUTimer_t end = CPUTimer();
    CPUTimer_t t = end-start;
    POWER_CALLS++;
    POWER_TIME += t;
    printf("%s   GetPowerSpectrum took %llu us\n",indent,t);
}
References BinPower(), CIC(), CPUTimer(), cpy(), cudaCall, do_return(), foldParticles(), forward_fft(), getIndent, InvokeGPUKernel, PkCICFilter(), POWER_CALLS, POWER_KERNEL_TIME, POWER_TIME, scalePower(), and writePkOutput().
Referenced by serial().
InitGreens()
void HACCGPM::serial::InitGreens (HACCGPM::Params & params, HACCGPM::serial::MemoryManager & mem, int calls = 0)
Definition at line 57 of file greens.cu.
{
    int numBlocks = (params.ng*params.ng*params.ng)/params.blockSize;
    getIndent(calls);
    #ifdef VerboseGreens
    printf("%sInitGreens was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,params.blockSize,indent,numBlocks);
    printf("%s   Calling getGreens...\n",indent);
    #endif
    InvokeGPUKernel(getGreens,numBlocks,params.blockSize,mem.d_greens,params.ng);
    #ifdef VerboseGreens
    printf("%s      Called getGreens...\n",indent);
    #endif
}
References do_return(), getGreens(), getIndent, and InvokeGPUKernel.
Referenced by serial().
printCICTimes()
void HACCGPM::serial::printCICTimes ()
Definition at line 183 of file pm_actions.cu.
{
    printf("   CIC               -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10llu us | mean: %10.2f us\n",CIC_CALLS,CIC_TIME,CIC_TIME - CIC_KERNEL_TIME,CIC_KERNEL_TIME,((float)CIC_TIME)/((float)(CIC_CALLS)));
    printf("   UpdatePositions   -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10llu us | mean: %10.2f us\n",UPDATE_POS_CALLS,UPDATE_POS_TIME,UPDATE_POS_TIME - UPDATE_POS_KERNEL_TIME,UPDATE_POS_KERNEL_TIME,((float)UPDATE_POS_TIME)/((float)(UPDATE_POS_CALLS)));
    printf("   UpdateVelocities  -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10llu us | mean: %10.2f us\n",UPDATE_VEL_CALLS,UPDATE_VEL_TIME,UPDATE_VEL_TIME - UPDATE_VEL_KERNEL_TIME,UPDATE_VEL_KERNEL_TIME,((float)UPDATE_VEL_TIME)/((float)(UPDATE_VEL_CALLS)));
}
References CIC_CALLS, CIC_KERNEL_TIME, CIC_TIME, do_return(), UPDATE_POS_CALLS, UPDATE_POS_KERNEL_TIME, UPDATE_POS_TIME, UPDATE_VEL_CALLS, UPDATE_VEL_KERNEL_TIME, and UPDATE_VEL_TIME.
Referenced by serial().
printFFTTimes()
void HACCGPM::serial::printFFTTimes ()
Definition at line 253 of file ffts.cu.
{
    //printf("   CIC              -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10llu us | mean: %10.2f us\n",CIC_CALLS,CIC_TIME,CIC_TIME - CIC_KERNEL_TIME,CIC_KERNEL_TIME,((float)CIC_TIME)/((float)(CIC_CALLS)));
    //printf("   UpdatePositions  -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10llu us | mean: %10.2f us\n",UPDATE_POS_CALLS,UPDATE_POS_TIME,UPDATE_POS_TIME - UPDATE_POS_KERNEL_TIME,UPDATE_POS_KERNEL_TIME,((float)UPDATE_POS_TIME)/((float)(UPDATE_POS_CALLS)));
    if (FFT_FORWARD_CALLS_OP != 0){
        printf("   forward_fft (op)  -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10llu us | mean: %10.2f us\n",FFT_FORWARD_CALLS_OP,FFT_FORWARD_TIME_OP,FFT_FORWARD_PLAN_TIME_OP,FFT_FORWARD_TIME_OP - FFT_FORWARD_PLAN_TIME_OP,((float)FFT_FORWARD_TIME_OP)/((float)(FFT_FORWARD_CALLS_OP)));
    }
    if (FFT_FORWARD_CALLS_IP != 0){
        printf("   forward_fft (ip)  -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10llu us | mean: %10.2f us\n",FFT_FORWARD_CALLS_IP,FFT_FORWARD_TIME_IP,FFT_FORWARD_PLAN_TIME_IP,FFT_FORWARD_TIME_IP - FFT_FORWARD_PLAN_TIME_IP,((float)FFT_FORWARD_TIME_IP)/((float)(FFT_FORWARD_CALLS_IP)));
    }
    if (FFT_BACKWARD_CALLS_OP != 0){
        printf("   backward_fft (op) -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10llu us | mean: %10.2f us\n",FFT_BACKWARD_CALLS_OP,FFT_BACKWARD_TIME_OP,FFT_BACKWARD_PLAN_TIME_OP,FFT_BACKWARD_TIME_OP - FFT_BACKWARD_PLAN_TIME_OP,((float)FFT_BACKWARD_TIME_OP)/((float)(FFT_BACKWARD_CALLS_OP)));
    }
    if (FFT_BACKWARD_CALLS_IP != 0){
        printf("   backward_fft (ip) -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10llu us | mean: %10.2f us\n",FFT_BACKWARD_CALLS_IP,FFT_BACKWARD_TIME_IP,FFT_BACKWARD_PLAN_TIME_IP,FFT_BACKWARD_TIME_IP - FFT_BACKWARD_PLAN_TIME_IP,((float)FFT_BACKWARD_TIME_IP)/((float)(FFT_BACKWARD_CALLS_IP)));
    }
}
References FFT_BACKWARD_CALLS_IP, FFT_BACKWARD_CALLS_OP, FFT_BACKWARD_PLAN_TIME_IP, FFT_BACKWARD_PLAN_TIME_OP, FFT_BACKWARD_TIME_IP, FFT_BACKWARD_TIME_OP, FFT_FORWARD_CALLS_IP, FFT_FORWARD_CALLS_OP, FFT_FORWARD_PLAN_TIME_IP, FFT_FORWARD_PLAN_TIME_OP, FFT_FORWARD_TIME_IP, and FFT_FORWARD_TIME_OP.
Referenced by serial().
printOutputTimes()
void HACCGPM::serial::printOutputTimes ()
Definition at line 45 of file io.cu.
{
    printf("   writeOutput       -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10d us | mean: %10.2f us\n",OUTPUT_CALLS,OUTPUT_TIME,OUTPUT_TIME,0,((float)OUTPUT_TIME)/((float)(OUTPUT_CALLS)));
}
References do_return(), OUTPUT_CALLS, and OUTPUT_TIME.
Referenced by serial().
printPowerTimes()
void HACCGPM::serial::printPowerTimes ()
Definition at line 208 of file power.cu.
{
    printf("   GetPowerSpectrum  -> calls: %10d | total: %10llu us | cpu: %10llu us | gpu: %10llu us | mean: %10.2f us\n",POWER_CALLS,POWER_TIME,POWER_TIME - POWER_KERNEL_TIME,POWER_KERNEL_TIME,((float)POWER_TIME)/((float)(POWER_CALLS)));
}
References do_return(), POWER_CALLS, POWER_KERNEL_TIME, and POWER_TIME.
Referenced by serial().
PyAnalysis()
void HACCGPM::serial::PyAnalysis (HACCGPM::Params & params, HACCGPM::serial::MemoryManager & mem, HACCGPM::Timestepper & ts, PyCosmoTools & pytools, int step)
Definition at line 3 of file py_analysis.cu.
{
    if (params.do_analysis){
        if (params.analysis[step]){
            printf("Doing Python Analysis Step\n");
            float4* particles = (float4*)malloc(sizeof(float4)*params.ng*params.ng*params.ng);
            float4* vels = (float4*)malloc(sizeof(float4)*params.ng*params.ng*params.ng);
            cudaCall(cudaMemcpy, particles, mem.d_pos, sizeof(float4)*params.ng*params.ng*params.ng, cudaMemcpyDeviceToHost);
            cudaCall(cudaMemcpy, vels, mem.d_vel, sizeof(float4)*params.ng*params.ng*params.ng, cudaMemcpyDeviceToHost);
            float* combined = (float*)malloc(sizeof(float)*params.ng*params.ng*params.ng*7);
            for (int i = 0; i < params.ng*params.ng*params.ng; i++){
                combined[i*7] = particles[i].w;
                combined[i*7 + 1] = particles[i].x;
                combined[i*7 + 2] = particles[i].y;
                combined[i*7 + 3] = particles[i].z;
                combined[i*7 + 4] = vels[i].x;
                combined[i*7 + 5] = vels[i].y;
                combined[i*7 + 6] = vels[i].z;
            }
            free(particles);
            free(vels);
            pytools.analysisStep(combined,params.ng*params.ng*params.ng,7,step,ts.aa,ts.z);
            free(combined);
        }
    }
}
References HACCGPM::Timestepper::aa, PyCosmoTools::analysisStep(), cudaCall, HACCGPM::serial::MemoryManager::d_pos, HACCGPM::serial::MemoryManager::d_vel, and HACCGPM::Timestepper::z.
Referenced by serial().
Solve()
void HACCGPM::serial::Solve (deviceFFT_t * d_rho, hostFFT_t * d_greens, int ng, int blockSize, int calls = 0)
Definition at line 227 of file solver.cu.
{
    int numBlocks = (ng*ng*ng)/blockSize;
    getIndent(calls);
    #ifdef VerboseSolver
    printf("%sSolve was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,blockSize,indent,numBlocks);
    printf("%s   Doing forward fft...\n",indent);
    #endif
    HACCGPM::serial::forward_fft(d_rho,ng,calls+1);
    #ifdef VerboseSolver
    printf("%s      Done forward fft.\n",indent);
    printf("%s   Calling kspace_solve...\n",indent);
    #endif
    InvokeGPUKernel(kspace_solve,numBlocks,blockSize,d_rho,d_greens);
    #ifdef VerboseSolver
    printf("%s      Called kspace_solve.\n",indent);
    printf("%s   Doing backward fft...\n",indent);
    #endif
    HACCGPM::serial::backward_fft(d_rho,ng,calls+1);
    #ifdef VerboseSolver
    printf("%s      Done backward fft.\n",indent);
    #endif
}
References backward_fft(), do_return(), forward_fft(), getIndent, InvokeGPUKernel, and kspace_solve().
SolveGradient() [1/2]
void HACCGPM::serial::SolveGradient (float4 * d_grad, deviceFFT_t * d_rho, hostFFT_t * d_greens, int ng, int blockSize, int calls = 0)
Definition at line 256 of file solver.cu.
{
    int numBlocks = (ng*ng*ng)/blockSize;
    getIndent(calls);
    #ifdef VerboseSolver
    printf("%sSolveGradient was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,blockSize,indent,numBlocks);
    printf("%s   Doing forward fft...\n",indent);
    #endif
    HACCGPM::serial::forward_fft(d_rho,ng,calls+1);
    #ifdef VerboseSolver
    printf("%s      Done forward fft.\n",indent);
    printf("%s   Allocating d_x, d_y, d_z...\n",indent);
    #endif
    deviceFFT_t* d_x; cudaCall(cudaMalloc,&d_x,sizeof(deviceFFT_t)*ng*ng*ng);
    deviceFFT_t* d_y; cudaCall(cudaMalloc,&d_y,sizeof(deviceFFT_t)*ng*ng*ng);
    deviceFFT_t* d_z; cudaCall(cudaMalloc,&d_z,sizeof(deviceFFT_t)*ng*ng*ng);
    #ifdef VerboseSolver
    printf("%s      Allocated d_x, d_y, d_z\n",indent);
    printf("%s   Calling kspace_solve_gradient...\n",indent);
    #endif
    double const b1 =   4.0 / 3.0;
    double const b2 = - 1.0 / 6.0;
    InvokeGPUKernel(kspace_solve_gradient,numBlocks,blockSize,d_x,d_y,d_z,d_rho,d_greens,b1,b2,ng);
    #ifdef VerboseSolver
    printf("%s      Called kspace_solve_gradient.\n",indent);
    printf("%s   Doing backward ffts...\n",indent);
    #endif
    HACCGPM::serial::backward_fft(d_x,ng,calls+1);
    HACCGPM::serial::backward_fft(d_y,ng,calls+1);
    HACCGPM::serial::backward_fft(d_z,ng,calls+1);
    //SHOULD WE NORMALIZE THIS???
    #ifdef VerboseSolver
    printf("%s      Done backward ffts.\n",indent);
    printf("%s   Calling combine...\n",indent);
    #endif
    InvokeGPUKernel(combine,numBlocks,blockSize,d_grad,d_x,d_y,d_z);
    #ifdef VerboseSolver
    printf("%s      Called combine.\n",indent);
    printf("%s   Freeing d_x, d_y, d_z...\n",indent);
    #endif
    cudaCall(cudaFree,d_x);
    cudaCall(cudaFree,d_y);
    cudaCall(cudaFree,d_z);
    #ifdef VerboseSolver
    printf("%s      Freed d_x, d_y, d_z.\n",indent);
    #endif
}
References backward_fft(), combine(), cudaCall, deviceFFT_t, do_return(), forward_fft(), getIndent, InvokeGPUKernel, and kspace_solve_gradient().
SolveGradient() [2/2]
void HACCGPM::serial::SolveGradient (HACCGPM::Params & params, HACCGPM::serial::MemoryManager & mem, int calls = 0)
Definition at line 252 of file solver.cu.
{
    HACCGPM::serial::SolveGradient(mem.d_grad,mem.d_grid,mem.d_greens,params.ng,params.blockSize,calls);
}
References do_return(), and SolveGradient().
Referenced by serial(), and SolveGradient().
UpdatePositions() [1/2]
void HACCGPM::serial::UpdatePositions (float4 * d_pos, float4 * d_vel, HACCGPM::Timestepper ts, float frac, int ng, int blockSize, int calls = 0)
Definition at line 167 of file pm_actions.cu.
{
    CPUTimer_t start = CPUTimer();
    int numBlocks = (ng*ng*ng)/blockSize;
    float prefactor = ((ts.deltaT)/(ts.aa * ts.aa * ts.adot)) * frac;
    getIndent(calls);
    #ifdef VerboseUpdate
    printf("%sUpdate Positions was called with\n%s   blockSize %d\n%s   numBlocks %d\n%s   frac %g\n%s   prefactor %g\n",indent,indent,blockSize,indent,numBlocks,indent,frac,indent,prefactor);
    #endif
    UPDATE_POS_KERNEL_TIME += InvokeGPUKernel(UpdatePosKernel,numBlocks,blockSize,d_pos,d_vel,prefactor,(float)ng);
    CPUTimer_t end = CPUTimer();
    CPUTimer_t t = end-start;
    printf("%s   UpdatePositions took %llu us\n",indent,t);
    UPDATE_POS_TIME += t;
    UPDATE_POS_CALLS += 1;
}
References CPUTimer(), do_return(), getIndent, InvokeGPUKernel, UPDATE_POS_CALLS, UPDATE_POS_KERNEL_TIME, UPDATE_POS_TIME, and UpdatePosKernel().
UpdatePositions() [2/2]
void HACCGPM::serial::UpdatePositions (HACCGPM::Params & params, HACCGPM::serial::MemoryManager & mem, HACCGPM::Timestepper ts, float frac, int calls = 0)
Definition at line 163 of file pm_actions.cu.
{
    HACCGPM::serial::UpdatePositions(mem.d_pos,mem.d_vel,ts,frac,params.ng,params.blockSize,calls);
}
References do_return(), and UpdatePositions().
Referenced by serial(), and UpdatePositions().
UpdateVelocities() [1/2]
void HACCGPM::serial::UpdateVelocities (float4 * d_vel, float4 * d_grad, float4 * d_pos, HACCGPM::Timestepper ts, int ng, int blockSize, int calls = 0)
Definition at line 148 of file pm_actions.cu.
{
    CPUTimer_t start = CPUTimer();
    int numBlocks = (ng*ng*ng)/blockSize;
    getIndent(calls);
    #ifdef VerboseUpdate
    printf("%sUpdate Velocities was called with\n%s   blockSize %d\n%s   numBlocks %d\n",indent,indent,blockSize,indent,numBlocks);
    #endif
    UPDATE_VEL_KERNEL_TIME += InvokeGPUKernel(ICICKernel,numBlocks,blockSize,d_vel,d_grad,d_pos,ts.deltaT,ts.fscal,ng);
    CPUTimer_t end = CPUTimer();
    CPUTimer_t t = end-start;
    printf("%s   UpdateVelocities took %llu us\n",indent,t);
    UPDATE_VEL_TIME += t;
    UPDATE_VEL_CALLS += 1;
}
References CPUTimer(), do_return(), getIndent, ICICKernel(), InvokeGPUKernel, UPDATE_VEL_CALLS, UPDATE_VEL_KERNEL_TIME, and UPDATE_VEL_TIME.
UpdateVelocities() [2/2]
void HACCGPM::serial::UpdateVelocities (HACCGPM::Params & params, HACCGPM::serial::MemoryManager & mem, HACCGPM::Timestepper ts, int calls = 0)
Definition at line 144 of file pm_actions.cu.
{
    HACCGPM::serial::UpdateVelocities(mem.d_vel,mem.d_grad,mem.d_pos,ts,params.ng,params.blockSize,calls);
}
References do_return(), and UpdateVelocities().
Referenced by serial(), and UpdateVelocities().
writeOutput() [1/2]
void HACCGPM::serial::writeOutput (char * fname, float4 * d_pos, float4 * d_vel, int ng, int calls = 0)
Definition at line 12 of file io.cu.
{
    getIndent(calls);
    printf("%swriteOutput was called\n",indent);
    CPUTimer_t start = CPUTimer();
    int n_particles = ng*ng*ng;
    float* h_pos = (float*)malloc(sizeof(float)*4*n_particles);
    float* h_vel = (float*)malloc(sizeof(float)*4*n_particles);
    cudaCall(cudaMemcpy, h_pos, d_pos, sizeof(float)*ng*ng*ng*4, cudaMemcpyDeviceToHost);
    cudaCall(cudaMemcpy, h_vel, d_vel, sizeof(float)*ng*ng*ng*4, cudaMemcpyDeviceToHost);
    FILE *fp;
    fp = fopen(fname, "w+");
    fwrite(h_pos,sizeof(float),4*n_particles,fp);
    fwrite(h_vel,sizeof(float),4*n_particles,fp);
    fclose(fp);
    free(h_pos);
    free(h_vel);
    CPUTimer_t end = CPUTimer();
    CPUTimer_t t = end-start;
    printf("%s   writeOutput took %llu us\n",indent,t);
    OUTPUT_CALLS++;
    OUTPUT_TIME += t;
}
References CPUTimer(), cudaCall, do_return(), getIndent, OUTPUT_CALLS, and OUTPUT_TIME.
writeOutput() [2/2]
void HACCGPM::serial::writeOutput (HACCGPM::Params & params, HACCGPM::serial::MemoryManager & mem, char * fname, int calls = 0)
Definition at line 8 of file io.cu.
{
    HACCGPM::serial::writeOutput(fname,mem.d_pos,mem.d_vel,params.ng,calls);
}
References do_return(), and writeOutput().
Referenced by serial(), and writeOutput().