HACC_GPM: /home/hqureshi/HACC_GPM/src/particle_transfer/cuda/combine_particles.cu File Reference
combine_particles.cu File Reference
#include "../kernels.hpp"
Functions
__global__ void combineParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, const float4 *__restrict d_swap, int *d_count, int n_new, int n_particles)
CPUTimer_t launch_combine_particles (float4 *d_pos, float4 *d_vel, float4 *d_swap, int *d_count, int n_new, int n_particles, int world_rank, int numBlocks, int blockSize, int calls)
Function Documentation
combineParticles()
__global__ void combineParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, const float4 *__restrict d_swap, int * d_count, int n_new, int n_particles)
Definition at line 3 of file combine_particles.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= n_particles)return;
    float4 my_particle = __ldg(&d_pos[idx]);
    if (!(my_particle.w < -1))return;
    int my_idx = atomicAdd(d_count,1);
    if (my_idx >= n_new)return;
    float4 new_pos = __ldg(&d_swap[my_idx*2]);
    float4 new_vel = __ldg(&d_swap[(my_idx*2) + 1]);
    d_pos[idx] = new_pos;
    d_vel[idx] = new_vel;
}
References do_return().
Referenced by launch_combine_particles().
launch_combine_particles()
CPUTimer_t launch_combine_particles (float4 * d_pos, float4 * d_vel, float4 * d_swap, int * d_count, int n_new, int n_particles, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 17 of file combine_particles.cu.
{
    getIndent(calls);
    return InvokeGPUKernelParallel(combineParticles,numBlocks,blockSize,d_pos,d_vel,d_swap,d_count,n_new,n_particles);
}
References combineParticles(), do_return(), getIndent, and InvokeGPUKernelParallel.
Referenced by HACCGPM::parallel::insertParticles().