HACC_GPM: /home/hqureshi/HACC_GPM/src/initial_conditions/cuda/place_particles_initializer.cu File Reference
place_particles_initializer.cu File Reference
#include "../ic_kernels.hpp"
Functions
__global__ void placeParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double dotDelta, double rl, double a, double deltaT, double fscal, int ng)
__global__ void placeParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double dotDelta, double rl, double a, double deltaT, double fscal, int ng, int nx, int ny, int nz, int nlocal, int world_rank)
void launch_place_particles (float4 *d_pos, float4 *d_vel, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, double delta, double dotDelta, double rl, double z_ini, double deltaT, double fscal, int ng, int numBlocks, int blockSize, int calls)
void launch_place_particles (float4 *d_pos, float4 *d_vel, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, double delta, double dotDelta, double rl, double z_ini, double deltaT, double fscal, int ng, int nlocal, int3 local_grid_size, int world_rank, int numBlocks, int blockSize, int calls)
Function Documentation
launch_place_particles() [1/2]
void launch_place_particles (float4 * d_pos, float4 * d_vel, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, double delta, double dotDelta, double rl, double z_ini, double deltaT, double fscal, int ng, int nlocal, int3 local_grid_size, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 64 of file place_particles_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernelParallel(placeParticles,numBlocks,blockSize,d_pos,d_vel,d_x,d_y,d_z,delta,dotDelta,rl,1/(1+z_ini),deltaT,fscal,ng,local_grid_size.x,local_grid_size.y,local_grid_size.z, nlocal, world_rank);
}
References do_return(), getIndent, InvokeGPUKernelParallel, placeParticles(), and world_rank.
launch_place_particles() [2/2]
void launch_place_particles (float4 * d_pos, float4 * d_vel, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, double delta, double dotDelta, double rl, double z_ini, double deltaT, double fscal, int ng, int numBlocks, int blockSize, int calls)
Definition at line 59 of file place_particles_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernel(placeParticles,numBlocks,blockSize,d_pos,d_vel,d_x,d_y,d_z,delta,dotDelta,rl,1/(1+z_ini),deltaT,fscal,ng);
}
References do_return(), getIndent, InvokeGPUKernel, and placeParticles().
Referenced by HACCGPM::parallel::GenerateDisplacementIC(), and HACCGPM::serial::GenerateDisplacementIC().
placeParticles() [1/2]
__global__ void placeParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double dotDelta, double rl, double a, double deltaT, double fscal, int ng)
Definition at line 3 of file place_particles_initializer.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    float4 my_particle = make_float4(idx3d.x,idx3d.y,idx3d.z,idx);
    deviceFFT_t thisSx = __ldg(&outSx[idx]);
    deviceFFT_t thisSy = __ldg(&outSy[idx]);
    deviceFFT_t thisSz = __ldg(&outSz[idx]);
    float3 s = make_float3(thisSx.x,thisSy.x,thisSz.x);
    float velA = a - (deltaT * 0.5f);
    float velMul = (velA * velA * dotDelta * fscal);
    float4 my_vel = make_float4(velMul*s.x,velMul*s.y,velMul*s.z,idx);
    my_particle.x += delta * s.x + ng;
    my_particle.x = fmod(my_particle.x,(float)ng);
    my_particle.y += delta * s.y + ng;
    my_particle.y = fmod(my_particle.y,(float)ng);
    my_particle.z += delta * s.z + ng;
    my_particle.z = fmod(my_particle.z,(float)ng);
    d_pos[idx] = my_particle;
    d_vel[idx] = my_vel;
}
References deviceFFT_t, do_return(), and HACCGPM::serial::get_index().
Referenced by launch_place_particles(), and launch_place_particles().
placeParticles() [2/2]
__global__ void placeParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, deviceFFT_t *__restrict outSx, deviceFFT_t *__restrict outSy, deviceFFT_t *__restrict outSz, double delta, double dotDelta, double rl, double a, double deltaT, double fscal, int ng, int nx, int ny, int nz, int nlocal, int world_rank)
Definition at line 31 of file place_particles_initializer.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    int3 idx3d = HACCGPM::parallel::get_local_index(idx,nx,ny,nz);
    float4 my_particle = make_float4(idx3d.x,idx3d.y,idx3d.z,idx + nlocal*world_rank);
    deviceFFT_t thisSx = __ldg(&outSx[idx]);
    deviceFFT_t thisSy = __ldg(&outSy[idx]);
    deviceFFT_t thisSz = __ldg(&outSz[idx]);
    float3 s = make_float3(thisSx.x,thisSy.x,thisSz.x);
    float velA = a - (deltaT * 0.5f);
    float velMul = (velA * velA * dotDelta * fscal);
    float4 my_vel = make_float4(velMul*s.x,velMul*s.y,velMul*s.z,idx + nlocal*world_rank);
    my_particle.x += delta * s.x;
    my_particle.y += delta * s.y;
    my_particle.z += delta * s.z;
    d_pos[idx] = my_particle;
    d_vel[idx] = my_vel;
}
References deviceFFT_t, do_return(), HACCGPM::parallel::get_local_index(), and world_rank.