HACC_GPM: /home/hqureshi/HACC_GPM/power.cu File Reference
/home/hqureshi/HACC_GPM/power.cu File Reference
#include "haccgpm.hpp"
#include <stdlib.h>
#include <stdio.h>
Macros
#define VerbosePower
Functions
__global__ void scalePower (const deviceFFT_t *__restrict data, hostFFT_t *__restrict out, double ng, double rl)
__global__ void scalePower (deviceFFT_t *__restrict data, double ng, double rl)
__global__ void PkCICFilter (double *__restrict grid, int ng, int folds)
__global__ void PkCICFilter (deviceFFT_t *__restrict grid, int ng, int folds)
__global__ void foldParticles (float4 *__restrict d_pos, double ng)
__global__ void ScaleParticles (float4 *__restrict d_pos, double oldNg, double newNg)
__global__ void cpy (float4 *__restrict dest, const float4 *__restrict source)
__global__ void BinPower (const hostFFT_t *__restrict d_powerSpectrum, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng)
__global__ void BinPower (const deviceFFT_t *__restrict d_grid, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng)
Variables
CPUTimer_t POWER_TIME = 0
int POWER_CALLS = 0
CPUTimer_t POWER_KERNEL_TIME = 0
Macro Definition Documentation
VerbosePower
#define VerbosePower
Definition at line 5 of file power.cu.
Function Documentation
BinPower() [1/2]
__global__ void BinPower (const deviceFFT_t *__restrict d_grid, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng)
Definition at line 167 of file power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx == 0){
        return;
    }
    if (idx == ((ng/2)*(ng)*(ng) + (ng/2)*ng + (ng/2))){
        return;
    }
    double d = ((2*M_PI)/(((double)(rl))));
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    float3 kmodes = HACCGPM::serial::get_kmodes(idx3d,ng,d);
    deviceFFT_t this_val = __ldg(&d_grid[idx]);
    float kbin = sqrtf(kmodes.x*kmodes.x + kmodes.y*kmodes.y + kmodes.z*kmodes.z) - minK;
    int indx = (int)(kbin/binDelta);
    atomicAdd(&d_binVals[indx],this_val.x);
    atomicAdd(&d_binCounts[indx],1);
}
References deviceFFT_t, HACCGPM::serial::get_index(), and HACCGPM::serial::get_kmodes().
BinPower() [2/2]
__global__ void BinPower (const hostFFT_t *__restrict d_powerSpectrum, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng)
Definition at line 141 of file power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx == 0){
        return;
    }
    if (idx == ((ng/2)*(ng)*(ng) + (ng/2)*ng + (ng/2))){
        return;
    }
    double d = ((2*M_PI)/(((double)(rl))));
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    float3 kmodes = HACCGPM::serial::get_kmodes(idx3d,ng,d);
    hostFFT_t this_val = __ldg(&d_powerSpectrum[idx]);
    float kbin = sqrtf(kmodes.x*kmodes.x + kmodes.y*kmodes.y + kmodes.z*kmodes.z) - minK;
    int indx = (int)(kbin/binDelta);
    atomicAdd(&d_binVals[indx],this_val);
    atomicAdd(&d_binCounts[indx],1);
}
References HACCGPM::serial::get_index(), HACCGPM::serial::get_kmodes(), and hostFFT_t.
Referenced by HACCGPM::serial::GetPowerSpectrum().
cpy()
__global__ void cpy (float4 *__restrict dest, const float4 *__restrict source)
Definition at line 135 of file power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    //printf("%g %g %g\n",source[idx],source[idx],source[idx]);
    dest[idx] = __ldg(&source[idx]);
}
Referenced by HACCGPM::serial::GetPowerSpectrum().
foldParticles()
__global__ void foldParticles (float4 *__restrict d_pos, double ng)
Definition at line 101 of file power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    float4 my_particle = __ldg(&d_pos[idx]);
    my_particle.x /= ng;
    if (my_particle.x >= 0.5){
        my_particle.x -= 0.5;
    }
    my_particle.x *= 2 * ng;
    my_particle.y /= ng;
    if (my_particle.y >= 0.5){
        my_particle.y -= 0.5;
    }
    my_particle.y *= 2 * ng;
    my_particle.z /= ng;
    if (my_particle.z >= 0.5){
        my_particle.z -= 0.5;
    }
    my_particle.z *= 2 * ng;
    d_pos[idx] = my_particle;
}
Referenced by HACCGPM::serial::GetPowerSpectrum().
PkCICFilter() [1/2]
__global__ void PkCICFilter (deviceFFT_t *__restrict grid, int ng, int folds)
Definition at line 66 of file power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    double d = ((2*M_PI)/(((double)(ng))));
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    float3 kmodes = HACCGPM::serial::get_kmodes(idx3d,ng,d);
    float filt1 = sinf(0.5f * kmodes.x) / (0.5 * kmodes.x);
    filt1 = filt1*filt1;
    filt1 = __frcp_rn(filt1 * filt1);
    if (kmodes.x == 0){
        filt1 = 1.0;
    }
    float filt2 = sinf(0.5f * kmodes.y) / (0.5 * kmodes.y);
    filt2 = filt2*filt2;
    filt2 = __frcp_rn(filt2 * filt2);
    if (kmodes.y == 0){
        filt2 = 1.0;
    }
    float filt3 = sinf(0.5f * kmodes.z) / (0.5 * kmodes.z);
    filt3 = filt3*filt3;
    filt3 = __frcp_rn(filt3 * filt3);
    if (kmodes.z == 0){
        filt3 = 1.0;
    }
    double filter = filt1 * filt2 * filt3;
    deviceFFT_t my_grid = __ldg(&grid[idx]);
    my_grid.x *= filter;
    grid[idx] = my_grid;
}
References deviceFFT_t, HACCGPM::serial::get_index(), and HACCGPM::serial::get_kmodes().
PkCICFilter() [2/2]
__global__ void PkCICFilter (double *__restrict grid, int ng, int folds)
Definition at line 31 of file power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    double d = ((2*M_PI)/(((double)(ng))));
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    float3 kmodes = HACCGPM::serial::get_kmodes(idx3d,ng,d);
    float filt1 = sinf(0.5f * kmodes.x) / (0.5 * kmodes.x);
    filt1 = filt1*filt1;
    filt1 = __frcp_rn(filt1 * filt1);
    if (kmodes.x == 0){
        filt1 = 1.0;
    }
    float filt2 = sinf(0.5f * kmodes.y) / (0.5 * kmodes.y);
    filt2 = filt2*filt2;
    filt2 = __frcp_rn(filt2 * filt2);
    if (kmodes.y == 0){
        filt2 = 1.0;
    }
    float filt3 = sinf(0.5f * kmodes.z) / (0.5 * kmodes.z);
    filt3 = filt3*filt3;
    filt3 = __frcp_rn(filt3 * filt3);
    if (kmodes.z == 0){
        filt3 = 1.0;
    }
    double filter = filt1 * filt2 * filt3;
    double my_grid = __ldg(&grid[idx]);
    my_grid *= filter;
    grid[idx] = my_grid;
}
References HACCGPM::serial::get_index(), and HACCGPM::serial::get_kmodes().
Referenced by HACCGPM::serial::GetPowerSpectrum().
ScaleParticles()
__global__ void ScaleParticles (float4 *__restrict d_pos, double oldNg, double newNg)
Definition at line 125 of file power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    float4 my_particle = __ldg(&d_pos[idx]);
    float mul = newNg/oldNg;
    my_particle.x *= mul;
    my_particle.y *= mul;
    my_particle.z *= mul;
    d_pos[idx] = my_particle;
}
scalePower() [1/2]
__global__ void scalePower (const deviceFFT_t *__restrict data, hostFFT_t *__restrict out, double ng, double rl)
Definition at line 11 of file power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    double scale = (1.0f/(ng*ng*ng)) * (rl/ng);
    deviceFFT_t old = __ldg(&data[idx]);
    hostFFT_t absVal = old.x*old.x + old.y*old.y;
    out[idx] = absVal * scale;
}
References deviceFFT_t, and hostFFT_t.
Referenced by HACCGPM::serial::GetPowerSpectrum().
scalePower() [2/2]
__global__ void scalePower (deviceFFT_t *__restrict data, double ng, double rl)
Definition at line 21 of file power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    double scale = (1.0f/(ng*ng*ng)) * (rl/ng);
    deviceFFT_t old = __ldg(&data[idx]);
    old.x = (old.x * old.x + old.y * old.y) * scale;
    data[idx] = old;
}
References deviceFFT_t.
Variable Documentation
POWER_CALLS
int POWER_CALLS = 0
Definition at line 8 of file power.cu.
Referenced by HACCGPM::serial::GetPowerSpectrum(), and HACCGPM::serial::printPowerTimes().
POWER_KERNEL_TIME
CPUTimer_t POWER_KERNEL_TIME = 0
Definition at line 9 of file power.cu.
Referenced by HACCGPM::serial::GetPowerSpectrum(), and HACCGPM::serial::printPowerTimes().
POWER_TIME
CPUTimer_t POWER_TIME = 0
Definition at line 7 of file power.cu.
Referenced by HACCGPM::serial::GetPowerSpectrum(), and HACCGPM::serial::printPowerTimes().