HACC_GPM: /home/hqureshi/HACC_GPM/src/grid_exchange/gridexchange.cpp File Reference
gridexchange.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <mpi.h>
#include "haccgpm.hpp"
#include "gridexchangekernels.hpp"
Macros
#define VerboseResolve
Functions
template<class ThisDim >
void do_return (float4 *grad, int left_rank, int right_rank, int size, int3 local_grid_size, int3 local_coords, int3 total_grid_dims, int overload, int world_rank, size_t *bytes, CPUTimer_t *mpi_time, int blockSize, int calls)
Variables
int RESOLVE_CALLS = 0
CPUTimer_t RESOLVE_TIME = 0
CPUTimer_t RESOLVE_MPI_TIME = 0
CPUTimer_t RESOLVE_GPU_TIME = 0
size_t RESOLVE_BYTES = 0
Macro Definition Documentation
VerboseResolve
#define VerboseResolve
Definition at line 28 of file gridexchange.cpp.
Function Documentation
do_return()
template<class ThisDim > void do_return (float4 * grad, int left_rank, int right_rank, int size, int3 local_grid_size, int3 local_coords, int3 total_grid_dims, int overload, int world_rank, size_t * bytes, CPUTimer_t * mpi_time, int blockSize, int calls)
Definition at line 31 of file gridexchange.cpp.
{
    getIndent(calls);
    //size = total_grid_dims.x * overload * local_grid_size.z;
    float4* left_x_sends = (float4*)malloc(sizeof(float4)*size);
    float4* left_x_recvs = (float4*)malloc(sizeof(float4)*size);
    float4* right_x_sends = (float4*)malloc(sizeof(float4)*size);
    float4* right_x_recvs = (float4*)malloc(sizeof(float4)*size);
    ThisDim this_dim;
    this_dim.load(left_x_sends,right_x_sends,grad,local_grid_size,total_grid_dims,overload,size,blockSize,world_rank,calls);
    if(world_rank == 0)printf("%sSending...\n",indent);
    CPUTimer_t mpi_start = CPUTimer();
    {
    MPI_Request req;
    MPI_Isend(left_x_sends,size*4,MPI_FLOAT,left_rank,0,MPI_COMM_WORLD,&req);
    MPI_Request_free(&req);
    }
    {
    MPI_Request req;
    MPI_Isend(right_x_sends,size*4,MPI_FLOAT,right_rank,0,MPI_COMM_WORLD,&req);
    MPI_Request_free(&req);
    }
    *bytes += 2*size*sizeof(float4);
    if(world_rank == 0)printf("%s   Sent %lu bytes\n",indent,2*size*sizeof(float4));
    if(world_rank == 0)printf("%sRecieving...\n",indent);
    MPI_Recv(left_x_recvs,size*4,MPI_FLOAT,right_rank,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
    MPI_Recv(right_x_recvs,size*4,MPI_FLOAT,left_rank,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
    if(world_rank == 0)printf("%s   Recieved %lu bytes\n",indent,2*size*sizeof(float4));
    CPUTimer_t mpi_end = CPUTimer();
    *mpi_time += mpi_end - mpi_start;
    MPI_Barrier(MPI_COMM_WORLD);
    free(left_x_sends);
    free(right_x_sends);
    this_dim.store(left_x_recvs,right_x_recvs,grad,local_grid_size,total_grid_dims,overload,size,blockSize,world_rank,calls);
    free(left_x_recvs);
    free(right_x_recvs);
    MPI_Barrier(MPI_COMM_WORLD);
}
References CPUTimer(), getIndent, and world_rank.
Referenced by HACCGPM::CosmoClass::a2z(), HACCGPM::Timestepper::advanceHalfStep(), BinPower(), BinPower(), calc_power_bins(), calcGreens(), HACCGPM::parallel::CIC(), HACCGPM::serial::CIC(), HACCGPM::parallel::CIC(), HACCGPM::serial::CIC(), CICKernel(), CICKernelParallel(), combine(), combine_parallel(), combineParticles(), copy(), cos(), HACCGPM::CosmoClass::CosmoClass(), CPUTimer(), cpy(), HACCGPM::CosmoClass::da_dtau(), HACCGPM::CosmoClass::da_dtau__3(), HACCGPM::CosmoClass::delta(), do_pk_interpolation(), HACCGPM::CosmoClass::dotDelta(), HACCGPM::parallel::GridExchange::fill(), findDuplicates(), float2complex(), float2complex(), foldParticles(), HACCGPM::parallel::GenerateDisplacementIC(), HACCGPM::serial::GenerateDisplacementIC(), GenerateFourierAmplitudes(), GenerateFourierAmplitudesParallel(), GenerateRealRandom(), HACCGPM::serial::get_adot(), HACCGPM::CosmoClass::get_delta_and_dotDelta(), HACCGPM::CosmoClass::get_delta_and_dotDelta(), HACCGPM::serial::get_fscal(), HACCGPM::parallel::get_global_index(), get_gradient(), HACCGPM::serial::get_index(), HACCGPM::get_kmodes(), HACCGPM::parallel::get_local_index(), get_pk_cic_filter(), getGreens(), getGreensParallel(), HACCGPM::parallel::GetPowerSpectrum(), HACCGPM::serial::GetPowerSpectrum(), gpuAssert(), HACCGPM::CosmoClass::GrowthFactor(), HACCGPM::CosmoClass::growths(), ICICKernel(), ICICKernelParallel(), init_count_buffer(), init_load_buffer(), HACCGPM::parallel::InitGreens(), HACCGPM::serial::InitGreens(), initRNG(), initRNG(), HACCGPM::parallel::insertParticles(), HACCGPM::CosmoClass::int_1_da_dtau_3(), interpolatePowerSpectrum(), interpolatePowerSpectrum(), kspace_solve(), kspace_solve_gradient(), kspace_solve_gradient_parallel(), XReturn::load(), YReturn::load(), ZReturn::load(), HACCGPM::parallel::LoadIntoBuffers(), loadXLeft(), loadXLeftKernel(), loadXReturnKernel(), loadXRight(), loadXRightKernel(), loadYLeft(), loadYLeftKernel(), loadYReturnKernel(), loadYRight(), loadYRightKernel(), loadZLeft(), loadZLeftKernel(), loadZReturnKernel(), loadZRight(), loadZRightKernel(), HACCGPM::parallel::MemoryManager::MemoryManager(), HACCGPM::serial::MemoryManager::MemoryManager(), HACCGPM::CosmoClass::odesolve(), omega_nu_massive(), HACCGPM::CosmoClass::Omega_nu_massive(), operator*(), PkCICFilter(), PkCICFilter(), placeParticles(), placeParticles(), print_params(), HACCGPM::serial::printCICTimes(), HACCGPM::parallel::printCICTimes(), HACCGPM::parallel::printGridExchangeBytes(), HACCGPM::parallel::printGridExchangeTimes(), HACCGPM::serial::printOutputTimes(), HACCGPM::serial::printPowerTimes(), HACCGPM::parallel::printTransferBytes(), HACCGPM::parallel::printTransferTimes(), HACCGPM::CosmoClass::read_ipk(), HACCGPM::read_params(), HACCGPM::parallel::GridExchange::resolve(), HACCGPM::CosmoClass::rkck(), HACCGPM::CosmoClass::rkqs(), ScaleAmplitudes(), ScaleFFT(), ScaleParticles(), scalePower(), HACCGPM::parallel::sendPower(), set_invalid(), HACCGPM::Timestepper::setInitialA(), HACCGPM::Timestepper::setInitialZ(), HACCGPM::serial::Solve(), HACCGPM::serial::SolveGradient(), HACCGPM::parallel::SolveGradient(), HACCGPM::parallel::SolveGradient(), HACCGPM::serial::SolveGradient(), XReturn::store(), YReturn::store(), ZReturn::store(), storeXLeft(), storeXLeftKernel(), storeXReturnKernel(), storeXRight(), storeXRightKernel(), storeYLeft(), storeYLeftKernel(), storeYReturnKernel(), storeYRight(), storeYRightKernel(), storeZLeft(), storeZLeftKernel(), storeZReturnKernel(), storeZRight(), storeZRightKernel(), swap_set_invalid(), HACCGPM::Timestepper::Timestepper(), HACCGPM::parallel::timing_stats(), HACCGPM::parallel::TransferParticles(), transformDensityField(), transformDensityField(), HACCGPM::serial::UpdatePositions(), HACCGPM::parallel::UpdatePositions(), HACCGPM::parallel::UpdatePositions(), HACCGPM::serial::UpdatePositions(), UpdatePosKernel(), UpdatePosKernelParallel(), HACCGPM::parallel::UpdateVelocities(), HACCGPM::serial::UpdateVelocities(), HACCGPM::parallel::UpdateVelocities(), HACCGPM::serial::UpdateVelocities(), HACCGPM::serial::writeOutput(), HACCGPM::serial::writeOutput(), writePkOutput(), HACCGPM::parallel::MemoryManager::~MemoryManager(), and HACCGPM::serial::MemoryManager::~MemoryManager().
Variable Documentation
RESOLVE_BYTES
size_t RESOLVE_BYTES = 0
Definition at line 12 of file gridexchange.cpp.
Referenced by HACCGPM::parallel::printGridExchangeBytes(), and HACCGPM::parallel::GridExchange::resolve().
RESOLVE_CALLS
int RESOLVE_CALLS = 0
Definition at line 8 of file gridexchange.cpp.
Referenced by HACCGPM::parallel::printGridExchangeBytes(), HACCGPM::parallel::printGridExchangeTimes(), and HACCGPM::parallel::GridExchange::resolve().
RESOLVE_GPU_TIME
CPUTimer_t RESOLVE_GPU_TIME = 0
Definition at line 11 of file gridexchange.cpp.
Referenced by HACCGPM::parallel::printGridExchangeTimes(), and HACCGPM::parallel::GridExchange::resolve().
RESOLVE_MPI_TIME
CPUTimer_t RESOLVE_MPI_TIME = 0
Definition at line 10 of file gridexchange.cpp.
Referenced by HACCGPM::parallel::printGridExchangeTimes(), and HACCGPM::parallel::GridExchange::resolve().
RESOLVE_TIME
CPUTimer_t RESOLVE_TIME = 0
Definition at line 9 of file gridexchange.cpp.
Referenced by HACCGPM::parallel::printGridExchangeTimes(), and HACCGPM::parallel::GridExchange::resolve().