HACC_GPM: driver Namespace Reference
driver Namespace Reference
Functions
import_analysis_modules (*modules)
find_analysis_modules ()
find_analysis_classes ()
init_analysis_objects (ng, rl, world_size, world_rank, local_coords, local_grid_size)
do_initial_conditions_step (power_spectrum, particles, step, a, z)
do_final_step (power_spectrum, particles, step, a, z)
do_analysis_step (particles, step, a, z)
do_power_spectrum_step (power_spectrum, step, a, z)
Variables
dict context = { 'import_analysis_modules': import_analysis_modules, 'init_analysis_objects': init_analysis_objects, 'do_analysis_step': do_analysis_step, 'do_power_spectrum_step': do_power_spectrum_step, 'do_initial_conditions_step': do_initial_conditions_step, 'do_final_step': do_final_step}
test_context_module = types.ModuleType('pycosmodriver', 'PyCosmoDriver')
Function Documentation
do_analysis_step()
driver.do_analysis_step (particles, step, a, z)
Definition at line 71 of file driver.py.
def do_analysis_step(particles,step,a,z):
    global analysis_objects
    cols = ['id','x','y','z','vx','vy','vz'][:particles.shape[1]]
    particles = pd.DataFrame(particles,columns=cols).astype({'id': 'int64'}).set_index('id')
    for i in analysis_objects:
        i.__set_time__(step,a,z)
        i.__set_particles__(particles)
        i.on_analysis_step()
    sys.stdout.flush()
do_final_step()
driver.do_final_step (power_spectrum, particles, step, a, z)
Definition at line 57 of file driver.py.
def do_final_step(power_spectrum,particles,step,a,z):
    global analysis_objects
    cols = ['id','x','y','z','vx','vy','vz'][:particles.shape[1]]
    particles = pd.DataFrame(particles,columns=cols).astype({'id': 'int64'}).set_index('id')
    pk_cols = ['<k> (h/Mpc)','<P_0(k)> (Mpc/h)^3','ErrorBar (Mpc/h)^3', 'nModes'][:power_spectrum.shape[1]]
    pk = pd.DataFrame(power_spectrum,columns=pk_cols)
    for i in analysis_objects:
        i.__set_time__(step,a,z)
        i.__set_particles__(particles)
        if (i.world_rank == 0):
            i.__set_power_spectrum__(pk)
        i.on_final()
    sys.stdout.flush()
do_initial_conditions_step()
driver.do_initial_conditions_step (power_spectrum, particles, step, a, z)
Definition at line 43 of file driver.py.
def do_initial_conditions_step(power_spectrum,particles,step,a,z):
    global analysis_objects
    cols = ['id','x','y','z','vx','vy','vz'][:particles.shape[1]]
    particles = pd.DataFrame(particles,columns=cols).astype({'id': 'int64'}).set_index('id')
    pk_cols = ['<k> (h/Mpc)','<P_0(k)> (Mpc/h)^3','ErrorBar (Mpc/h)^3', 'nModes'][:power_spectrum.shape[1]]
    pk = pd.DataFrame(power_spectrum,columns=pk_cols)
    for i in analysis_objects:
        i.__set_time__(step,a,z)
        i.__set_particles__(particles)
        if (i.world_rank == 0):
            i.__set_power_spectrum__(pk)
        i.on_initial_conditions()
    sys.stdout.flush()
do_power_spectrum_step()
driver.do_power_spectrum_step (power_spectrum, step, a, z)
Definition at line 81 of file driver.py.
def do_power_spectrum_step(power_spectrum,step,a,z):
    global analysis_objects
    pk_cols = ['<k> (h/Mpc)','<P_0(k)> (Mpc/h)^3','ErrorBar (Mpc/h)^3', 'nModes'][:power_spectrum.shape[1]]
    pk = pd.DataFrame(power_spectrum,columns=pk_cols)
    for i in analysis_objects:
        i.__set_time__(step,a,z)
        i.__set_power_spectrum__(pk)
        i.on_power_spectrum_step()
    sys.stdout.flush()
find_analysis_classes()
driver.find_analysis_classes ()
Definition at line 24 of file driver.py.
def find_analysis_classes():
    analysis_classes = []
    analysis_modules = find_analysis_modules()
    for i in analysis_modules:
        for name, obj in inspect.getmembers(i,inspect.isclass):
            if not obj==pycosmo.PyCosmoAnalysis and issubclass(obj,pycosmo.PyCosmoAnalysis):
                analysis_classes.append(obj)
    return analysis_classes
References find_analysis_modules().
Referenced by init_analysis_objects().
find_analysis_modules()
driver.find_analysis_modules ()
Definition at line 19 of file driver.py.
def find_analysis_modules():
    imported_modules = sys.modules
    analysis_modules = [imported_modules[i] for i in imported_modules if i in globals() and not i in ['sys','pycosmo','inspect','os','types']]
    return analysis_modules
Referenced by find_analysis_classes().
import_analysis_modules()
driver.import_analysis_modules (* modules)
Definition at line 8 of file driver.py.
def import_analysis_modules(*modules):
    for i in modules:
        path = os.path.dirname(os.path.abspath(i))
        sys.path.append(path)
        basename = os.path.basename(i).split('.py')[0]
        if basename.isalnum():
            exec('import ' + basename,globals())
        else:
            print('INVALID PY MODULE:',i)
    sys.stdout.flush()
init_analysis_objects()
driver.init_analysis_objects (ng, rl, world_size, world_rank, local_coords, local_grid_size)
Definition at line 35 of file driver.py.
def init_analysis_objects(ng, rl, world_size, world_rank, local_coords, local_grid_size):
    global analysis_objects
    classes = find_analysis_classes()
    analysis_objects = []
    for i in classes:
        analysis_objects.append(i(ng,rl,world_size,world_rank,local_coords,local_grid_size))
    return analysis_objects
References find_analysis_classes().
Variable Documentation
context
dict driver.context = { 'import_analysis_modules': import_analysis_modules, 'init_analysis_objects': init_analysis_objects, 'do_analysis_step': do_analysis_step, 'do_power_spectrum_step': do_power_spectrum_step, 'do_initial_conditions_step': do_initial_conditions_step, 'do_final_step': do_final_step}
Definition at line 91 of file driver.py.
test_context_module
driver.test_context_module = types.ModuleType('pycosmodriver', 'PyCosmoDriver')
Definition at line 92 of file driver.py.