HACC_GPM: YReturn Class Reference
YReturn Class Reference
#include <gridexchangekernels.hpp>
Public Member Functions
CPUTimer_t load (float4 *h_left, float4 *h_right, float4 *d_in, int3 local_grid_size, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
CPUTimer_t store (float4 *h_left, float4 *h_right, float4 *d_in, int3 local_grid_size, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Detailed Description
Definition at line 33 of file gridexchangekernels.hpp.
Member Function Documentation
load()
CPUTimer_t YReturn::load (float4 * h_left, float4 * h_right, float4 * d_in, int3 local_grid_size, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 155 of file gridreturnkernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    if(world_rank == 0)printf("%sLoading Y Return Buffers\n",indent);
    int n = size;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    float4* d_left; cudaCall(cudaMalloc,&d_left,sizeof(float4)*size);
    float4* d_right; cudaCall(cudaMalloc,&d_right,sizeof(float4)*size);
    gpu_time = InvokeGPUKernelParallel(loadYReturnKernel,numBlocks,blockSize,d_left,d_right,d_in,local_grid_size,ol_grid_size,overload,n);
    cudaCall(cudaMemcpy, h_left, d_left, sizeof(float4)*size, cudaMemcpyDeviceToHost);
    cudaCall(cudaMemcpy, h_right, d_right, sizeof(float4)*size, cudaMemcpyDeviceToHost);
    cudaCall(cudaFree,d_left);
    cudaCall(cudaFree,d_right);
    return gpu_time;
}
References cudaCall, do_return(), getIndent, InvokeGPUKernelParallel, loadYReturnKernel(), and world_rank.
store()
CPUTimer_t YReturn::store (float4 * h_left, float4 * h_right, float4 * d_in, int3 local_grid_size, int3 ol_grid_size, int overload, int size, int blockSize, int world_rank, int calls)
Definition at line 235 of file gridreturnkernels.cu.
{
    getIndent(calls);
    CPUTimer_t gpu_time;
    if(world_rank == 0)printf("%sStoring Y Return Buffers\n",indent);
    int n = size;
    int numBlocks = (n + (blockSize - 1))/blockSize;
    if(world_rank == 0)printf("%s   blockSize = %d\n",indent,blockSize);
    if(world_rank == 0)printf("%s   numBlocks = %d\n",indent,numBlocks);
    if(world_rank == 0)printf("%s           n = %d\n",indent,n);
    if(world_rank == 0)printf("%s        size = %d\n",indent,size);
    float4* d_left; cudaCall(cudaMalloc,&d_left,sizeof(float4)*size);
    float4* d_right; cudaCall(cudaMalloc,&d_right,sizeof(float4)*size);
    cudaCall(cudaMemcpy, d_left, h_left, sizeof(float4)*size, cudaMemcpyHostToDevice);
    cudaCall(cudaMemcpy, d_right, h_right, sizeof(float4)*size, cudaMemcpyHostToDevice);
    gpu_time = InvokeGPUKernelParallel(storeYReturnKernel,numBlocks,blockSize,d_left,d_right,d_out,local_grid_size,ol_grid_size,overload,n);
    cudaCall(cudaFree,d_left);
    cudaCall(cudaFree,d_right);
    return gpu_time;
}
References cudaCall, do_return(), getIndent, InvokeGPUKernelParallel, storeYReturnKernel(), and world_rank.
The documentation for this class was generated from the following files:
/home/hqureshi/HACC_GPM/src/grid_exchange/gridexchangekernels.hpp
/home/hqureshi/HACC_GPM/src/grid_exchange/gridreturnkernels.cu