HACC_GPM: /home/hqureshi/HACC_GPM/src/pm_solver/greens.cu File Reference
greens.cu File Reference
#include <stdlib.h>
#include <stdio.h>
#include <cassert>
#include "haccgpm.hpp"
Macros
#define VerboseGreens
Functions
__device__ __forceinline__ double3 cos (float3 kmodes)
__forceinline__ __device__ double calcGreens (int3 idx3d, int ng)
__global__ void getGreens (hostFFT_t *__restrict d_greens, int ng)
__global__ void getGreensParallel (hostFFT_t *__restrict d_greens, int ng, int3 local_grid_size, int3 local_coords)
Macro Definition Documentation
VerboseGreens
#define VerboseGreens
Definition at line 6 of file greens.cu.
Function Documentation
calcGreens()
__forceinline__ __device__ double calcGreens (int3 idx3d, int ng)
Definition at line 16 of file greens.cu.
{
    if ((idx3d.x == 0) && (idx3d.y == 0) && (idx3d.z == 0))return 0.0;
    float d = ((2*M_PI)/(((float)(ng))));
    double3 c = cos(idx3d * d);
    float3 kmodes = HACCGPM::get_kmodes(idx3d,ng,d);
    double coeff = 0.5 / (ng*ng*ng);
    double out = coeff / (c.x + c.y + c.z - 3.0);
    return out;
}
References cos(), do_return(), and HACCGPM::get_kmodes().
Referenced by getGreens(), and getGreensParallel().
cos()
__device__ __forceinline__ double3 cos (float3 kmodes)
Definition at line 8 of file greens.cu.
{
    double3 out;
    out.x = cos(kmodes.x);
    out.y = cos(kmodes.y);
    out.z = cos(kmodes.z);
    return out;
}
References cos(), and do_return().
Referenced by calcGreens(), and cos().
getGreens()
__global__ void getGreens (hostFFT_t *__restrict d_greens, int ng)
Definition at line 34 of file greens.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    d_greens[idx] = calcGreens(idx3d,ng);
}
References calcGreens(), do_return(), and HACCGPM::serial::get_index().
Referenced by HACCGPM::serial::InitGreens().
getGreensParallel()
__global__ void getGreensParallel (hostFFT_t *__restrict d_greens, int ng, int3 local_grid_size, int3 local_coords)
Definition at line 44 of file greens.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    int n = local_grid_size.x*local_grid_size.y*local_grid_size.z;
    if (idx >= n)return;
    int3 idx3d = HACCGPM::parallel::get_global_index(idx,ng,local_grid_size,local_coords);
    d_greens[idx] = calcGreens(idx3d,ng);
}
References calcGreens(), do_return(), and HACCGPM::parallel::get_global_index().
Referenced by HACCGPM::parallel::InitGreens().