HACC_GPM: /home/hqureshi/HACC_GPM/pycosmotools/test/test.cpp File Reference
test.cpp File Reference
#include "../include/pycosmotools.hpp"
#include <stdlib.h>
#include <stdio.h>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 5 of file test.cpp.
          {
    int local_coords[3] = {0,0,0};
    int local_grid_size[3] = {16,16,16};
    PyCosmoTools pytools(32,8,8,0,local_coords,local_grid_size);
    pytools.loadPython();
    pytools.import((char*)"/home/hqureshi/half-precision-hacc/hacc-halfprecision/pycosmotools/examples/analysis1");
    pytools.initialize();
    float particles[2*7] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13};
    float power_spectrum[2*4] = {0,1,2,3,4,5,6,7};
    pytools.initialConditionsStep(power_spectrum,2,4,particles,2,7,0,0.1,200);
    pytools.analysisStep(particles,2,7,0,0.1,200);
    pytools.powerSpectrumStep(power_spectrum,2,4,0,0.1,200);
    pytools.finalStep(power_spectrum,2,4,particles,2,7,0,0.1,200);
    return 0;
}
References PyCosmoTools::analysisStep(), PyCosmoTools::finalStep(), PyCosmoTools::import(), PyCosmoTools::initialConditionsStep(), PyCosmoTools::initialize(), PyCosmoTools::loadPython(), and PyCosmoTools::powerSpectrumStep().