HACC_GPM: /home/hqureshi/HACC_GPM/src/pm_actions/pm_kernels.hpp File Reference
pm_kernels.hpp File Reference
#include "haccgpm.hpp"
Functions
__global__ void UpdatePosKernel (float4 *__restrict d_pos, const float4 *__restrict d_vel, float prefactor, float ng)
__global__ void UpdatePosKernelParallel (float4 *__restrict d_pos, const float4 *__restrict d_vel, float prefactor, int n)
__global__ void float2complex (deviceFFT_t *__restrict d_out, const float *__restrict d_in, int n)
__global__ void float2complex (deviceFFT_t *__restrict d_out, const float *__restrict d_in, int3 local_grid_size, int overload)
__global__ void CICKernel (float *__restrict grid, const float4 *__restrict my_pos, int ng, float mass)
__global__ void CICKernelParallel (float *__restrict d_grid, const float4 *__restrict d_pos, int ng, int overload, int3 local_grid_size, int n_particles, float mass)
__global__ void ICICKernel (float4 *__restrict d_vel, const float4 *__restrict d_grad, const float4 *__restrict my_pos, double deltaT, double fscal, int ng)
__global__ void ICICKernelParallel (float4 *__restrict d_vel, const float4 *__restrict d_grad, const float4 *__restrict my_pos, double deltaT, double fscal, int overload, int3 local_grid_size, int ng, int n_particles)
Function Documentation
CICKernel()
__global__ void CICKernel (float *__restrict grid, const float4 *__restrict my_pos, int ng, float mass)
Definition at line 3 of file cic_pm.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    float4 my_particle = __ldg(&my_pos[idx]);
    int i = my_particle.x;
    int j = my_particle.y;
    int k = my_particle.z;
    float diffx = (my_particle.x - (float)i);
    float diffy = (my_particle.y - (float)j);
    float diffz = (my_particle.z - (float)k);
    for (int x = 0; x < 2; x++){
        for (int y = 0; y < 2; y++){
            for (int z = 0; z < 2; z++){
                int nx = (i + x)%ng;
                int ny = (j + y)%ng;
                int nz = (k + z)%ng;
                int indx = (nx)*ng*ng + (ny)*ng + nz;
                float dx = diffx;
                if (x == 0){
                    dx = 1 - dx;
                }
                float dy = diffy;
                if (y == 0){
                    dy = 1 - dy;
                }
                float dz = diffz;
                if (z == 0){
                    dz = 1 - dz;
                }
                float mul = dx*dy*dz*mass; //* (1.0f/(ng*ng*ng));
                atomicAdd(&grid[indx],mul);
            }
        }
    }
}
References do_return().
Referenced by HACCGPM::serial::CIC().
CICKernelParallel()
__global__ void CICKernelParallel (float *__restrict d_grid, const float4 *__restrict d_pos, int ng, int overload, int3 local_grid_size, int n_particles, float mass)
Definition at line 43 of file cic_pm.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= n_particles)return;
    float4 my_particle = __ldg(&d_pos[idx]);
    if (my_particle.w < -1)return;
    my_particle.x += (float)overload;
    my_particle.y += (float)overload;
    my_particle.z += (float)overload;
    int3 overload_grid = make_int3(local_grid_size.x + 2*overload, local_grid_size.y + 2*overload, local_grid_size.z + 2*overload);
    int i = my_particle.x;
    int j = my_particle.y;
    int k = my_particle.z;
    float diffx = my_particle.x - ((float)i);
    float diffy = my_particle.y - ((float)j);
    float diffz = my_particle.z - ((float)k);
    for (int x = 0; x < 2; x++){
        for (int y = 0; y < 2; y++){
            for (int z = 0; z < 2; z++){
                int nx = (i + x);
                int ny = (j + y);
                int nz = (k + z);
                if ((nx < 0) || (nx >= overload_grid.x) || (ny < 0) || (ny >= overload_grid.y) || (nz < 0) || (nz >= overload_grid.z))continue;
                int indx = (nx)*(overload_grid.y)*(overload_grid.z) + (ny)*(overload_grid.z) + nz;
                float dx = diffx;
                if (x == 0){
                    dx = 1 - dx;
                }
                float dy = diffy;
                if (y == 0){
                    dy = 1 - dy;
                }
                float dz = diffz;
                if (z == 0){
                    dz = 1 - dz;
                }
                float mul = dx*dy*dz*mass; //* (1.0f/(ng*ng*ng));
                atomicAdd(&d_grid[indx],mul);
            }
        }
    }
}
References do_return().
Referenced by HACCGPM::parallel::CIC().
float2complex() [1/2]
__global__ void float2complex (deviceFFT_t *__restrict d_out, const float *__restrict d_in, int n)
Definition at line 3 of file float_to_complex_pm.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if(idx >= n)return;
    float my_grid = __ldg(&d_in[idx]);
    deviceFFT_t out;
    out.x = my_grid;
    out.y = 0;
    d_out[idx] = out;
}
References deviceFFT_t, and do_return().
Referenced by HACCGPM::parallel::CIC(), and HACCGPM::serial::CIC().
float2complex() [2/2]
__global__ void float2complex (deviceFFT_t *__restrict d_out, const float *__restrict d_in, int3 local_grid_size, int overload)
Definition at line 13 of file float_to_complex_pm.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    int n = (local_grid_size.x + 2*overload)*(local_grid_size.y + 2*overload)*(local_grid_size.z + 2*overload);
    if(idx >= n)return;
    int3 ol_grid_size = make_int3(local_grid_size.x + 2*overload,local_grid_size.y + 2*overload,local_grid_size.z + 2*overload);
    int3 idx3d = HACCGPM::parallel::get_local_index(idx,ol_grid_size.x,ol_grid_size.y,ol_grid_size.z);
    idx3d.x -= overload;
    idx3d.y -= overload;
    idx3d.z -= overload;
    if (idx3d.x < 0)return;
    if (idx3d.y < 0)return;
    if (idx3d.z < 0)return;
    if (idx3d.x >= local_grid_size.x)return;
    if (idx3d.y >= local_grid_size.y)return;
    if (idx3d.z >= local_grid_size.z)return;
    float my_grid = __ldg(&d_in[idx]);
    deviceFFT_t out;
    out.x = my_grid;
    out.y = 0;
    int outidx = idx3d.x * local_grid_size.y * local_grid_size.z + idx3d.y * local_grid_size.z + idx3d.z;
    d_out[outidx] = out;
}
References deviceFFT_t, do_return(), and HACCGPM::parallel::get_local_index().
ICICKernel()
__global__ void ICICKernel (float4 *__restrict d_vel, const float4 *__restrict d_grad, const float4 *__restrict my_pos, double deltaT, double fscal, int ng)
Definition at line 72 of file icic_pm.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    float4 my_particle = __ldg(&my_pos[idx]);
    float3 my_deltaV = make_float3(0.0,0.0,0.0);
    int i = my_particle.x;
    int j = my_particle.y;
    int k = my_particle.z;
    float diffx = (my_particle.x - (float)i);
    float diffy = (my_particle.y - (float)j);
    float diffz = (my_particle.z - (float)k);
    for (int x = 0; x < 2; x++){
        for (int y = 0; y < 2; y++){
            for (int z = 0; z < 2; z++){
                int nx = (i + x)%ng;
                int ny = (j + y)%ng;
                int nz = (k + z)%ng;
                int indx = (nx)*ng*ng + (ny)*ng + nz;
                float dx = diffx;
                if (x == 0){
                    dx = 1 - dx;
                }
                float dy = diffy;
                if (y == 0){
                    dy = 1 - dy;
                }
                float dz = diffz;
                if (z == 0){
                    dz = 1 - dz;
                }
                float4 grad = __ldg(&d_grad[indx]);
                float mul = dx*dy*dz * deltaT * (fscal);//* (1.0f/((double)(ng*ng*ng)));// (1.0f/((double)(ng*ng*ng)));// * deltaT * fscal * (1.0f/((double)(ng*ng*ng)));
                my_deltaV.x += mul*grad.x;
                my_deltaV.y += mul*grad.y;
                my_deltaV.z += mul*grad.z;
                //atomicAdd(&grid[indx].x,(double)mul);
            }
        }
    }
    float4 my_vel = __ldg(&d_vel[idx]);
    my_vel.x += my_deltaV.x;
    my_vel.y += my_deltaV.y;
    my_vel.z += my_deltaV.z;
    d_vel[idx] = my_vel;
}
References do_return().
Referenced by HACCGPM::serial::UpdateVelocities().
ICICKernelParallel()
__global__ void ICICKernelParallel (float4 *__restrict d_vel, const float4 *__restrict d_grad, const float4 *__restrict my_pos, double deltaT, double fscal, int overload, int3 local_grid_size, int ng, int n_particles)
Definition at line 3 of file icic_pm.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= n_particles)return;
    float4 my_particle = __ldg(&my_pos[idx]);
    if (my_particle.w < -1)return;
    my_particle.x += (float)overload;
    my_particle.y += (float)overload;
    my_particle.z += (float)overload;
    int3 overload_grid = make_int3(local_grid_size.x + 2*overload, local_grid_size.y + 2*overload, local_grid_size.z + 2*overload);
    float3 my_deltaV = make_float3(0.0,0.0,0.0);
    int i = my_particle.x;
    int j = my_particle.y;
    int k = my_particle.z;
    float diffx = (my_particle.x - (float)i);
    float diffy = (my_particle.y - (float)j);
    float diffz = (my_particle.z - (float)k);
    for (int x = 0; x < 2; x++){
        for (int y = 0; y < 2; y++){
            for (int z = 0; z < 2; z++){
                int nx = (i + x);
                int ny = (j + y);
                int nz = (k + z);
                if ((nx < 0) || (nx >= overload_grid.x) || (ny < 0) || (ny >= overload_grid.y) || (nz < 0) || (nz >= overload_grid.z))continue;
                int indx = (nx)*(overload_grid.y)*(overload_grid.z) + (ny)*(overload_grid.z) + nz;
                float dx = diffx;
                if (x == 0){
                    dx = 1 - dx;
                }
                float dy = diffy;
                if (y == 0){
                    dy = 1 - dy;
                }
                float dz = diffz;
                if (z == 0){
                    dz = 1 - dz;
                }
                float4 grad = __ldg(&d_grad[indx]);
                float mul = dx*dy*dz * deltaT * (fscal);//* (1.0f/((double)(ng*ng*ng)));// (1.0f/((double)(ng*ng*ng)));// * deltaT * fscal * (1.0f/((double)(ng*ng*ng)));
                my_deltaV.x += mul*grad.x;
                my_deltaV.y += mul*grad.y;
                my_deltaV.z += mul*grad.z;
                //atomicAdd(&grid[indx].x,(double)mul);
            }
        }
    }
    //if (idx < 100){
    //    printf("%g %g %g\n",my_deltaV.x,my_deltaV.y,my_deltaV.z);
    //}
    float4 my_vel = __ldg(&d_vel[idx]);
    my_vel.x += my_deltaV.x;
    my_vel.y += my_deltaV.y;
    my_vel.z += my_deltaV.z;
    d_vel[idx] = my_vel;
}
References do_return().
Referenced by HACCGPM::parallel::UpdateVelocities().
UpdatePosKernel()
__global__ void UpdatePosKernel (float4 *__restrict d_pos, const float4 *__restrict d_vel, float prefactor, float ng)
Definition at line 3 of file update_positions_pm.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    float4 my_pos = __ldg(&d_pos[idx]);
    float4 my_vel = __ldg(&d_vel[idx]);
    my_pos.x += my_vel.x * prefactor;
    my_pos.y += my_vel.y * prefactor;
    my_pos.z += my_vel.z * prefactor;
    my_pos.x = fmod(my_pos.x + ng,ng);
    my_pos.y = fmod(my_pos.y + ng,ng);
    my_pos.z = fmod(my_pos.z + ng,ng);
    //if ((my_pos.x < 0 || my_pos.x >= ng) || (my_pos.y < 0 || my_pos.y >= ng) || (my_pos.z < 0 || my_pos.z >= ng)){
    //    printf("%g %g %g\n",my_pos.x,my_pos.y,my_pos.z);
    //    printf("FUCK!!!\n");
    //}
    d_pos[idx] = my_pos;
}
References do_return().
Referenced by HACCGPM::serial::UpdatePositions().
UpdatePosKernelParallel()
__global__ void UpdatePosKernelParallel (float4 *__restrict d_pos, const float4 *__restrict d_vel, float prefactor, int n)
Definition at line 20 of file update_positions_pm.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= n)return;
    float4 my_pos = __ldg(&d_pos[idx]);
    if (my_pos.w < -1)return;
    float4 my_vel = __ldg(&d_vel[idx]);
    my_pos.x += my_vel.x * prefactor;
    my_pos.y += my_vel.y * prefactor;
    my_pos.z += my_vel.z * prefactor;
    d_pos[idx] = my_pos;
}
References do_return().
Referenced by HACCGPM::parallel::UpdatePositions().