HACC_GPM: /home/hqureshi/HACC_GPM/src/initial_conditions/cuda/read_camb.cu File Reference
read_camb.cu File Reference
#include "../ic_kernels.hpp"
#include "../cambTools/ccamb.h"
Functions
void launch_get_pk (hostFFT_t *d_pkScale, double z, const char *fname, int ng, double rl, int calls)
void launch_get_pk (hostFFT_t *d_pkScale, double z, const char *fname, int ng, double rl, int nlocal, int world_rank, int calls)
Function Documentation
launch_get_pk() [1/2]
void launch_get_pk (hostFFT_t * d_pkScale, double z, const char * fname, int ng, double rl, int calls)
Definition at line 7 of file read_camb.cu.
{
    hostFFT_t* h_tmp = (hostFFT_t*)malloc(sizeof(hostFFT_t)*ng*ng*ng);
    get_pk(fname,h_tmp,z,ng,rl,calls+1);
    cudaCall(cudaMemcpy, d_pkScale, h_tmp, sizeof(hostFFT_t)*ng*ng*ng, cudaMemcpyHostToDevice);
    free(h_tmp);
}
References cudaCall, do_return(), get_pk(), and hostFFT_t.
Referenced by GenerateFourierAmplitudes(), and GenerateFourierAmplitudesParallel().
launch_get_pk() [2/2]
void launch_get_pk (hostFFT_t * d_pkScale, double z, const char * fname, int ng, double rl, int nlocal, int world_rank, int calls)
Definition at line 19 of file read_camb.cu.
{
    hostFFT_t* h_tmp = (hostFFT_t*)malloc(sizeof(hostFFT_t)*nlocal);
    get_pk_parallel(fname,h_tmp,z,ng,rl,nlocal,world_rank,calls+1);
    cudaCall(cudaMemcpy, d_pkScale, h_tmp, sizeof(hostFFT_t)*nlocal, cudaMemcpyHostToDevice);
    free(h_tmp);
}
References cudaCall, do_return(), get_pk_parallel(), hostFFT_t, and world_rank.