HACC_GPM: /home/hqureshi/HACC_GPM/src/pm_solver/kernels.hpp File Reference
kernels.hpp File Reference
#include "haccgpm.hpp"
Functions
CPUTimer_t launch_getgreens (hostFFT_t *__restrict d_greens, int ng, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_getgreens (hostFFT_t *__restrict d_greens, int ng, int nlocal, int3 local_grid_size_vec, int3 grid_coords_vec, int world_rank, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_combine (float4 *d_grad, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_combine (float4 *d_grad, deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, int3 local_grid_size, int3 local_coords, int overload, int nlocal, int ng, int world_rank, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_kspace_solve (deviceFFT_t *d_rho, hostFFT_t *d_greens, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_kspace_solve_gradient (deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, deviceFFT_t *d_rho, hostFFT_t *d_greens, int ng, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_kspace_solve_gradient (deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, deviceFFT_t *d_rho, hostFFT_t *d_greens, int ng, int nlocal, int overload, int3 local_grid_size, int3 local_coords, int world_rank, int numBlocks, int blockSize, int calls)
Function Documentation
launch_combine() [1/2]
CPUTimer_t launch_combine (float4 * d_grad, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, int numBlocks, int blockSize, int calls)
Definition at line 45 of file combine.cu.
{
    getIndent(calls);
    return InvokeGPUKernel(combine,numBlocks,blockSize,d_grad,d_x,d_y,d_z);
}
References combine(), do_return(), getIndent, and InvokeGPUKernel.
Referenced by HACCGPM::serial::SolveGradient(), and HACCGPM::parallel::SolveGradient().
launch_combine() [2/2]
CPUTimer_t launch_combine (float4 * d_grad, deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, int3 local_grid_size, int3 local_coords, int overload, int nlocal, int ng, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 50 of file combine.cu.
{
    getIndent(calls);
    return InvokeGPUKernelParallel(combine_parallel,numBlocks,blockSize,d_grad,d_x,d_y,d_z,local_grid_size,local_coords,overload,nlocal,ng);
}
References combine_parallel(), do_return(), getIndent, and InvokeGPUKernelParallel.
launch_getgreens() [1/2]
CPUTimer_t launch_getgreens (hostFFT_t *__restrict d_greens, int ng, int nlocal, int3 local_grid_size_vec, int3 grid_coords_vec, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 66 of file get_greens.cu.
{
    getIndent(calls);
    return InvokeGPUKernelParallel(getGreensParallelKernel,numBlocks,blockSize,d_greens,ng,local_grid_size_vec,grid_coords_vec);
}
References do_return(), getGreensParallelKernel(), getIndent, and InvokeGPUKernelParallel.
launch_getgreens() [2/2]
CPUTimer_t launch_getgreens (hostFFT_t *__restrict d_greens, int ng, int numBlocks, int blockSize, int calls)
Definition at line 58 of file get_greens.cu.
{
    getIndent(calls);
    return InvokeGPUKernel(getGreensKernel,numBlocks,blockSize,d_greens,ng);
}
References do_return(), getGreensKernel(), getIndent, and InvokeGPUKernel.
Referenced by HACCGPM::parallel::InitGreens(), and HACCGPM::serial::InitGreens().
launch_kspace_solve()
CPUTimer_t launch_kspace_solve (deviceFFT_t * d_rho, hostFFT_t * d_greens, int numBlocks, int blockSize, int calls)
Definition at line 93 of file kspace_solver.cu.
{
    getIndent(calls);
    return InvokeGPUKernel(kspace_solve,numBlocks,blockSize,d_rho,d_greens);
}
References do_return(), getIndent, InvokeGPUKernel, and kspace_solve().
Referenced by HACCGPM::serial::Solve().
launch_kspace_solve_gradient() [1/2]
CPUTimer_t launch_kspace_solve_gradient (deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, deviceFFT_t * d_rho, hostFFT_t * d_greens, int ng, int nlocal, int overload, int3 local_grid_size, int3 local_coords, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 103 of file kspace_solver.cu.
{
    getIndent(calls);
    return InvokeGPUKernelParallel(kspace_solve_gradient_parallel,numBlocks,blockSize,d_x,d_y,d_z,d_rho,d_greens,ng,nlocal,overload,local_grid_size,local_coords);
}
References do_return(), getIndent, InvokeGPUKernelParallel, and kspace_solve_gradient_parallel().
launch_kspace_solve_gradient() [2/2]
CPUTimer_t launch_kspace_solve_gradient (deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, deviceFFT_t * d_rho, hostFFT_t * d_greens, int ng, int numBlocks, int blockSize, int calls)
Definition at line 98 of file kspace_solver.cu.
{
    getIndent(calls);
    return InvokeGPUKernel(kspace_solve_gradient,numBlocks,blockSize,d_x,d_y,d_z,d_rho,d_greens,ng);
}
References do_return(), getIndent, InvokeGPUKernel, and kspace_solve_gradient().
Referenced by HACCGPM::serial::SolveGradient(), and HACCGPM::parallel::SolveGradient().