HACC_GPM: HACCGPM::parallel::GridExchange Class Reference
HACCGPM::parallel::GridExchange Class Reference
#include <haccgpm.hpp>
Public Member Functions
GridExchange ()
GridExchange (int3 local_coords_, int3 local_grid_size_, int3 dims_, int ng_, int world_size_, int world_rank_, int overload_, int blockSize_)
void resolve (float *grid, int calls=0)
void fill (float4 *grad, int calls=0)
Private Attributes
int3 local_coords
int3 local_grid_size
int3 dims
int ng
int world_size
int world_rank
int overload
int blockSize
Detailed Description
Definition at line 233 of file haccgpm.hpp.
Constructor & Destructor Documentation
GridExchange() [1/2]
HACCGPM::parallel::GridExchange::GridExchange ()
Definition at line 14 of file gridexchange.cpp.
{};
GridExchange() [2/2]
HACCGPM::parallel::GridExchange::GridExchange (int3 local_coords_, int3 local_grid_size_, int3 dims_, int ng_, int world_size_, int world_rank_, int overload_, int blockSize_)
Definition at line 16 of file gridexchange.cpp.
                                                                                                                                                                         : local_coords(local_coords_),
                                                                                                                    local_grid_size(local_grid_size_),
                                                                                                                    ng(ng_),
                                                                                                                    world_size(world_size_),
                                                                                                                    world_rank(world_rank_),
                                                                                                                    overload(overload_),
                                                                                                                    blockSize(blockSize_),
                                                                                                                    dims(dims_){};
Member Function Documentation
fill()
void HACCGPM::parallel::GridExchange::fill (float4 * grad, int calls = 0)
Definition at line 89 of file gridexchange.cpp.
{
    getIndent(calls);
    CPUTimer_t mpi_start,mpi_end;
    CPUTimer_t mpi_time = 0;
    size_t bytes = 0;
    #ifdef VerboseResolve
    if(world_rank == 0)printf("%sDoing Grid Exchange Fill (called GridExchange.fill)\n",indent);
    #endif
    int3 total_grid_dims = make_int3(local_grid_size.x + 2*overload,local_grid_size.y + 2*overload,local_grid_size.z + 2*overload);
    int total_grid_size = total_grid_dims.x*total_grid_dims.y*total_grid_dims.z;
    #ifdef VerboseResolve
    if(world_rank == 0)printf("%s   Overload Dimensions: [%d %d %d]\n",indent,total_grid_dims.x,total_grid_dims.y,total_grid_dims.z);
    #endif
    int size, left_rank, right_rank;
    int3 left_coords, right_coords;
    size = overload * local_grid_size.y * local_grid_size.z;
    left_coords = make_int3((local_coords.x-1 + dims.x)%dims.x,local_coords.y,local_coords.z);
    left_rank = left_coords.x * dims.y * dims.z + left_coords.y * dims.z + left_coords.z;
    right_coords = make_int3((local_coords.x+1 + dims.x)%dims.x,local_coords.y,local_coords.z);
    right_rank = right_coords.x * dims.y * dims.z + right_coords.y * dims.z + right_coords.z;
    do_return<XReturn>(grad,left_rank,right_rank,size,local_grid_size,local_coords,total_grid_dims,overload,world_rank,&bytes,&mpi_time,blockSize,calls+1);
    size = total_grid_dims.x * overload * local_grid_size.z;
    left_coords = make_int3(local_coords.x,(local_coords.y-1 + dims.y)%dims.y,local_coords.z);
    left_rank = left_coords.x * dims.y * dims.z + left_coords.y * dims.z + left_coords.z;
    right_coords = make_int3(local_coords.x,(local_coords.y+1 + dims.y)%dims.y,local_coords.z);
    right_rank = right_coords.x * dims.y * dims.z + right_coords.y * dims.z + right_coords.z;
    do_return<YReturn>(grad,left_rank,right_rank,size,local_grid_size,local_coords,total_grid_dims,overload,world_rank,&bytes,&mpi_time,blockSize,calls+1);
    size = total_grid_dims.x * total_grid_dims.y * overload;
    left_coords = make_int3(local_coords.x,local_coords.y,(local_coords.z-1 + dims.z)%dims.z);
    left_rank = left_coords.x * dims.y * dims.z + left_coords.y * dims.z + left_coords.z;
    right_coords = make_int3(local_coords.x,local_coords.y,(local_coords.z+1 + dims.z)%dims.z);
    right_rank = right_coords.x * dims.y * dims.z + right_coords.y * dims.z + right_coords.z;
    do_return<ZReturn>(grad,left_rank,right_rank,size,local_grid_size,local_coords,total_grid_dims,overload,world_rank,&bytes,&mpi_time,blockSize,calls+1);
}
References do_return(), getIndent, and world_rank.
resolve()
void HACCGPM::parallel::GridExchange::resolve (float * grid, int calls = 0)
Definition at line 140 of file gridexchange.cpp.
{
    getIndent(calls);
    #ifdef VerboseResolve
    if(world_rank == 0)printf("%sDoing Grid Exchange Resolve (called GridExchange.resolve)\n",indent);
    #endif
    CPUTimer_t mpi_start,mpi_end;
    CPUTimer_t mpi_time = 0;
    CPUTimer_t gpu_time = 0;
    size_t bytes = 0;
    CPUTimer_t start = CPUTimer();
    int3 total_grid_dims = make_int3(local_grid_size.x + 2*overload,local_grid_size.y + 2*overload,local_grid_size.z + 2*overload);
    int total_grid_size = total_grid_dims.x*total_grid_dims.y*total_grid_dims.z;
    #ifdef VerboseResolve
    if(world_rank == 0)printf("%s   Overload Dimensions: [%d %d %d]\n",indent,total_grid_dims.x,total_grid_dims.y,total_grid_dims.z);
    #endif
    int size, dest_rank, recv_rank;
    int3 dest_coords, recv_coords;
    //X DIMENSION
    size = total_grid_dims.y * total_grid_dims.z * overload;
    dest_coords = make_int3((local_coords.x-1 + dims.x)%dims.x,local_coords.y,local_coords.z);
    dest_rank = dest_coords.x * dims.y * dims.z + dest_coords.y * dims.z + dest_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Send X (left) with size = %d and dest = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,dest_rank,dest_coords.x,dest_coords.y,dest_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    recv_coords = make_int3((local_coords.x+1)%dims.x,local_coords.y,local_coords.z);
    recv_rank = recv_coords.x * dims.y * dims.z + recv_coords.y * dims.z + recv_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Recv X (left) with size = %d and recv = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,recv_rank,recv_coords.x,recv_coords.y,recv_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    float* left_x_sends = (float*)malloc(sizeof(float)*size);
    float* left_x_recvs = (float*)malloc(sizeof(float)*size);
    gpu_time += loadXLeft(left_x_sends,grid,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    {
    MPI_Request req;
    MPI_Isend(left_x_sends,size,MPI_FLOAT,dest_rank,0,MPI_COMM_WORLD,&req);
    MPI_Request_free(&req);
    }
    bytes += size*sizeof(float);
    MPI_Recv(left_x_recvs,size,MPI_FLOAT,recv_rank,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    gpu_time += storeXLeft(grid,left_x_recvs,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    MPI_Barrier(MPI_COMM_WORLD);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    free(left_x_sends);
    free(left_x_recvs);
    dest_coords = make_int3((local_coords.x+1 + dims.x)%dims.x,local_coords.y,local_coords.z);
    dest_rank = dest_coords.x * dims.y * dims.z + dest_coords.y * dims.z + dest_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Send X (left) with size = %d and dest = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,dest_rank,dest_coords.x,dest_coords.y,dest_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    recv_coords = make_int3((local_coords.x-1 + dims.x)%dims.x,local_coords.y,local_coords.z);
    recv_rank = recv_coords.x * dims.y * dims.z + recv_coords.y * dims.z + recv_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Recv X (left) with size = %d and recv = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,recv_rank,recv_coords.x,recv_coords.y,recv_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    float* right_x_sends = (float*)malloc(sizeof(float)*size);
    float* right_x_recvs = (float*)malloc(sizeof(float)*size);
    gpu_time += loadXRight(right_x_sends,grid,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    {
    MPI_Request req;
    MPI_Isend(right_x_sends,size,MPI_FLOAT,dest_rank,0,MPI_COMM_WORLD,&req);
    MPI_Request_free(&req);
    }
    bytes += size*sizeof(float);
    MPI_Recv(right_x_recvs,size,MPI_FLOAT,recv_rank,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    gpu_time += storeXRight(grid,right_x_recvs,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    MPI_Barrier(MPI_COMM_WORLD);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    free(right_x_sends);
    free(right_x_recvs);
    //Y Left
    size = (total_grid_dims.x - 2*overload) * total_grid_dims.z * overload;
    dest_coords = make_int3(local_coords.x,(local_coords.y-1 + dims.y)%dims.y,local_coords.z);
    dest_rank = dest_coords.x * dims.y * dims.z + dest_coords.y * dims.z + dest_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Send X (left) with size = %d and dest = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,dest_rank,dest_coords.x,dest_coords.y,dest_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    recv_coords = make_int3(local_coords.x,(local_coords.y+1 + dims.y)%dims.y,local_coords.z);
    recv_rank = recv_coords.x * dims.y * dims.z + recv_coords.y * dims.z + recv_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Recv X (left) with size = %d and recv = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,recv_rank,recv_coords.x,recv_coords.y,recv_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    float* left_y_sends = (float*)malloc(sizeof(float)*size);
    float* left_y_recvs = (float*)malloc(sizeof(float)*size);
    gpu_time += loadYLeft(left_y_sends,grid,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    {
    MPI_Request req;
    MPI_Isend(left_y_sends,size,MPI_FLOAT,dest_rank,0,MPI_COMM_WORLD,&req);
    MPI_Request_free(&req);
    }
    bytes += size*sizeof(float);
    MPI_Recv(left_y_recvs,size,MPI_FLOAT,recv_rank,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    gpu_time += storeYLeft(grid,left_y_recvs,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    MPI_Barrier(MPI_COMM_WORLD);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    free(left_y_sends);
    free(left_y_recvs);
    //Y right
    //size = (total_grid_dims.x - 2*overload) * total_grid_dims.z * overload;
    dest_coords = make_int3(local_coords.x,(local_coords.y+1 + dims.y)%dims.y,local_coords.z);
    dest_rank = dest_coords.x * dims.y * dims.z + dest_coords.y * dims.z + dest_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Send X (left) with size = %d and dest = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,dest_rank,dest_coords.x,dest_coords.y,dest_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    recv_coords = make_int3(local_coords.x,(local_coords.y-1 + dims.y)%dims.y,local_coords.z);
    recv_rank = recv_coords.x * dims.y * dims.z + recv_coords.y * dims.z + recv_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Recv X (left) with size = %d and recv = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,recv_rank,recv_coords.x,recv_coords.y,recv_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    float* right_y_sends = (float*)malloc(sizeof(float)*size);
    float* right_y_recvs = (float*)malloc(sizeof(float)*size);
    gpu_time += loadYRight(right_y_sends,grid,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    {
    MPI_Request req;
    MPI_Isend(right_y_sends,size,MPI_FLOAT,dest_rank,0,MPI_COMM_WORLD,&req);
    MPI_Request_free(&req);
    }
    bytes += size*sizeof(float);
    MPI_Recv(right_y_recvs,size,MPI_FLOAT,recv_rank,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    gpu_time += storeYRight(grid,right_y_recvs,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    MPI_Barrier(MPI_COMM_WORLD);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    free(right_y_sends);
    free(right_y_recvs);
    //Z Left
    size = (total_grid_dims.x - 2*overload) * (total_grid_dims.y - 2*overload) * overload;
    dest_coords = make_int3(local_coords.x,local_coords.y,(local_coords.z-1 + dims.z)%dims.z);
    dest_rank = dest_coords.x * dims.y * dims.z + dest_coords.y * dims.z + dest_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Send X (left) with size = %d and dest = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,dest_rank,dest_coords.x,dest_coords.y,dest_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    recv_coords = make_int3(local_coords.x,local_coords.y,(local_coords.z+1 + dims.z)%dims.z);
    recv_rank = recv_coords.x * dims.y * dims.z + recv_coords.y * dims.z + recv_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Recv X (left) with size = %d and recv = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,recv_rank,recv_coords.x,recv_coords.y,recv_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    float* left_z_sends = (float*)malloc(sizeof(float)*size);
    float* left_z_recvs = (float*)malloc(sizeof(float)*size);
    gpu_time += loadZLeft(left_z_sends,grid,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    {
    MPI_Request req;
    MPI_Isend(left_z_sends,size,MPI_FLOAT,dest_rank,0,MPI_COMM_WORLD,&req);
    MPI_Request_free(&req);
    }
    bytes += size*sizeof(float);
    MPI_Recv(left_z_recvs,size,MPI_FLOAT,recv_rank,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    gpu_time += storeZLeft(grid,left_z_recvs,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    MPI_Barrier(MPI_COMM_WORLD);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    free(left_z_sends);
    free(left_z_recvs);
    //Y right
    //size = (total_grid_dims.x - 2*overload) * total_grid_dims.z * overload;
    dest_coords =  make_int3(local_coords.x,local_coords.y,(local_coords.z+1 + dims.z)%dims.z);
    dest_rank = dest_coords.x * dims.y * dims.z + dest_coords.y * dims.z + dest_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Send X (left) with size = %d and dest = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,dest_rank,dest_coords.x,dest_coords.y,dest_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    recv_coords =  make_int3(local_coords.x,local_coords.y,(local_coords.z-1 + dims.z)%dims.z);
    recv_rank = recv_coords.x * dims.y * dims.z + recv_coords.y * dims.z + recv_coords.z;
    #ifdef VerboseResolveSends
    MPI_Barrier(MPI_COMM_WORLD);
    for (int i = 0; i < world_size; i++){
        if(i == world_rank)printf("%s      Rank %d ([%d %d %d]): Recv X (left) with size = %d and recv = %d ([%d %d %d])\n",indent,world_rank,local_coords.x,local_coords.y,local_coords.z,size,recv_rank,recv_coords.x,recv_coords.y,recv_coords.z);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);
    #endif
    float* right_z_sends = (float*)malloc(sizeof(float)*size);
    float* right_z_recvs = (float*)malloc(sizeof(float)*size);
    gpu_time += loadZRight(right_z_sends,grid,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    {
    MPI_Request req;
    MPI_Isend(right_z_sends,size,MPI_FLOAT,dest_rank,0,MPI_COMM_WORLD,&req);
    MPI_Request_free(&req);
    }
    bytes += size*sizeof(float);
    MPI_Recv(right_z_recvs,size,MPI_FLOAT,recv_rank,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    gpu_time += storeZRight(grid,right_z_recvs,total_grid_dims,overload,size,blockSize,world_rank,calls+1);
    mpi_start = CPUTimer();
    MPI_Barrier(MPI_COMM_WORLD);
    mpi_end = CPUTimer();
    mpi_time += mpi_end - mpi_start;
    free(right_z_sends);
    free(right_z_recvs);
    CPUTimer_t end = CPUTimer();
    RESOLVE_CALLS++;
    RESOLVE_TIME += end-start;
    RESOLVE_MPI_TIME += mpi_time;
    RESOLVE_GPU_TIME += gpu_time;
    RESOLVE_BYTES += bytes;
    #ifdef VerboseResolve
    if(world_rank == 0)printf("%s   Grid Exchange Resolve took %llu us\n",indent,end-start);
    #endif
}
References CPUTimer(), do_return(), getIndent, loadXLeft(), loadXRight(), loadYLeft(), loadYRight(), loadZLeft(), loadZRight(), RESOLVE_BYTES, RESOLVE_CALLS, RESOLVE_GPU_TIME, RESOLVE_MPI_TIME, RESOLVE_TIME, storeXLeft(), storeXRight(), storeYLeft(), storeYRight(), storeZLeft(), storeZRight(), and world_rank.
Member Data Documentation
blockSize
int HACCGPM::parallel::GridExchange::blockSize private
Definition at line 243 of file haccgpm.hpp.
dims
int3 HACCGPM::parallel::GridExchange::dims private
Definition at line 238 of file haccgpm.hpp.
local_coords
int3 HACCGPM::parallel::GridExchange::local_coords private
Definition at line 236 of file haccgpm.hpp.
local_grid_size
int3 HACCGPM::parallel::GridExchange::local_grid_size private
Definition at line 237 of file haccgpm.hpp.
ng
int HACCGPM::parallel::GridExchange::ng private
Definition at line 239 of file haccgpm.hpp.
overload
int HACCGPM::parallel::GridExchange::overload private
Definition at line 242 of file haccgpm.hpp.
world_rank
int HACCGPM::parallel::GridExchange::world_rank private
Definition at line 241 of file haccgpm.hpp.
world_size
int HACCGPM::parallel::GridExchange::world_size private
Definition at line 240 of file haccgpm.hpp.
The documentation for this class was generated from the following files:
/home/hqureshi/HACC_GPM/src/haccgpm.hpp
/home/hqureshi/HACC_GPM/src/grid_exchange/gridexchange.cpp