HACC_GPM: /home/hqureshi/HACC_GPM/src/pm_solver/cuda/kspace_solver.cu File Reference
kspace_solver.cu File Reference
#include "../kernels.hpp"
Functions
__device__ __forceinline__ float get_gradient (float kmode)
__global__ void kspace_solve (deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens)
__global__ void kspace_solve_gradient (deviceFFT_t *__restrict d_x, deviceFFT_t *__restrict d_y, deviceFFT_t *__restrict d_z, const deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens, int ng)
__global__ void kspace_solve_gradient_parallel (deviceFFT_t *__restrict d_x, deviceFFT_t *__restrict d_y, deviceFFT_t *__restrict d_z, const deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens, int ng, int nlocal, int overload, int3 local_grid_size, int3 local_coords)
CPUTimer_t launch_kspace_solve (deviceFFT_t *d_rho, hostFFT_t *d_greens, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_kspace_solve_gradient (deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, deviceFFT_t *d_rho, hostFFT_t *d_greens, int ng, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_kspace_solve_gradient (deviceFFT_t *d_x, deviceFFT_t *d_y, deviceFFT_t *d_z, deviceFFT_t *d_rho, hostFFT_t *d_greens, int ng, int nlocal, int overload, int3 local_grid_size, int3 local_coords, int world_rank, int numBlocks, int blockSize, int calls)
Function Documentation
get_gradient()
__device__ __forceinline__ float get_gradient (float kmode)
Definition at line 4 of file kspace_solver.cu.
{
    return sinf(kmode);
}
References do_return().
Referenced by kspace_solve_gradient(), and kspace_solve_gradient_parallel().
kspace_solve()
__global__ void kspace_solve (deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens)
Definition at line 8 of file kspace_solver.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    hostFFT_t greens = __ldg(&d_greens[idx]);
    deviceFFT_t rho = __ldg(&d_rho[idx]);
    rho.x *= greens;
    rho.y *= greens;
    d_rho[idx] = rho;
}
References deviceFFT_t, do_return(), and hostFFT_t.
Referenced by launch_kspace_solve().
kspace_solve_gradient()
__global__ void kspace_solve_gradient (deviceFFT_t *__restrict d_x, deviceFFT_t *__restrict d_y, deviceFFT_t *__restrict d_z, const deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens, int ng)
Definition at line 18 of file kspace_solver.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    double d = ((2*M_PI)/(((double)(ng))));
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    float3 kmodes = HACCGPM::get_kmodes(idx3d,ng,d);
    hostFFT_t greens = __ldg(&d_greens[idx]);
    float3 c;
    c.x = -get_gradient(kmodes.x) * greens;
    c.y = -get_gradient(kmodes.y) * greens;
    c.z = -get_gradient(kmodes.z) * greens;
    deviceFFT_t rho = __ldg(&d_rho[idx]);
    deviceFFT_t out_x;
    out_x.x = -c.x * rho.y;
    out_x.y = c.x * rho.x;
    d_x[idx] = out_x;
    deviceFFT_t out_y;
    out_y.x = -c.y * rho.y;
    out_y.y = c.y * rho.x;
    d_y[idx] = out_y;
    deviceFFT_t out_z;
    out_z.x = -c.z * rho.y;
    out_z.y = c.z * rho.x;
    d_z[idx] = out_z;
}
References deviceFFT_t, do_return(), get_gradient(), HACCGPM::serial::get_index(), HACCGPM::get_kmodes(), and hostFFT_t.
Referenced by launch_kspace_solve_gradient().
kspace_solve_gradient_parallel()
__global__ void kspace_solve_gradient_parallel (deviceFFT_t *__restrict d_x, deviceFFT_t *__restrict d_y, deviceFFT_t *__restrict d_z, const deviceFFT_t *__restrict d_rho, const hostFFT_t *__restrict d_greens, int ng, int nlocal, int overload, int3 local_grid_size, int3 local_coords)
Definition at line 54 of file kspace_solver.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    double d = ((2*M_PI)/(((double)(ng))));
    int3 idx3d = HACCGPM::parallel::get_global_index(idx,ng,local_grid_size,local_coords);
    float3 kmodes = HACCGPM::get_kmodes(idx3d,ng,d);
    hostFFT_t greens = __ldg(&d_greens[idx]);
    float3 c;
    c.x = -get_gradient(kmodes.x) * greens;
    c.y = -get_gradient(kmodes.y) * greens;
    c.z = -get_gradient(kmodes.z) * greens;
    deviceFFT_t rho = __ldg(&d_rho[idx]);
    deviceFFT_t out_x;
    out_x.x = -c.x * rho.y;
    out_x.y = c.x * rho.x;
    d_x[idx] = out_x;
    deviceFFT_t out_y;
    out_y.x = -c.y * rho.y;
    out_y.y = c.y * rho.x;
    d_y[idx] = out_y;
    deviceFFT_t out_z;
    out_z.x = -c.z * rho.y;
    out_z.y = c.z * rho.x;
    d_z[idx] = out_z;
}
References deviceFFT_t, do_return(), HACCGPM::parallel::get_global_index(), get_gradient(), HACCGPM::get_kmodes(), and hostFFT_t.
Referenced by launch_kspace_solve_gradient().
launch_kspace_solve()
CPUTimer_t launch_kspace_solve (deviceFFT_t * d_rho, hostFFT_t * d_greens, int numBlocks, int blockSize, int calls)
Definition at line 93 of file kspace_solver.cu.
{
    getIndent(calls);
    return InvokeGPUKernel(kspace_solve,numBlocks,blockSize,d_rho,d_greens);
}
References do_return(), getIndent, InvokeGPUKernel, and kspace_solve().
Referenced by HACCGPM::serial::Solve().
launch_kspace_solve_gradient() [1/2]
CPUTimer_t launch_kspace_solve_gradient (deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, deviceFFT_t * d_rho, hostFFT_t * d_greens, int ng, int nlocal, int overload, int3 local_grid_size, int3 local_coords, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 103 of file kspace_solver.cu.
{
    getIndent(calls);
    return InvokeGPUKernelParallel(kspace_solve_gradient_parallel,numBlocks,blockSize,d_x,d_y,d_z,d_rho,d_greens,ng,nlocal,overload,local_grid_size,local_coords);
}
References do_return(), getIndent, InvokeGPUKernelParallel, and kspace_solve_gradient_parallel().
launch_kspace_solve_gradient() [2/2]
CPUTimer_t launch_kspace_solve_gradient (deviceFFT_t * d_x, deviceFFT_t * d_y, deviceFFT_t * d_z, deviceFFT_t * d_rho, hostFFT_t * d_greens, int ng, int numBlocks, int blockSize, int calls)
Definition at line 98 of file kspace_solver.cu.
{
    getIndent(calls);
    return InvokeGPUKernel(kspace_solve_gradient,numBlocks,blockSize,d_x,d_y,d_z,d_rho,d_greens,ng);
}
References do_return(), getIndent, InvokeGPUKernel, and kspace_solve_gradient().
Referenced by HACCGPM::serial::SolveGradient(), and HACCGPM::parallel::SolveGradient().