HACC_GPM: /home/hqureshi/HACC_GPM/src/power_spectrum/cuda/bin_power.cu File Reference
bin_power.cu File Reference
#include "power_kernels.hpp"
Functions
__forceinline__ __device__ void calc_power_bins (double *__restrict d_binVals, int *__restrict d_binCounts, double this_val, int idx, int3 idx3d, double minK, double binDelta, double rl, int ng)
__global__ void BinPower (const deviceFFT_t *__restrict d_grid, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng)
__global__ void BinPower (const deviceFFT_t *__restrict d_grid, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng, int nlocal, int world_rank, int3 local_grid_size, int3 local_coords, int3 dims)
Function Documentation
BinPower() [1/2]
__global__ void BinPower (const deviceFFT_t *__restrict d_grid, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng)
Definition at line 18 of file bin_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    deviceFFT_t this_val = __ldg(&d_grid[idx]);
    calc_power_bins(d_binVals,d_binCounts,this_val.x,idx,idx3d,minK,binDelta,rl,ng);
}
References calc_power_bins(), deviceFFT_t, do_return(), and HACCGPM::serial::get_index().
Referenced by HACCGPM::parallel::GetPowerSpectrum(), and HACCGPM::serial::GetPowerSpectrum().
BinPower() [2/2]
__global__ void BinPower (const deviceFFT_t *__restrict d_grid, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng, int nlocal, int world_rank, int3 local_grid_size, int3 local_coords, int3 dims)
Definition at line 30 of file bin_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    int3 idx3d = HACCGPM::parallel::get_global_index(idx,ng,local_grid_size,local_coords);
    deviceFFT_t this_val = __ldg(&d_grid[idx]);
    calc_power_bins(d_binVals,d_binCounts,this_val.x,idx,idx3d,minK,binDelta,rl,ng);
}
References calc_power_bins(), deviceFFT_t, do_return(), and HACCGPM::parallel::get_global_index().
calc_power_bins()
__forceinline__ __device__ void calc_power_bins (double *__restrict d_binVals, int *__restrict d_binCounts, double this_val, int idx, int3 idx3d, double minK, double binDelta, double rl, int ng)
Definition at line 3 of file bin_power.cu.
{
    if ((idx3d.x == 0) && (idx3d.y == 0) && (idx3d.z == 0))return;
    if ((idx3d.x == ng/2) && (idx3d.y == ng/2) && (idx3d.z == ng/2))return;
    double d = (2*M_PI)/(rl);
    float3 kmodes = HACCGPM::get_kmodes(idx3d,ng,d);
    float kbin = sqrtf(kmodes.x*kmodes.x + kmodes.y*kmodes.y + kmodes.z*kmodes.z) - minK;
    int indx = (int)(kbin/binDelta);
    atomicAdd(&d_binVals[indx],this_val);
    atomicAdd(&d_binCounts[indx],1);
}
References do_return(), and HACCGPM::get_kmodes().
Referenced by BinPower(), and BinPower().