HACC_GPM: /home/hqureshi/HACC_GPM/src/initial_conditions/cuda/scale_initializer.cu File Reference
scale_initializer.cu File Reference
#include "../ic_kernels.hpp"
Functions
__global__ void ScaleAmplitudes (deviceFFT_t *__restrict grid, const hostFFT_t *__restrict scale, int nlocal)
void launch_scale_amplitudes (deviceFFT_t *grid, hostFFT_t *scale, int nlocal, int world_rank, int numBlocks, int blockSize, int calls)
void launch_scale_amplitudes (deviceFFT_t *grid, hostFFT_t *scale, int nlocal, int numBlocks, int blockSize, int calls)
__global__ void ScaleFFT (deviceFFT_t *__restrict data, double scale, int nlocal)
void launch_scale_fft (deviceFFT_t *data, double scale, int nlocal, int world_rank, int numBlocks, int blockSize, int calls)
void launch_scale_fft (deviceFFT_t *data, double scale, int nlocal, int numBlocks, int blockSize, int calls)
Function Documentation
launch_scale_amplitudes() [1/2]
void launch_scale_amplitudes (deviceFFT_t * grid, hostFFT_t * scale, int nlocal, int numBlocks, int blockSize, int calls)
Definition at line 19 of file scale_initializer.cu.
{
    launch_scale_amplitudes(grid,scale,nlocal,0,numBlocks,blockSize,calls);
}
References do_return(), and launch_scale_amplitudes().
launch_scale_amplitudes() [2/2]
void launch_scale_amplitudes (deviceFFT_t * grid, hostFFT_t * scale, int nlocal, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 14 of file scale_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernelParallel(ScaleAmplitudes,numBlocks,blockSize,grid,scale,nlocal);
}
References do_return(), getIndent, InvokeGPUKernelParallel, and ScaleAmplitudes().
Referenced by GenerateFourierAmplitudes(), GenerateFourierAmplitudesParallel(), and launch_scale_amplitudes().
launch_scale_fft() [1/2]
void launch_scale_fft (deviceFFT_t * data, double scale, int nlocal, int numBlocks, int blockSize, int calls)
Definition at line 42 of file scale_initializer.cu.
{
    launch_scale_fft(data,scale,nlocal,0,numBlocks,blockSize,calls);
}
References do_return(), and launch_scale_fft().
launch_scale_fft() [2/2]
void launch_scale_fft (deviceFFT_t * data, double scale, int nlocal, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 37 of file scale_initializer.cu.
{
    getIndent(calls);
    InvokeGPUKernelParallel(ScaleFFT,numBlocks,blockSize,data,scale,nlocal);
}
References do_return(), getIndent, InvokeGPUKernelParallel, and ScaleFFT().
Referenced by HACCGPM::parallel::GenerateDisplacementIC(), HACCGPM::serial::GenerateDisplacementIC(), and launch_scale_fft().
ScaleAmplitudes()
__global__ void ScaleAmplitudes (deviceFFT_t *__restrict grid, const hostFFT_t *__restrict scale, int nlocal)
Definition at line 3 of file scale_initializer.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= nlocal)return;
    hostFFT_t base_scale_by = __ldg(&scale[idx]);
    hostFFT_t scale_by = sqrt(base_scale_by);
    deviceFFT_t current = __ldg(&grid[idx]);
    current.x *= scale_by;
    current.y *= scale_by;
    grid[idx] = current;
}
References deviceFFT_t, do_return(), and hostFFT_t.
Referenced by launch_scale_amplitudes().
ScaleFFT()
__global__ void ScaleFFT (deviceFFT_t *__restrict data, double scale, int nlocal)
Definition at line 23 of file scale_initializer.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    deviceFFT_t old = __ldg(&data[idx]);
    old.x *= scale;
    old.y *= scale;
    data[idx] = old;
}
References deviceFFT_t, and do_return().
Referenced by launch_scale_fft().