HACC_GPM: /home/hqureshi/HACC_GPM/src/pm_actions/cuda/float_to_complex_pm.cu File Reference
float_to_complex_pm.cu File Reference
#include "../pm_kernels.hpp"
Functions
__global__ void float2complex (deviceFFT_t *__restrict d_out, const float *__restrict d_in, int n)
__global__ void float2complex (deviceFFT_t *__restrict d_out, const float *__restrict d_in, int3 local_grid_size, int overload)
CPUTimer_t launch_f2c (deviceFFT_t *d_out, float *d_in, int ng, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_f2c (deviceFFT_t *d_out, float *d_in, int3 local_grid_size, int overload, int world_rank, int numBlocks, int blockSize, int calls)
Function Documentation
float2complex() [1/2]
__global__ void float2complex (deviceFFT_t *__restrict d_out, const float *__restrict d_in, int n)
Definition at line 3 of file float_to_complex_pm.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if(idx >= n)return;
    float my_grid = __ldg(&d_in[idx]);
    deviceFFT_t out;
    out.x = my_grid;
    out.y = 0;
    d_out[idx] = out;
}
References deviceFFT_t, and do_return().
Referenced by launch_f2c(), and launch_f2c().
float2complex() [2/2]
__global__ void float2complex (deviceFFT_t *__restrict d_out, const float *__restrict d_in, int3 local_grid_size, int overload)
Definition at line 13 of file float_to_complex_pm.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    int n = (local_grid_size.x + 2*overload)*(local_grid_size.y + 2*overload)*(local_grid_size.z + 2*overload);
    if(idx >= n)return;
    int3 ol_grid_size = make_int3(local_grid_size.x + 2*overload,local_grid_size.y + 2*overload,local_grid_size.z + 2*overload);
    int3 idx3d = HACCGPM::parallel::get_local_index(idx,ol_grid_size.x,ol_grid_size.y,ol_grid_size.z);
    idx3d.x -= overload;
    idx3d.y -= overload;
    idx3d.z -= overload;
    if (idx3d.x < 0)return;
    if (idx3d.y < 0)return;
    if (idx3d.z < 0)return;
    if (idx3d.x >= local_grid_size.x)return;
    if (idx3d.y >= local_grid_size.y)return;
    if (idx3d.z >= local_grid_size.z)return;
    float my_grid = __ldg(&d_in[idx]);
    deviceFFT_t out;
    out.x = my_grid;
    out.y = 0;
    int outidx = idx3d.x * local_grid_size.y * local_grid_size.z + idx3d.y * local_grid_size.z + idx3d.z;
    d_out[outidx] = out;
}
References deviceFFT_t, do_return(), and HACCGPM::parallel::get_local_index().
launch_f2c() [1/2]
CPUTimer_t launch_f2c (deviceFFT_t * d_out, float * d_in, int ng, int numBlocks, int blockSize, int calls)
Definition at line 39 of file float_to_complex_pm.cu.
{
    getIndent(calls);
    return InvokeGPUKernel(float2complex,numBlocks,blockSize,d_out,d_in,ng*ng*ng);
}
References do_return(), float2complex(), getIndent, and InvokeGPUKernel.
Referenced by HACCGPM::parallel::CIC(), and HACCGPM::serial::CIC().
launch_f2c() [2/2]
CPUTimer_t launch_f2c (deviceFFT_t * d_out, float * d_in, int3 local_grid_size, int overload, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 44 of file float_to_complex_pm.cu.
{
    getIndent(calls);
    return InvokeGPUKernelParallel(float2complex,numBlocks,blockSize,d_out,d_in,local_grid_size,overload);
}
References do_return(), float2complex(), getIndent, and InvokeGPUKernelParallel.