HACC_GPM: /home/hqureshi/HACC_GPM/src/power_spectrum/cuda/fold_particles_power.cu File Reference
fold_particles_power.cu File Reference
#include "power_kernels.hpp"
Functions
__global__ void foldParticles (float4 *__restrict d_pos, double ng)
__global__ void ScaleParticles (float4 *__restrict d_pos, double oldNg, double newNg)
__global__ void cpy (float4 *__restrict dest, const float4 *__restrict source)
Function Documentation
cpy()
__global__ void cpy (float4 *__restrict dest, const float4 *__restrict source)
Definition at line 37 of file fold_particles_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    dest[idx] = __ldg(&source[idx]);
}
References do_return().
Referenced by HACCGPM::serial::GetPowerSpectrum().
foldParticles()
__global__ void foldParticles (float4 *__restrict d_pos, double ng)
Definition at line 3 of file fold_particles_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    float4 my_particle = __ldg(&d_pos[idx]);
    my_particle.x /= ng;
    if (my_particle.x >= 0.5){
        my_particle.x -= 0.5;
    }
    my_particle.x *= 2 * ng;
    my_particle.y /= ng;
    if (my_particle.y >= 0.5){
        my_particle.y -= 0.5;
    }
    my_particle.y *= 2 * ng;
    my_particle.z /= ng;
    if (my_particle.z >= 0.5){
        my_particle.z -= 0.5;
    }
    my_particle.z *= 2 * ng;
    d_pos[idx] = my_particle;
}
References do_return().
Referenced by HACCGPM::serial::GetPowerSpectrum().
ScaleParticles()
__global__ void ScaleParticles (float4 *__restrict d_pos, double oldNg, double newNg)
Definition at line 27 of file fold_particles_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    float4 my_particle = __ldg(&d_pos[idx]);
    float mul = newNg/oldNg;
    my_particle.x *= mul;
    my_particle.y *= mul;
    my_particle.z *= mul;
    d_pos[idx] = my_particle;
}
References do_return().