HACC_GPM: /home/hqureshi/HACC_GPM/src/power_spectrum/power_kernels.hpp File Reference
power_kernels.hpp File Reference
#include "haccgpm.hpp"
Functions
__global__ void scalePower (deviceFFT_t *__restrict data, double ng, double rl, int nlocal)
__global__ void PkCICFilter (deviceFFT_t *__restrict grid, int ng, int nlocal, int3 local_grid_size, int3 local_coords)
__global__ void PkCICFilter (deviceFFT_t *__restrict grid, int ng)
__global__ void foldParticles (float4 *__restrict d_pos, double ng)
__global__ void ScaleParticles (float4 *__restrict d_pos, double oldNg, double newNg)
__global__ void cpy (float4 *__restrict dest, const float4 *__restrict source)
__global__ void BinPower (const deviceFFT_t *__restrict d_grid, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng)
__global__ void BinPower (const deviceFFT_t *__restrict d_grid, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng, int nlocal, int world_rank, int3 local_grid_size, int3 local_coords, int3 dims)
Function Documentation
BinPower() [1/2]
__global__ void BinPower (const deviceFFT_t *__restrict d_grid, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng)
Definition at line 18 of file bin_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    deviceFFT_t this_val = __ldg(&d_grid[idx]);
    calc_power_bins(d_binVals,d_binCounts,this_val.x,idx,idx3d,minK,binDelta,rl,ng);
}
References calc_power_bins(), deviceFFT_t, do_return(), and HACCGPM::serial::get_index().
Referenced by HACCGPM::parallel::GetPowerSpectrum(), and HACCGPM::serial::GetPowerSpectrum().
BinPower() [2/2]
__global__ void BinPower (const deviceFFT_t *__restrict d_grid, double *__restrict d_binVals, int *__restrict d_binCounts, double minK, double binDelta, double rl, int ng, int nlocal, int world_rank, int3 local_grid_size, int3 local_coords, int3 dims)
Definition at line 30 of file bin_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    int3 idx3d = HACCGPM::parallel::get_global_index(idx,ng,local_grid_size,local_coords);
    deviceFFT_t this_val = __ldg(&d_grid[idx]);
    calc_power_bins(d_binVals,d_binCounts,this_val.x,idx,idx3d,minK,binDelta,rl,ng);
}
References calc_power_bins(), deviceFFT_t, do_return(), and HACCGPM::parallel::get_global_index().
cpy()
__global__ void cpy (float4 *__restrict dest, const float4 *__restrict source)
Definition at line 37 of file fold_particles_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    dest[idx] = __ldg(&source[idx]);
}
References do_return().
Referenced by HACCGPM::serial::GetPowerSpectrum().
foldParticles()
__global__ void foldParticles (float4 *__restrict d_pos, double ng)
Definition at line 3 of file fold_particles_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    float4 my_particle = __ldg(&d_pos[idx]);
    my_particle.x /= ng;
    if (my_particle.x >= 0.5){
        my_particle.x -= 0.5;
    }
    my_particle.x *= 2 * ng;
    my_particle.y /= ng;
    if (my_particle.y >= 0.5){
        my_particle.y -= 0.5;
    }
    my_particle.y *= 2 * ng;
    my_particle.z /= ng;
    if (my_particle.z >= 0.5){
        my_particle.z -= 0.5;
    }
    my_particle.z *= 2 * ng;
    d_pos[idx] = my_particle;
}
References do_return().
Referenced by HACCGPM::serial::GetPowerSpectrum().
PkCICFilter() [1/2]
__global__ void PkCICFilter (deviceFFT_t *__restrict grid, int ng)
Definition at line 47 of file filter_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    double filter = get_pk_cic_filter(idx3d,ng);
    deviceFFT_t my_grid = __ldg(&grid[idx]);
    my_grid.x *= filter;
    grid[idx] = my_grid;
}
References deviceFFT_t, do_return(), HACCGPM::serial::get_index(), and get_pk_cic_filter().
PkCICFilter() [2/2]
__global__ void PkCICFilter (deviceFFT_t *__restrict grid, int ng, int nlocal, int3 local_grid_size, int3 local_coords)
Definition at line 34 of file filter_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    int3 idx3d = HACCGPM::parallel::get_global_index(idx,ng,local_grid_size,local_coords);
    double filter = get_pk_cic_filter(idx3d,ng);
    deviceFFT_t my_grid = __ldg(&grid[idx]);
    my_grid.x *= filter;
    grid[idx] = my_grid;
}
References deviceFFT_t, do_return(), HACCGPM::parallel::get_global_index(), and get_pk_cic_filter().
Referenced by HACCGPM::parallel::GetPowerSpectrum(), and HACCGPM::serial::GetPowerSpectrum().
ScaleParticles()
__global__ void ScaleParticles (float4 *__restrict d_pos, double oldNg, double newNg)
Definition at line 27 of file fold_particles_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    float4 my_particle = __ldg(&d_pos[idx]);
    float mul = newNg/oldNg;
    my_particle.x *= mul;
    my_particle.y *= mul;
    my_particle.z *= mul;
    d_pos[idx] = my_particle;
}
References do_return().
scalePower()
__global__ void scalePower (deviceFFT_t *__restrict data, double ng, double rl, int nlocal)
Definition at line 3 of file scale_power.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= nlocal)return;
    double scale = (1.0f/(ng*ng*ng)) * (rl/ng);
    deviceFFT_t old = __ldg(&data[idx]);
    old.x = (old.x * old.x + old.y * old.y) * scale;
    data[idx] = old;
}
References deviceFFT_t, and do_return().
Referenced by HACCGPM::parallel::GetPowerSpectrum(), and HACCGPM::serial::GetPowerSpectrum().