HACC_GPM: /home/hqureshi/HACC_GPM/src/pm_solver/cuda/get_greens.cu File Reference
get_greens.cu File Reference
#include <stdlib.h>
#include <stdio.h>
#include <cassert>
#include "../kernels.hpp"
Macros
#define VerboseGreens
Functions
__device__ __forceinline__ double3 cos (float3 kmodes)
__forceinline__ __device__ double calcGreens (int3 idx3d, int ng)
__global__ void getGreensKernel (hostFFT_t *__restrict d_greens, int ng)
__global__ void getGreensParallelKernel (hostFFT_t *__restrict d_greens, int ng, int3 local_grid_size, int3 local_coords)
CPUTimer_t launch_getgreens (hostFFT_t *__restrict d_greens, int ng, int numBlocks, int blockSize, int calls)
CPUTimer_t launch_getgreens (hostFFT_t *__restrict d_greens, int ng, int nlocal, int3 local_grid_size_vec, int3 grid_coords_vec, int world_rank, int numBlocks, int blockSize, int calls)
Macro Definition Documentation
VerboseGreens
#define VerboseGreens
Definition at line 6 of file get_greens.cu.
Function Documentation
calcGreens()
__forceinline__ __device__ double calcGreens (int3 idx3d, int ng)
Definition at line 16 of file get_greens.cu.
{
    if ((idx3d.x == 0) && (idx3d.y == 0) && (idx3d.z == 0))return 0.0;
    float d = ((2*M_PI)/(((float)(ng))));
    double3 c = cos(idx3d * d);
    float3 kmodes = HACCGPM::get_kmodes(idx3d,ng,d);
    double coeff = 0.5 / (ng*ng*ng);
    double out = coeff / (c.x + c.y + c.z - 3.0);
    return out;
}
References cos(), do_return(), and HACCGPM::get_kmodes().
Referenced by getGreensKernel(), and getGreensParallelKernel().
cos()
__device__ __forceinline__ double3 cos (float3 kmodes)
Definition at line 8 of file get_greens.cu.
{
    double3 out;
    out.x = cos(kmodes.x);
    out.y = cos(kmodes.y);
    out.z = cos(kmodes.z);
    return out;
}
References cos(), and do_return().
Referenced by calcGreens(), and cos().
getGreensKernel()
__global__ void getGreensKernel (hostFFT_t *__restrict d_greens, int ng)
Definition at line 34 of file get_greens.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    int3 idx3d = HACCGPM::serial::get_index(idx,ng);
    d_greens[idx] = calcGreens(idx3d,ng);
}
References calcGreens(), do_return(), and HACCGPM::serial::get_index().
Referenced by launch_getgreens().
getGreensParallelKernel()
__global__ void getGreensParallelKernel (hostFFT_t *__restrict d_greens, int ng, int3 local_grid_size, int3 local_coords)
Definition at line 44 of file get_greens.cu.
{
    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    int n = local_grid_size.x*local_grid_size.y*local_grid_size.z;
    if (idx >= n)return;
    int3 idx3d = HACCGPM::parallel::get_global_index(idx,ng,local_grid_size,local_coords);
    d_greens[idx] = calcGreens(idx3d,ng);
}
References calcGreens(), do_return(), and HACCGPM::parallel::get_global_index().
Referenced by launch_getgreens().
launch_getgreens() [1/2]
CPUTimer_t launch_getgreens (hostFFT_t *__restrict d_greens, int ng, int nlocal, int3 local_grid_size_vec, int3 grid_coords_vec, int world_rank, int numBlocks, int blockSize, int calls)
Definition at line 66 of file get_greens.cu.
{
    getIndent(calls);
    return InvokeGPUKernelParallel(getGreensParallelKernel,numBlocks,blockSize,d_greens,ng,local_grid_size_vec,grid_coords_vec);
}
References do_return(), getGreensParallelKernel(), getIndent, and InvokeGPUKernelParallel.
launch_getgreens() [2/2]
CPUTimer_t launch_getgreens (hostFFT_t *__restrict d_greens, int ng, int numBlocks, int blockSize, int calls)
Definition at line 58 of file get_greens.cu.
{
    getIndent(calls);
    return InvokeGPUKernel(getGreensKernel,numBlocks,blockSize,d_greens,ng);
}
References do_return(), getGreensKernel(), getIndent, and InvokeGPUKernel.
Referenced by HACCGPM::parallel::InitGreens(), and HACCGPM::serial::InitGreens().