HACC: /home/hqureshi/HACC_GPM/particleswapkernels.cu File Reference
/home/hqureshi/HACC_GPM/particleswapkernels.cu File Reference
#include <stdlib.h>
#include <stdio.h>
#include "haccgpm.hpp"
#include "bdwgc/include/gc.h"
Macros
#define VerboseSwap
Functions
__global__ void swap_set_invalid (float4 *__restrict d_pos, int mem_frac)
__global__ void copy (float4 *__restrict dest1, const float4 *__restrict source1, float4 *__restrict dest2, const float4 *__restrict source2, int n)
__global__ void count_buffer (int *ns, const float4 *__restrict d_pos, int n_particles, int3 local_grid_size)
__global__ void load_buffer (float4 *__restrict d_pos, float4 *__restrict d_vel, float4 *__restrict d_pos_swap, float4 *__restrict d_vel_swap, int *count, int *starts, const float4 *__restrict d_tmppos, const float4 *__restrict d_tmpvel, int3 local_grid_size, int n_particles, int world_rank)
__global__ void findDuplicates (const float4 *__restrict d_pos, float4 *__restrict new_particles, int n_new, int n_particles)
__global__ void combineParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, const float4 *__restrict new_pos, const float4 *__restrict new_vel, int n_new, int remaining, int n_particles)
__global__ void loadGridBuffersKernel (float *__restrict d_out, const float *__restrict d_grid, int3 local_grid_size, int n_extra)
Macro Definition Documentation
VerboseSwap
#define VerboseSwap
Definition at line 6 of file particleswapkernels.cu.
Function Documentation
combineParticles()
__global__ void combineParticles (float4 *__restrict d_pos, float4 *__restrict d_vel, const float4 *__restrict new_pos, const float4 *__restrict new_vel, int n_new, int remaining, int n_particles)
Definition at line 100 of file particleswapkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= n_new)return;
    float4 my_particle = __ldg(&new_pos[idx]);
    if (my_particle.w < -1)return;
    float4 my_vel = __ldg(&new_vel[idx]);
    int dest = idx + remaining;
    d_pos[dest] = my_particle;
    d_vel[dest] = my_vel;
}
Referenced by HACCGPM::parallel::insertParticles().
copy()
__global__ void copy (float4 *__restrict dest1, const float4 *__restrict source1, float4 *__restrict dest2, const float4 *__restrict source2, int n)
Definition at line 14 of file particleswapkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= n)return;
    float4 my_particle = __ldg(&source1[idx]);
    float4 my_vel = __ldg(&source2[idx]);
    dest1[idx] = my_particle;
    dest2[idx] = my_vel;
}
Referenced by HACCGPM::parallel::loadIntoBuffers().
count_buffer()
__global__ void count_buffer (int * ns, const float4 *__restrict d_pos, int n_particles, int3 local_grid_size)
Definition at line 23 of file particleswapkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= n_particles)return;
    float4 my_particle = __ldg(&d_pos[idx]);
    if (my_particle.w < -1)return;
    for (int i = 0; i < 27; i++){
        int x = (i/3)/3;
        int y = (i - x*3*3)/3;
        int z = i - x*3*3 - y*3;
        x = (x-1)*local_grid_size.x;
        y = (y-1)*local_grid_size.y;
        z = (z-1)*local_grid_size.z;
        float3 tmp_particle = make_float3(my_particle.x - x, my_particle.y - y, my_particle.z - z);
        if ((tmp_particle.x >= 0.0f && tmp_particle.x < local_grid_size.x) &&
            (tmp_particle.y >= 0.0f && tmp_particle.y < local_grid_size.y) &&
            (tmp_particle.z >= 0.0f && tmp_particle.z < local_grid_size.z)){
                //printf("Particle %g %g %g %g going to idx %d\n",my_particle.x,my_particle.y,my_particle.z,my_particle.w,i);
                atomicAdd(&ns[i],1);
            }
    }
}
Referenced by HACCGPM::parallel::loadIntoBuffers().
findDuplicates()
__global__ void findDuplicates (const float4 *__restrict d_pos, float4 *__restrict new_particles, int n_new, int n_particles)
Definition at line 86 of file particleswapkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= n_particles)return;
    float4 my_particle = __ldg(&d_pos[idx]);
    for (int i = 0; i < n_new; i++){
        float4 other_particle = __ldg(&new_particles[i]);
        if (my_particle.w == other_particle.w){
            //printf("DUPLICATE!!!\n");
            new_particles[i] = make_float4(0,0,0,-10);
            return;
        }
    }
}
load_buffer()
__global__ void load_buffer (float4 *__restrict d_pos, float4 *__restrict d_vel, float4 *__restrict d_pos_swap, float4 *__restrict d_vel_swap, int * count, int * starts, const float4 *__restrict d_tmppos, const float4 *__restrict d_tmpvel, int3 local_grid_size, int n_particles, int world_rank)
Definition at line 46 of file particleswapkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= n_particles)return;
    float4 my_particle = __ldg(&d_tmppos[idx]);
    if (my_particle.w < -1)return;
    float4 my_vel = __ldg(&d_tmpvel[idx]);
    for (int i = 0; i < 27; i++){
        int x = (i/3)/3;
        int y = (i - x*3*3)/3;
        int z = i - x*3*3 - y*3;
        x = (x-1)*local_grid_size.x;
        y = (y-1)*local_grid_size.y;
        z = (z-1)*local_grid_size.z;
        float4 tmp_particle = make_float4(my_particle.x - x, my_particle.y - y, my_particle.z - z, my_particle.w);
        if ((tmp_particle.x >= 0.0f && tmp_particle.x < local_grid_size.x) &&
            (tmp_particle.y >= 0.0f && tmp_particle.y < local_grid_size.y) &&
            (tmp_particle.z >= 0.0f && tmp_particle.z < local_grid_size.z)){
                //printf("Particle %g %g %g %g going to idx %d\n",my_particle.x,my_particle.y,my_particle.z,my_particle.w,i);
                float4* pos_dest;
                float4* vel_dest;
                pos_dest = d_pos;
                vel_dest = d_vel;
                if (i != 13){
                    int start = starts[i];
                    pos_dest = &d_pos_swap[start];
                    vel_dest = &d_vel_swap[start];
                }
                int j = atomicAdd(&count[i],1);
                pos_dest[j] = tmp_particle;
                vel_dest[j] = my_vel;
                /*if (i > 13){
                    if (world_rank == 0){
                        printf("i=%d j=%d [%g %g %g %g]\n",i,j,pos_dest[j].x,pos_dest[j].y,pos_dest[j].z,pos_dest[j].w);
                    }
                }*/
            }
    }
}
Referenced by HACCGPM::parallel::loadIntoBuffers().
loadGridBuffersKernel()
__global__ void loadGridBuffersKernel (float *__restrict d_out, const float *__restrict d_grid, int3 local_grid_size, int n_extra)
THIS IS WRONG!!!! PLEASE FIX. THE INDEXES ARE NOT ALWAYS CONTIGUOUS...
Definition at line 111 of file particleswapkernels.cu.
{
    int idx = threadIdx.x+blockDim.x+blockIdx.x;
    if (idx >= n_extra)return;
    //int3 start = make_int3(0,0,0);
    int x = local_grid_size.x;
    int y = local_grid_size.y;
    int z = local_grid_size.z;
    int tmp_idx = idx;
    for (int i = 1; i < 8; i++){
        int l = i/4;
        int m = (i - l*4)/2;
        int n = (i - l*4) - m*2;
        int l_mul = ((l+1)%2)*x;
        int m_mul = ((m+1)%2)*y;
        int n_mul = ((n+1)%2)*z;
        if (l_mul == 0){
            l_mul = 1;
        }
        if (m_mul == 0){
            m_mul == 1;
        }
        if (n_mul == 0){
            n_mul == 1;
        }
        int bin_size = l_mul*m_mul*n_mul;
        if (tmp_idx < bin_size){
            int global_index = x * l * (y+1)*(z+1) + y * m * (z+1) + (z+1) * n + tmp_idx;
            float my_cell = __ldg(&d_grid[global_index]);
            d_out[idx] = my_cell;
            return;
        }
        tmp_idx -= bin_size;
    }
    /*if (0 <= tmp_idx < z*y){
        start.z = z;
    } else{
        tmp_idx -= z*y;
        if (0 <= tmp_idx < y*x){
            start.y = y;
        } else {
            tmp_idx -= y*x;
            if (0 <= tmp_idx < y){
                start.y = y;
                start.z = z;
            } else {
                tmp_idx -= y;
                if (0 <= tmp_idx < z*x){
                    start.x = x;
                } else {
                    tmp_idx -= z*x;
                    if (0 <= tmp_idx < z){
                        start.x = x;
                        start.z = z;
                    } else {
                        tmp_idx -= z;
                        if (0 <= tmp_idx < x){
                            start.x = x;
                            start.y = y;
                        } else{
                            start.x = x;
                            start.y = y;
                            start.z = z;
                        }}}}}}*/
    /*int global_index = start.x * (y+1)*(z+1) + start.y * (z+1) + start.z + 1 + tmp_idx;
    float my_cell = __ldg(&d_grid[global_index]);
    d_out[idx] = my_cell;*/
}
Referenced by HACCGPM::parallel::loadGridBuffers().
swap_set_invalid()
__global__ void swap_set_invalid (float4 *__restrict d_pos, int mem_frac)
Definition at line 8 of file particleswapkernels.cu.
{
    int idx = threadIdx.x+blockDim.x*blockIdx.x;
    if (idx >= mem_frac) return;
    d_pos[idx] = make_float4(0,0,0,-10);
}
Referenced by HACCGPM::parallel::loadIntoBuffers().